# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'project_employee_page1.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys


import mysql
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QDate
from PyQt5.QtGui import QColor
from PyQt5.QtWidgets import QMessageBox
from db import con
from archive_dtr import Ui_DTRA,Ui_Payroll
from archive_transaction import Ui_Trans
from archive_summary import Ui_Summary
from dialogs import Dialog


class Ui_AE(object):
    ProjectTab=""
    BtnBack=""
    projectid=0
    BtnDtr=""
    BtnPayroll=""
    BtnTransaction=""
    BtnSummary=""


    Allowid=0
    Cashid=0

    PEList=""

    employee_id = []
    employee_fname = []
    employee_lname = []
    employee_mname = []
    employee_position = []

    LEName = ""
    LEBday = ""
    LEAge = ""
    LESex = ""
    LEContact = ""
    LEJob = ""

    LBName=""
    LBBday=""
    LBAge=""
    LBSex=""
    LBContact=""
    LBJob=""
    ImgEmployee=""
    LBRate=""


    LERate=""
    DateWorkStart=""
    DateWorkEnd=""

    itemid=0

    TBLAllowance=""
    TBLCash=""

    # Table Date & LE
    TBADates=[]
    TBCDates=[]
    TBALE=[]
    TBCLE=[]


    TBAid=[]
    TBCid=[]
    LBProjectTitle=""

    # status
    editable = QtCore.Qt.ItemIsSelectable | QtCore.Qt.ItemIsEnabled | QtCore.Qt.ItemIsEditable
    not_editable = QtCore.Qt.ItemIsSelectable | QtCore.Qt.ItemIsEnabled 

    def setProjectTitle():
        try:
            cursor = con.cursor()
            cursor.execute(f"SELECT * FROM `projects` WHERE `project_id` = {Ui_AE.projectid}")
            res = cursor.fetchall()
            Ui_AE.LBProjectTitle.setText(res[0][1])

        except:
            Dialog.msg_dialog(str(sys.exc_info()))


    def showpage(page):
        Ui_AE.StackProject.setCurrentWidget(page)
    def showdtr(page):
        Ui_AE.StackProject.setCurrentWidget(page)
        Ui_DTRA.projectid=Ui_AE.projectid
        # Insert Items(Week) at DTR List (Default Values)
        Ui_DTRA.insert_week()
        
    def showpayroll(page):
        Ui_AE.StackProject.setCurrentWidget(page)
        Ui_DTRA.projectid=Ui_AE.projectid
        Ui_DTRA.insert_week()
        Ui_Payroll.insert_week()
        Ui_Payroll.resetTable()

    def showtrans(page):
        Ui_Trans.project_id=Ui_AE.projectid
        Ui_Trans.projectName=Ui_AE.LBProjectTitle.text()

        Ui_AE.StackProject.setCurrentWidget(page)
        # Insert Data in Transaction Table
        Ui_Trans.insert_trans(Ui_Trans.not_editable,False) # Default Cell non editable

    def showsummary(page):
        Ui_AE.StackProject.setCurrentWidget(page)
        Ui_Summary.project_id=Ui_AE.projectid
        Ui_Summary.get_summary()


    
    
    def getAllowance(table,status,edit_status):

        #Font for Input
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        # Regex
        my_regex = QtCore.QRegExp("^\\d{1,6}(\\.\\d{1,2})?$")

        try:
            cursor = con.cursor()
            cursor.execute(f"SELECT * FROM `projecte_balance` WHERE `employee_id` = {Ui_AE.itemid} AND `project_id`={Ui_AE.projectid} AND `title`='Add Allowance'")
            res = cursor.fetchall()
            row=0
            while (table.rowCount() > 0):
                table.removeRow(0)
            table.setRowCount(len(res))
            Ui_AE.TBADates=[]
            Ui_AE.TBAid=[]

            for x in res:

                Ui_AE.TBAid.append(x[0])

                #LEReceipt
                LEAllow = QtWidgets.QLineEdit(Ui_Trans.TBLTrans)
                LEAllow.setGeometry(QtCore.QRect(0, 0, 100, 31))
                LEAllow.setAlignment(QtCore.Qt.AlignCenter)
                LEAllow.setStyleSheet("color:white;")
                LEAllow.setObjectName("LEAllow")
                LEAllow.setText(str(x[5]))
                LEAllow.setEnabled(edit_status)
                LEAllow.setAlignment(QtCore.Qt.AlignCenter)
                LEAllow.setFont(font)

                my_validator = QtGui.QRegExpValidator(my_regex,LEAllow)
                LEAllow.setValidator(my_validator)

                table.setCellWidget(row, 0, LEAllow)

                DateAllow = QtWidgets.QDateEdit(table)
                DateAllow.setCalendarPopup(True)
                DateAllow.setDate(Ui_AE.process_date(x[4]))
                DateAllow.setEnabled(edit_status) 
                DateAllow.setFont(font)
                DateAllow.setAlignment(QtCore.Qt.AlignCenter)
                Ui_AE.TBADates.append(DateAllow)
                table.setCellWidget(row, 1, Ui_AE.TBADates[row])
                row=row+1


        except:
            Dialog.msg_dialog(str(sys.exc_info()))

    def getCashAdvance(table,status,edit_status):

        #Font for Input
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        # Regex
        less_regex = QtCore.QRegExp("^\\-\\d{1,6}(\\.\\d{1,2})?$")
        my_regex = QtCore.QRegExp("^\\d{1,6}(\\.\\d{1,2})?$")
        try:
            cursor = con.cursor()
            cursor.execute(f"SELECT * FROM `projecte_balance` WHERE `employee_id` = {Ui_AE.itemid} AND `project_id`={Ui_AE.projectid} AND `title` IN ('Add Cash Advance','Less Cash Advance')")
            res = cursor.fetchall()
            while (table.rowCount() > 0):
                table.removeRow(0)
            table.setRowCount(len(res))
            row=0
            Ui_AE.TBCDates=[]
            Ui_AE.TBCid=[]
            for x in res:
                Ui_AE.TBCid.append(x[0])

                #LEReceipt
                LECash = QtWidgets.QLineEdit(Ui_Trans.TBLTrans)
                LECash.setGeometry(QtCore.QRect(0, 0, 100, 31))
                LECash.setAlignment(QtCore.Qt.AlignCenter)
                LECash.setStyleSheet("color:white;")
                LECash.setObjectName("LECash")
                LECash.setText(str(x[5]))
                LECash.setEnabled(edit_status)
                LECash.setAlignment(QtCore.Qt.AlignCenter)
                LECash.setFont(font)
                cash = str(x[5])
                if (cash[0] == "-"):
                    my_validator = QtGui.QRegExpValidator(less_regex,LECash)
                else:
                    my_validator = QtGui.QRegExpValidator(my_regex,LECash)
                
                LECash.setValidator(my_validator)

                table.setCellWidget(row, 0, LECash)


                DateAllow = QtWidgets.QDateEdit(table)
                DateAllow.setCalendarPopup(True)
                DateAllow.setDate(Ui_AE.process_date(x[4]))
                DateAllow.setEnabled(edit_status)
                DateAllow.setAlignment(QtCore.Qt.AlignCenter)
                DateAllow.setFont(font)
                Ui_AE.TBCDates.append(DateAllow)
                table.setCellWidget(row, 1, Ui_AE.TBCDates[row])
                row=row+1
                
                
        except:
            Dialog.msg_dialog(str(sys.exc_info()))




    def addTable(table):
        now = QDate.currentDate()
        item = table.item(0, 0)
        item.setText("tesing")
        DateAllow = QtWidgets.QDateEdit(table)
        DateAllow.setCalendarPopup(True)
        DateAllow.setDate(now)
        table.setCellWidget(0, 1, DateAllow)


    def SaveCash2():
        Ui_AE.BtnBack.show()

        try:
            rows = Ui_AE.TBLCash.rowCount()

            x=0
            for i in range(rows):
                date = (f"{Ui_AE.TBCDates[x].date().year()},{Ui_AE.TBCDates[x].date().month()},{Ui_AE.TBCDates[x].date().day()}")
                balance = Ui_AE.TBLCash.cellWidget(x,0).text()

                cursor = con.cursor()
                query1 = (f"UPDATE `projecte_balance` SET `date` = '{date}', `balance` = {balance} WHERE `id` = {Ui_AE.TBCid[x]}")
                cursor.execute(query1)
                con.commit()
                x=x+1

                Ui_AE.getCashAdvance(Ui_AE.TBLCash,Ui_AE.not_editable,False)
                Ui_AE.ProjectTab.setEnabled(True)

        except:
                Dialog.msg_dialog(str(sys.exc_info()))

        index=0
        for i in range(len(Ui_AE.TBADates)):
            Ui_AE.TBCDates[index].setEnabled(False)
            index = index+1

        Ui_BalanceForm.updatePayrollBalance()


    def process_date(bday):
        index = 0
        start = 0
        flag1 = True
        flag2 = False
        flag3 = False

        while index < len(bday):
            if flag1 and (bday[index] == ","):
                year = bday[start:index]
                start = index + 1
                flag1 = False
                flag2 = True
            elif flag2 and (bday[index] == ","):
                month = bday[start:index]
                start = index + 1
                flag2 = False
                flag3 = True
            if flag3:
                day = bday[start:len(bday)]
                break
            index = index + 1

        return QDate(int(year), int(month), int(day))

    def get_info(item):
        Ui_AE.itemid = item.value
        # Ui_AE.search_area.setText("")

        try:
            Ui_AE.set_info()
            #call get allow

            Ui_AE.getAllowance(Ui_AE.TBLAllowance,Ui_AE.not_editable,False)
            Ui_AE.getCashAdvance(Ui_AE.TBLCash,Ui_AE.not_editable,False)

        except:
            Dialog.msg_dialog(str(sys.exc_info()))

    def removeEmployee():
        
        if Ui_AE.itemid >0:
            if (Dialog.confirm_dialog("Are you sure you want to remove employee from the project?") == QMessageBox.Ok):
                try:
                    cursor = con.cursor()
                    query1 = (f"UPDATE `employees` SET `Designated`='No',`Current_Site`='None' WHERE `id` = {Ui_AE.itemid}")
                    cursor.execute(query1)
                    con.commit()
    
                    query2 = (f"DELETE FROM `projecte` WHERE `employee_id` = {Ui_AE.itemid} AND `project_id`={Ui_AE.projectid}")
                    cursor.execute(query2)
                    con.commit()
                    query2 = (f"DELETE FROM `projecte_balance` WHERE `employee_id` = {Ui_AE.itemid} AND `project_id`={Ui_AE.projectid}")
                    cursor.execute(query2)
                    con.commit()

                    query2 = (f"DELETE FROM `projectdtr` WHERE `employee_id` = {Ui_AE.itemid} AND `project_id`={Ui_AE.projectid}")
                    cursor.execute(query2)
                    con.commit()

                    query2 = (f"DELETE FROM `project_payroll` WHERE `employee_id` = {Ui_AE.itemid} AND `project_id`={Ui_AE.projectid}")
                    cursor.execute(query2)
                    con.commit()


                    Dialog.msg_dialog("Employee has been removed from the project")
                    Ui_AE.getProjEmp()
                    Ui_AE.LEName.setText("")
                    Ui_AE.LEAge.setText("")
                    Ui_AE.LEContact.setText("")
                    Ui_AE.LESex.setText("")
                    Ui_AE.LEJob.setText("")
    
                    Ui_AE.ImgEmployee.clear()
                    Ui_AE.ImgEmployee.setStyleSheet("color: rgb(255, 255, 255);\n"
                                                    "background-color: rgba(0, 0, 0,0.8);")
                    Ui_AE.ImgEmployee.setText("")
    
                    Ui_AE.LEBday.setText("")
                    Ui_AE.LERate.setText("Rate/Hour")
                    now  = QDate.currentDate()
                    Ui_AE.DateWorkStart.setDate(now)
                    Ui_AE.DateWorkEnd.setDate(now)

    
    
                except:
                    Dialog.msg_dialog(str(sys.exc_info()))
        else:
            Dialog.msg_dialog("Please select an employee first")



    def set_info():
        # get_info_database
        if Ui_AE.itemid > 0:
            try:
                cursor = con.cursor()
                cursor.execute(f"SELECT * FROM `employees` WHERE `id` = {Ui_AE.itemid}")
                res = cursor.fetchall()

                for x in res:
                    suffix = ""
                    if x[4] == "N/A":

                        suffix = ""
                    else:
                        suffix = x[4]

                    full_name = (f"{x[2]} {x[3]}. {x[1]} {suffix}")

                    Ui_AE.LEName.setText(full_name)
                    Ui_AE.LEAge.setText(str(x[7]))
                    Ui_AE.LEContact.setText(f"0{x[8]}")
                    Ui_AE.LESex.setText(x[5])
                    Ui_AE.LEJob.setText(x[15])

                    qimg = QtGui.QImage.fromData(x[16])
                    pixmap = QtGui.QPixmap.fromImage(qimg)
                    pixmap5 = pixmap.scaled(Ui_AE.ImgEmployee.width(), Ui_AE.ImgEmployee.height())

                    Ui_AE.ImgEmployee.setPixmap(pixmap5)
                    Ui_AE.ImgEmployee.setStyleSheet("color: rgb(255, 255, 255);\n"
                                                    "background-color: rgba(0, 0, 0,0.8);")
                    Ui_AE.ImgEmployee.setText("")
                    Ui_AE.LEBday.setText(x[6].replace(",","/"))

                cursor.execute(f"SELECT * FROM `projecte` WHERE `employee_id` = {Ui_AE.itemid} AND `project_id`={Ui_AE.projectid}")
                res2 = cursor.fetchall()
                for y in res2:
                    Ui_AE.LERate.setText(str(y[3]))
                    Ui_AE.DateWorkStart.setDate(Ui_AE.process_date(y[4]))
                    Ui_AE.DateWorkEnd.setDate(Ui_AE.process_date(y[5]))


            except mysql.connector.Error as e:
                Dialog.msg_dialog(str(e))


                

    def getProjEmp():
            Ui_AE.PEList.clear()
            # get_info_database
            try:
                    res = Ui_AE.mysql_select()
                    Ui_AE.employee_id=[]
                    Ui_AE.employee_fname=[]
                    Ui_AE.employee_lname=[]
                    Ui_AE.employee_mname=[]
                    Ui_AE.employee_position=[]

                    for x in res:
                            Ui_AE.employee_id.append(x[0][0])
                            Ui_AE.employee_fname.append(x[0][2])
                            Ui_AE.employee_lname.append(x[0][1])
                            Ui_AE.employee_mname.append(x[0][3])
                            Ui_AE.employee_position.append(x[0][15])

            except mysql.connector.Error as e:
                    Dialog.msg_dialog(str(e))

            # insert elements
            index = 0
            while index < len(Ui_AE.employee_id):
                    try:
                            full_name = (
                                    f"{Ui_AE.employee_lname[index]}, {Ui_AE.employee_fname[index]} {Ui_AE.employee_mname[index]}.\n[{Ui_AE.employee_position[index]}]")
                            item = QtWidgets.QListWidgetItem(full_name)
                            item.setBackground(QColor('#666666')) if (index % 2) == 0 else item.setBackground(
                                    QColor('#595959'))
                            item.value = Ui_AE.employee_id[index]
                            item.setTextAlignment(QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
                            Ui_AE.PEList.addItem(item)
                            index = index + 1
                    except:
                            Dialog.msg_dialog(str(sys.exc_info()))

    def mysql_select():
            cursor = con.cursor()

            cursor.execute(f"SELECT * FROM `projecte` WHERE `project_id`='{Ui_AE.projectid}' ")
            res = cursor.fetchall()

            emp=[]
            for x in res:
                cursor.execute(f"SELECT * FROM `employees` WHERE `id`='{x[2]}' ")
                emp.append(cursor.fetchall())

            return emp

        
    def PE(Project_E,DashbaordWindow):
        Ui_AE.LBProjectTitle = QtWidgets.QLabel(Project_E)
        Ui_AE.LBProjectTitle.setGeometry(QtCore.QRect(10, 10, 271, 71))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        Ui_AE.LBProjectTitle.setFont(font)
        Ui_AE.LBProjectTitle.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        Ui_AE.LBProjectTitle.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(148, 0, 2,.4);\n"
"border-radius:8px;\n"
"\n"
"\n"
"\n"
"")
        Ui_AE.LBProjectTitle.setTextFormat(QtCore.Qt.AutoText)
        Ui_AE.LBProjectTitle.setAlignment(QtCore.Qt.AlignCenter)
        Ui_AE.LBProjectTitle.setWordWrap(True)
        Ui_AE.LBProjectTitle.setIndent(-1)
        Ui_AE.LBProjectTitle.setObjectName("Ui_AE.LBProjectTitle")
        Ui_AE.ProjectTab = QtWidgets.QGroupBox(Project_E)
        Ui_AE.ProjectTab.setGeometry(QtCore.QRect(310, 10, 741, 71))
        Ui_AE.ProjectTab.setStyleSheet("border:none;")
        Ui_AE.ProjectTab.setTitle("")
        Ui_AE.ProjectTab.setObjectName("Ui_AE.ProjectTab")
        BtnEmployee = QtWidgets.QPushButton(Ui_AE.ProjectTab)
        BtnEmployee.setGeometry(QtCore.QRect(20, 20, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        BtnEmployee.setFont(font)
        BtnEmployee.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        BtnEmployee.setStyleSheet("color: rgb(255, 255, 255);")
        BtnEmployee.setObjectName("BtnEmployee")
        BtnDtr = QtWidgets.QPushButton(Ui_AE.ProjectTab)
        BtnDtr.setGeometry(QtCore.QRect(180, 20, 75, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        BtnDtr.setFont(font)
        BtnDtr.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        BtnDtr.setStyleSheet("color: rgb(255, 255, 255);")
        BtnDtr.setObjectName("BtnDtr")
        BtnPayroll = QtWidgets.QPushButton(Ui_AE.ProjectTab)
        BtnPayroll.setGeometry(QtCore.QRect(300, 20, 75, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        BtnPayroll.setFont(font)
        BtnPayroll.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        BtnPayroll.setStyleSheet("color: rgb(255, 255, 255);")
        BtnPayroll.setObjectName("BtnPayroll")
        BtnTransaction = QtWidgets.QPushButton(Ui_AE.ProjectTab)
        BtnTransaction.setGeometry(QtCore.QRect(420, 20, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        BtnTransaction.setFont(font)
        BtnTransaction.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        BtnTransaction.setStyleSheet("color: rgb(255, 255, 255);")
        BtnTransaction.setObjectName("BtnTransaction")
        BtnSummary = QtWidgets.QPushButton(Ui_AE.ProjectTab)
        BtnSummary.setGeometry(QtCore.QRect(600, 20, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        BtnSummary.setFont(font)
        BtnSummary.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        BtnSummary.setStyleSheet("color: rgb(255, 255, 255);")
        BtnSummary.setObjectName("BtnSummary")
        BGtab = QtWidgets.QLabel(Ui_AE.ProjectTab)
        BGtab.setGeometry(QtCore.QRect(0, 0, 741, 71))
        BGtab.setStyleSheet("background-color: rgb(148, 0, 2,.4);\n"
"border-radius:8px;\n"
"\n"
"")
        BGtab.setText("")
        BGtab.setObjectName("BGtab")
        BGtab.raise_()
        BtnEmployee.raise_()
        BtnDtr.raise_()
        BtnPayroll.raise_()
        BtnTransaction.raise_()
        BtnSummary.raise_()
        Ui_AE.StackProject = QtWidgets.QStackedWidget(Project_E)
        Ui_AE.StackProject.setGeometry(QtCore.QRect(0, 110, 1051, 411))
        Ui_AE.StackProject.setStyleSheet("")
        Ui_AE.StackProject.setObjectName("Ui_AE.StackProject")
        ProjectEmployee = QtWidgets.QWidget()
        ProjectEmployee.setObjectName("ProjectEmployee")
        LBProjectEmp = QtWidgets.QLabel(ProjectEmployee)
        LBProjectEmp.setGeometry(QtCore.QRect(10, 10, 271, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        LBProjectEmp.setFont(font)
        LBProjectEmp.setStyleSheet("color: rgb(255, 255, 255);\n"
"")
        LBProjectEmp.setAlignment(QtCore.Qt.AlignCenter)
        LBProjectEmp.setObjectName("LBProjectEmp")
        EmpInfo = QtWidgets.QGroupBox(ProjectEmployee)
        EmpInfo.setGeometry(QtCore.QRect(310, 0, 741, 141))
        EmpInfo.setStyleSheet("border:none;\n"
"color:white;")
        EmpInfo.setTitle("")
        EmpInfo.setObjectName("EmpInfo")
        Ui_AE.ImgEmployee = QtWidgets.QLabel(EmpInfo)
        Ui_AE.ImgEmployee.setGeometry(QtCore.QRect(10, 10, 131, 121))
        Ui_AE.ImgEmployee.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(0, 0, 0,0.8);")
        Ui_AE.ImgEmployee.setText("")
        Ui_AE.ImgEmployee.setObjectName("Ui_AE.ImgEmployee")
        Ui_AE.LBName = QtWidgets.QLabel(EmpInfo)
        Ui_AE.LBName.setGeometry(QtCore.QRect(150, 10, 90, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        Ui_AE.LBName.setFont(font)
        Ui_AE.LBName.setObjectName("Ui_AE.LBName")
        Ui_AE.LBBday = QtWidgets.QLabel(EmpInfo)
        Ui_AE.LBBday.setGeometry(QtCore.QRect(150, 30, 90, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        Ui_AE.LBBday.setFont(font)
        Ui_AE.LBBday.setObjectName("Ui_AE.LBBday")
        Ui_AE.LBAge = QtWidgets.QLabel(EmpInfo)
        Ui_AE.LBAge.setGeometry(QtCore.QRect(150, 50, 90, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        Ui_AE.LBAge.setFont(font)
        Ui_AE.LBAge.setObjectName("Ui_AE.LBAge")
        Ui_AE.LBSex = QtWidgets.QLabel(EmpInfo)
        Ui_AE.LBSex.setGeometry(QtCore.QRect(150, 70, 90, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        Ui_AE.LBSex.setFont(font)
        Ui_AE.LBSex.setObjectName("Ui_AE.LBSex")
        Ui_AE.LBContact = QtWidgets.QLabel(EmpInfo)
        Ui_AE.LBContact.setGeometry(QtCore.QRect(150, 110, 90, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        Ui_AE.LBContact.setFont(font)
        Ui_AE.LBContact.setObjectName("Ui_AE.LBContact")
        Ui_AE.LBJob = QtWidgets.QLabel(EmpInfo)
        Ui_AE.LBJob.setGeometry(QtCore.QRect(150, 90, 90, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        Ui_AE.LBJob.setFont(font)
        Ui_AE.LBJob.setStyleSheet("")
        Ui_AE.LBJob.setObjectName("Ui_AE.LBJob")

        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)

        partition = QtWidgets.QLabel(EmpInfo)
        partition.setGeometry(QtCore.QRect(430, 5, 2, 131))
        partition.setStyleSheet("background-color: rgb(255, 255, 255);")
        partition.setText("")
        partition.setObjectName("partition")
        BgEmployee = QtWidgets.QLabel(EmpInfo)
        BgEmployee.setGeometry(QtCore.QRect(0, 0, 741, 141))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        BgEmployee.setFont(font)
        BgEmployee.setStyleSheet("background-color: rgb(148, 0, 2,.4);\n"
"border-radius:8px;\n"
"")
        BgEmployee.setText("")
        BgEmployee.setObjectName("BgEmployee")
        Ui_AE.LEName = QtWidgets.QLineEdit(EmpInfo)
        Ui_AE.LEName.setGeometry(QtCore.QRect(250, 12, 175, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        Ui_AE.LEName.setFont(font)
        Ui_AE.LEName.setStyleSheet("")
        Ui_AE.LEName.setText("")
        Ui_AE.LEName.setObjectName("Ui_AE.LEName")
        Ui_AE.LEBday = QtWidgets.QLineEdit(EmpInfo)
        Ui_AE.LEBday.setGeometry(QtCore.QRect(250, 32, 175, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        Ui_AE.LEBday.setFont(font)
        Ui_AE.LEBday.setStyleSheet("")
        Ui_AE.LEBday.setText("")
        Ui_AE.LEBday.setObjectName("Ui_AE.LEBday")
        Ui_AE.LEAge = QtWidgets.QLineEdit(EmpInfo)
        Ui_AE.LEAge.setGeometry(QtCore.QRect(250, 52, 175, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        Ui_AE.LEAge.setFont(font)
        Ui_AE.LEAge.setStyleSheet("")
        Ui_AE.LEAge.setText("")
        Ui_AE.LEAge.setObjectName("Ui_AE.LEAge")
        Ui_AE.LESex = QtWidgets.QLineEdit(EmpInfo)
        Ui_AE.LESex.setGeometry(QtCore.QRect(250, 72, 175, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        Ui_AE.LESex.setFont(font)
        Ui_AE.LESex.setStyleSheet("")
        Ui_AE.LESex.setText("")
        Ui_AE.LESex.setObjectName("Ui_AE.LESex")
        Ui_AE.LEJob = QtWidgets.QLineEdit(EmpInfo)
        Ui_AE.LEJob.setGeometry(QtCore.QRect(250, 92, 175, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        Ui_AE.LEJob.setFont(font)
        Ui_AE.LEJob.setStyleSheet("")
        Ui_AE.LEJob.setText("")
        Ui_AE.LEJob.setObjectName("Ui_AE.LEJob")
        Ui_AE.LEContact = QtWidgets.QLineEdit(EmpInfo)
        Ui_AE.LEContact.setGeometry(QtCore.QRect(250, 112, 175, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        Ui_AE.LEContact.setFont(font)
        Ui_AE.LEContact.setStyleSheet("")
        Ui_AE.LEContact.setText("")
        Ui_AE.LEContact.setObjectName("Ui_AE.LEContact")
        LBWorkDate = QtWidgets.QLabel(EmpInfo)
        LBWorkDate.setGeometry(QtCore.QRect(540, 10, 111, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        LBWorkDate.setFont(font)
        LBWorkDate.setObjectName("LBWorkDate")
        Ui_AE.DateWorkStart = QtWidgets.QDateEdit(EmpInfo)
        Ui_AE.DateWorkStart.setGeometry(QtCore.QRect(470, 30, 110, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        Ui_AE.DateWorkStart.setFont(font)
        Ui_AE.DateWorkStart.setStyleSheet("border:1px solid white;")
        Ui_AE.DateWorkStart.setCalendarPopup(True)
        Ui_AE.DateWorkStart.setObjectName("Ui_AE.DateWorkStart")
        Ui_AE.DateWorkEnd = QtWidgets.QDateEdit(EmpInfo)
        Ui_AE.DateWorkEnd.setGeometry(QtCore.QRect(600, 30, 110, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        Ui_AE.DateWorkEnd.setFont(font)
        Ui_AE.DateWorkEnd.setStyleSheet("border:1px solid white;")
        Ui_AE.DateWorkEnd.setCalendarPopup(True)
        Ui_AE.DateWorkEnd.setObjectName("Ui_AE.DateWorkEnd")
        Dash = QtWidgets.QLabel(EmpInfo)
        Dash.setGeometry(QtCore.QRect(588, 30, 16, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        Dash.setFont(font)
        Dash.setObjectName("Dash")
        Ui_AE.LBRate = QtWidgets.QLabel(EmpInfo)
        Ui_AE.LBRate.setGeometry(QtCore.QRect(540, 60, 101, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        Ui_AE.LBRate.setFont(font)
        Ui_AE.LBRate.setAlignment(QtCore.Qt.AlignCenter)
        Ui_AE.LBRate.setObjectName("Ui_AE.LBRate")
        Ui_AE.LERate = QtWidgets.QLineEdit(EmpInfo)
        Ui_AE.LERate.setGeometry(QtCore.QRect(530, 80, 113, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        Ui_AE.LERate.setFont(font)
        Ui_AE.LERate.setStyleSheet("border:1px solid white;")
        Ui_AE.LERate.setText("")
        Ui_AE.LERate.setAlignment(QtCore.Qt.AlignCenter)
        Ui_AE.LERate.setObjectName("Ui_AE.LERate")
        colon1 = QtWidgets.QLabel(EmpInfo)
        colon1.setGeometry(QtCore.QRect(242, 10, 16, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        colon1.setFont(font)
        colon1.setObjectName("colon1")
        colon2 = QtWidgets.QLabel(EmpInfo)
        colon2.setGeometry(QtCore.QRect(242, 30, 16, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        colon2.setFont(font)
        colon2.setObjectName("colon2")
        colon3 = QtWidgets.QLabel(EmpInfo)
        colon3.setGeometry(QtCore.QRect(242, 50, 16, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        colon3.setFont(font)
        colon3.setObjectName("colon3")
        colon4 = QtWidgets.QLabel(EmpInfo)
        colon4.setGeometry(QtCore.QRect(242, 70, 16, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        colon4.setFont(font)
        colon4.setObjectName("colon4")
        colon5 = QtWidgets.QLabel(EmpInfo)
        colon5.setGeometry(QtCore.QRect(242, 90, 16, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        colon5.setFont(font)
        colon5.setObjectName("colon5")
        colon6 = QtWidgets.QLabel(EmpInfo)
        colon6.setGeometry(QtCore.QRect(242, 110, 16, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        colon6.setFont(font)
        colon6.setObjectName("colon6")
        LEPHP = QtWidgets.QLabel(EmpInfo)
        LEPHP.setGeometry(QtCore.QRect(495, 80, 31, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        LEPHP.setFont(font)
        LEPHP.setStyleSheet("")
        LEPHP.setObjectName("LEPHP")
        BgEmployee.raise_()
        Ui_AE.ImgEmployee.raise_()
        Ui_AE.LBName.raise_()
        Ui_AE.LBBday.raise_()
        Ui_AE.LBAge.raise_()
        Ui_AE.LBSex.raise_()
        Ui_AE.LBContact.raise_()
        Ui_AE.LBJob.raise_()

        partition.raise_()
        Ui_AE.LEName.raise_()
        Ui_AE.LEBday.raise_()
        Ui_AE.LEAge.raise_()
        Ui_AE.LESex.raise_()
        Ui_AE.LEJob.raise_()
        Ui_AE.LEContact.raise_()
        LBWorkDate.raise_()
        Ui_AE.DateWorkStart.raise_()
        Ui_AE.DateWorkEnd.raise_()
        Dash.raise_()
        Ui_AE.LBRate.raise_()
        Ui_AE.LERate.raise_()
        colon1.raise_()
        colon2.raise_()
        colon3.raise_()
        colon4.raise_()
        colon5.raise_()
        colon6.raise_()
        LEPHP.raise_()

        Balance = QtWidgets.QGroupBox(ProjectEmployee)
        Balance.setGeometry(QtCore.QRect(310, 160, 741, 241))
        Balance.setStyleSheet("border:none;")
        Balance.setTitle("")
        Balance.setObjectName("Balance")
        BGBalance = QtWidgets.QLabel(Balance)
        BGBalance.setGeometry(QtCore.QRect(0, 0, 751, 241))
        BGBalance.setStyleSheet("background-color: rgb(148, 0, 2,.4);\n"
"border-radius:8px;\n"
"")
        BGBalance.setText("")
        BGBalance.setObjectName("BGBalance")

        Allowance = QtWidgets.QGroupBox(Balance)
        Allowance.setGeometry(QtCore.QRect(10, 10, 341, 191))
        Allowance.setTitle("")
        Allowance.setObjectName("Allowance")
        Allowance.setStyleSheet("color:white;")
        BGAllowance = QtWidgets.QLabel(Allowance)
        BGAllowance.setGeometry(QtCore.QRect(0, 0, 341, 191))
        BGAllowance.setStyleSheet("background-color: rgb(60, 0, 0,.8);")
        BGAllowance.setText("")
        BGAllowance.setObjectName("BGAllowance")
        Ui_AE.TBLAllowance = QtWidgets.QTableWidget(Allowance)
        Ui_AE.TBLAllowance.setGeometry(QtCore.QRect(0, 0, 341, 191))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        Ui_AE.TBLAllowance.setFont(font)
        Ui_AE.TBLAllowance.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        Ui_AE.TBLAllowance.setLayoutDirection(QtCore.Qt.LeftToRight)

        Ui_AE.TBLAllowance.horizontalHeader().setStyleSheet('''::section{background-color:transparent;}''')
        Ui_AE.TBLAllowance.setStyleSheet("QTableWidget::item{border:1px solid white;}")

        Ui_AE.TBLAllowance.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        Ui_AE.TBLAllowance.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        Ui_AE.TBLAllowance.setProperty("showDropIndicator", True)
        Ui_AE.TBLAllowance.setTextElideMode(QtCore.Qt.ElideRight)
        Ui_AE.TBLAllowance.setShowGrid(True)
        Ui_AE.TBLAllowance.setGridStyle(QtCore.Qt.SolidLine)
        Ui_AE.TBLAllowance.setColumnCount(2)
        Ui_AE.TBLAllowance.setObjectName("Ui_AE.TBLAllowance")
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        Ui_AE.TBLAllowance.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(0, 0, 0))
        Ui_AE.TBLAllowance.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        Ui_AE.TBLAllowance.setHorizontalHeaderItem(1, item)
        
        
        Ui_AE.TBLAllowance.horizontalHeader().setVisible(True)
        Ui_AE.TBLAllowance.horizontalHeader().setCascadingSectionResizes(True)
        Ui_AE.TBLAllowance.horizontalHeader().setDefaultSectionSize(150)
        Ui_AE.TBLAllowance.horizontalHeader().setHighlightSections(True)
        Ui_AE.TBLAllowance.horizontalHeader().setSortIndicatorShown(False)
        Ui_AE.TBLAllowance.horizontalHeader().setStretchLastSection(True)
        Ui_AE.TBLAllowance.verticalHeader().setVisible(False)
        Ui_AE.TBLAllowance.verticalHeader().setCascadingSectionResizes(False)
        Ui_AE.TBLAllowance.verticalHeader().setHighlightSections(True)
        Ui_AE.TBLAllowance.verticalHeader().setSortIndicatorShown(False)
        Ui_AE.TBLAllowance.verticalHeader().setStretchLastSection(False)
        Cash = QtWidgets.QGroupBox(Balance)
        Cash.setGeometry(QtCore.QRect(400, 10, 331, 191))
        Cash.setTitle("")
        Cash.setStyleSheet("color:white;")
        Cash.setObjectName("Cash")
        BGCash = QtWidgets.QLabel(Cash)
        BGCash.setGeometry(QtCore.QRect(0, 0, 331, 191))
        BGCash.setStyleSheet("background-color: rgb(60, 0, 0,.8);")
        BGCash.setText("")
        BGCash.setObjectName("BGCash")
        Ui_AE.TBLCash = QtWidgets.QTableWidget(Cash)
        Ui_AE.TBLCash.setGeometry(QtCore.QRect(0, 0, 331, 191))

        Ui_AE.TBLCash.horizontalHeader().setStyleSheet('''::section{background-color:transparent;}''')
        Ui_AE.TBLCash.setStyleSheet("QTableWidget::item{border:1px solid white;}")

        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        Ui_AE.TBLCash.setFont(font)
        Ui_AE.TBLCash.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        Ui_AE.TBLCash.setLayoutDirection(QtCore.Qt.LeftToRight)
        Ui_AE.TBLCash.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        Ui_AE.TBLCash.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        Ui_AE.TBLCash.setProperty("showDropIndicator", True)
        Ui_AE.TBLCash.setAlternatingRowColors(False)
        Ui_AE.TBLCash.setTextElideMode(QtCore.Qt.ElideRight)
        Ui_AE.TBLCash.setShowGrid(True)
        Ui_AE.TBLCash.setGridStyle(QtCore.Qt.SolidLine)
        Ui_AE.TBLCash.setColumnCount(2)
        Ui_AE.TBLCash.setObjectName("Ui_AE.TBLCash")
        item = QtWidgets.QTableWidgetItem()
        Ui_AE.TBLCash.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        Ui_AE.TBLCash.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        Ui_AE.TBLCash.setHorizontalHeaderItem(1, item)


        Ui_AE.TBLCash.horizontalHeader().setVisible(True)
        Ui_AE.TBLCash.horizontalHeader().setCascadingSectionResizes(True)
        Ui_AE.TBLCash.horizontalHeader().setDefaultSectionSize(150)
        Ui_AE.TBLCash.horizontalHeader().setHighlightSections(True)
        Ui_AE.TBLCash.horizontalHeader().setSortIndicatorShown(False)
        Ui_AE.TBLCash.horizontalHeader().setStretchLastSection(True)
        Ui_AE.TBLCash.verticalHeader().setVisible(False)
        Ui_AE.TBLCash.verticalHeader().setCascadingSectionResizes(False)
        Ui_AE.TBLCash.verticalHeader().setHighlightSections(True)
        Ui_AE.TBLCash.verticalHeader().setSortIndicatorShown(False)
        Ui_AE.TBLCash.verticalHeader().setStretchLastSection(False)
        PEmployeeList = QtWidgets.QScrollArea(ProjectEmployee)
        PEmployeeList.setEnabled(True)
        PEmployeeList.setGeometry(QtCore.QRect(10, 60, 281, 281))
        PEmployeeList.setStyleSheet("background-color: rgb(104, 0, 0,.1);\n"
"border-radius:8px;")
        PEmployeeList.setWidgetResizable(True)
        PEmployeeList.setObjectName("PEmployeeList")
        EmployeeListScroll_2 = QtWidgets.QWidget()
        EmployeeListScroll_2.setEnabled(True)
        EmployeeListScroll_2.setGeometry(QtCore.QRect(0, 0, 281, 281))
        EmployeeListScroll_2.setObjectName("EmployeeListScroll_2")
        Ui_AE.PEList = QtWidgets.QListWidget(EmployeeListScroll_2)
        Ui_AE.PEList.setGeometry(QtCore.QRect(0, 0, 281, 281))
        Ui_AE.PEList.setLayoutDirection(QtCore.Qt.RightToLeft)
        Ui_AE.PEList.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        Ui_AE.PEList.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        Ui_AE.PEList.setStyleSheet("background-color: rgb(167, 167, 167,.4);\n"
                                    "border-radius:5px;\n"
                                    "font-size:16px;\n"
                                    "color:white;\n"
                                    "")
        Ui_AE.PEList.setObjectName("Ui_AE.PEList")
        PEmployeeList.setWidget(EmployeeListScroll_2)
        Ui_AE.StackProject.addWidget(ProjectEmployee)

        Ui_AE.BtnBack = QtWidgets.QPushButton(DashbaordWindow)
        Ui_AE.BtnBack.setGeometry(QtCore.QRect(1119, 82, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        Ui_AE.BtnBack.setFont(font)
        Ui_AE.BtnBack.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        Ui_AE.BtnBack.setStyleSheet("background-color: rgb(0, 0, 0.9);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Icons/Assets/BackIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Ui_AE.BtnBack.setIcon(icon3)
        Ui_AE.BtnBack.setObjectName("BtnBack")

        _translate = QtCore.QCoreApplication.translate
        Ui_AE.LBProjectTitle.setText(_translate("DashbaordWindow", "Project Title"))
        BtnEmployee.setText(_translate("DashbaordWindow", "Employees"))
        BtnDtr.setText(_translate("DashbaordWindow", "DTR"))
        BtnPayroll.setText(_translate("DashbaordWindow", "Payroll"))
        BtnTransaction.setText(_translate("DashbaordWindow", "Transaction"))
        BtnSummary.setText(_translate("DashbaordWindow", "Summary"))
        LBProjectEmp.setText(_translate("DashbaordWindow", "Project Employees"))
        Ui_AE.LBName.setText(_translate("DashbaordWindow", "Name          "))
        Ui_AE.LBBday.setText(_translate("DashbaordWindow", "Birthday    "))
        Ui_AE.LBAge.setText(_translate("DashbaordWindow", "Age"))
        Ui_AE.LBSex.setText(_translate("DashbaordWindow", "Sex"))
        Ui_AE.LBContact.setText(_translate("DashbaordWindow", "Contact No."))
        Ui_AE.LBJob.setText(_translate("DashbaordWindow", "Job Position"))

        Ui_AE.LEName.setPlaceholderText(_translate("DashbaordWindow", "Name"))
        Ui_AE.LEBday.setPlaceholderText(_translate("DashbaordWindow", "Birthday"))
        Ui_AE.LEAge.setPlaceholderText(_translate("DashbaordWindow", "Age"))
        Ui_AE.LESex.setPlaceholderText(_translate("DashbaordWindow", "Sex"))
        Ui_AE.LEJob.setPlaceholderText(_translate("DashbaordWindow", "Job Position"))
        Ui_AE.LEContact.setPlaceholderText(_translate("DashbaordWindow", "Contact No."))
        LBWorkDate.setText(_translate("DashbaordWindow", "Work Due Date"))
        Dash.setText(_translate("DashbaordWindow", "-"))
        Ui_AE.LBRate.setText(_translate("DashbaordWindow", "Rate Per Hour"))
        Ui_AE.LERate.setPlaceholderText(_translate("DashbaordWindow", "Rate/Hour"))
        colon1.setText(_translate("DashbaordWindow", ":"))
        colon2.setText(_translate("DashbaordWindow", ":"))
        colon3.setText(_translate("DashbaordWindow", ":"))
        colon4.setText(_translate("DashbaordWindow", ":"))
        colon5.setText(_translate("DashbaordWindow", ":"))
        colon6.setText(_translate("DashbaordWindow", ":"))
        LEPHP.setText(_translate("DashbaordWindow", "PHP"))

        item = Ui_AE.TBLAllowance.horizontalHeaderItem(0)
        item.setText(_translate("DashbaordWindow", "Allowance"))
        item = Ui_AE.TBLAllowance.horizontalHeaderItem(1)
        item.setText(_translate("DashbaordWindow", "Date"))
        __sortingEnabled = Ui_AE.TBLAllowance.isSortingEnabled()
        Ui_AE.TBLAllowance.setSortingEnabled(False)
        Ui_AE.TBLAllowance.setSortingEnabled(__sortingEnabled)
        Ui_AE.TBLCash.setSortingEnabled(False)
        item = Ui_AE.TBLCash.horizontalHeaderItem(0)
        item.setText(_translate("DashbaordWindow", "Cash Advance"))
        item = Ui_AE.TBLCash.horizontalHeaderItem(1)
        item.setText(_translate("DashbaordWindow", "Date"))
        __sortingEnabled = Ui_AE.TBLCash.isSortingEnabled()
        Ui_AE.TBLCash.setSortingEnabled(False)


        Ui_AE.TBLCash.setSortingEnabled(__sortingEnabled)
        Ui_AE.BtnBack.setText(_translate("DashbaordWindow", "  Back"))

        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)















        #ProjectDTR
        ProjectDTR= QtWidgets.QWidget()
        ProjectDTR.setObjectName("ProjectDTR")
        Ui_DTRA.PDTR(ProjectDTR,Ui_AE.BtnBack,Ui_AE.ProjectTab)
        Ui_AE.StackProject.addWidget(ProjectDTR)

        

        #ProjectPayroll
        ProjectPayroll= QtWidgets.QWidget()
        ProjectPayroll.setObjectName("ProjectPayroll")
        Ui_Payroll.Payroll(ProjectPayroll,Ui_AE.BtnBack,Ui_AE.ProjectTab)
        Ui_AE.StackProject.addWidget(ProjectPayroll)

        #ProjectTransaction
        ProjectTransaction= QtWidgets.QWidget()
        ProjectTransaction.setObjectName("ProjectTransaction")
        Ui_Trans.Transaction(ProjectTransaction,DashbaordWindow,Ui_AE.BtnBack,Ui_AE.ProjectTab)
        Ui_AE.StackProject.addWidget(ProjectTransaction)

        #ProjectSummary
        ProjectSummary= QtWidgets.QWidget()
        ProjectSummary.setObjectName("ProjectSummary")
        Ui_Summary.Summary(ProjectSummary)
        Ui_AE.StackProject.addWidget(ProjectSummary)


        #buttons
        BtnEmployee.clicked.connect(lambda: Ui_AE.showpage(ProjectEmployee))
        BtnDtr.clicked.connect(lambda: Ui_AE.showdtr(ProjectDTR))
        BtnPayroll.clicked.connect(lambda: Ui_AE.showpayroll(ProjectPayroll))
        BtnTransaction.clicked.connect(lambda: Ui_AE.showtrans(ProjectTransaction))
        BtnSummary.clicked.connect(lambda: Ui_AE.showsummary(ProjectSummary))




        #adds
        Ui_AE.BtnBack.hide()
        Ui_AE.LEName.setEnabled(False)
        Ui_AE.LEBday.setEnabled(False)
        Ui_AE.LEAge.setEnabled(False)
        Ui_AE.LESex.setEnabled(False)
        Ui_AE.LEJob.setEnabled(False)
        Ui_AE.LEContact.setEnabled(False)

        #load Balance form
        Ui_BalanceForm.BalanceForm(DashbaordWindow)

        # selection function

        Ui_AE.PEList.itemClicked.connect(Ui_AE.get_info)

        #table selection 

        Ui_AE.TBLAllowance.selectionModel().selectionChanged.connect(Ui_AE.tableAllowSelect)
        Ui_AE.TBLCash.selectionModel().selectionChanged.connect(Ui_AE.tableCashSelect)



        Ui_AE.LERate.setEnabled(False)
        Ui_AE.DateWorkStart.setEnabled(False)
        Ui_AE.DateWorkEnd.setEnabled(False)


        my_regex = QtCore.QRegExp("^\\d{1,6}(\\.\\d{1,2})?$")
        my_validator = QtGui.QRegExpValidator(my_regex, Ui_AE.LERate)
        Ui_AE.LERate.setValidator(my_validator)


        

    def removeRowAllow():
        try:
            if Ui_AE.Allowid > 0:
                if (Dialog.confirm_dialog("Are you sure you want to remove this record?") == QMessageBox.Ok):
                    cursor = con.cursor()
                    query2 = (f"DELETE FROM `projecte_balance` WHERE `id` = {Ui_AE.Allowid}")
                    cursor.execute(query2)
                    con.commit()
                    Ui_AE.Allowid=0
                    Dialog.msg_dialog("Allowance Record has been removed from the employee")

                    Ui_AE.SaveAllow2()

                    Ui_AE.getAllowance(Ui_AE.TBLAllowance,Ui_AE.not_editable,False)
            else:
                Dialog.msg_dialog("Please select a row first")

        except:
            Dialog.msg_dialog(str(sys.exc_info()))

    def removeRowCash():
        try:
            if Ui_AE.Cashid > 0:
                if (Dialog.confirm_dialog("Are you sure you want to remove this record?") == QMessageBox.Ok):
                    cursor = con.cursor()
                    query2 = (f"DELETE FROM `projecte_balance` WHERE `id` = {Ui_AE.Cashid}")
                    cursor.execute(query2)
                    con.commit()
                    Ui_AE.Cashid=0
                    Dialog.msg_dialog("Cash Advance Record has been removed from the employee")

                    Ui_AE.getCashAdvance(Ui_AE.TBLCash,Ui_AE.not_editable,False)
                    Ui_AE.SaveCash2()
            else:
                Dialog.msg_dialog("Please select a row first")

        except:
            Dialog.msg_dialog(str(sys.exc_info()))



    def tableAllowSelect(selected, deselected):
        for x in selected.indexes():
            x=x.row()
            Ui_AE.Allowid=Ui_AE.TBAid[x]


    def tableCashSelect(selected, deselected):
        for x in selected.indexes():
            x=x.row()
            Ui_AE.Cashid=Ui_AE.TBCid[x]



class Ui_BalanceForm(object):
    DisplayGroup2=""
    BtnSubmit=""
    BtnCancel=""

    LBTitle=""
    LBBalance=""


    LEBalance=""
    dateEdit=""

    title=""


    def showBalanceForm(title):
        Ui_BalanceForm.DisplayGroup2.show()
        Ui_BalanceForm.title = title
        Ui_BalanceForm.LBTitle.setText( f"{Ui_BalanceForm.title}\nForm")
        Ui_BalanceForm.LBBalance.setText(str(Ui_BalanceForm.title))


    def cancelBalanceForm():
        if (Dialog.confirm_dialog("Are you sure you want to cancel?") == QMessageBox.Ok):
            Ui_BalanceForm.DisplayGroup2.hide()
            now = QDate.currentDate()
            Ui_BalanceForm.dateEdit.setDate(now)
            Ui_BalanceForm.LEBalance.setText("")

    def addBalance():
        Ui_BalanceForm.DisplayGroup2.hide()
        if (len(Ui_BalanceForm.LEBalance.text()))>0:
            try:
                date = (f"{Ui_BalanceForm.dateEdit.date().year()},{Ui_BalanceForm.dateEdit.date().month()},{Ui_BalanceForm.dateEdit.date().day()}")
                cursor = con.cursor()
                query1="INSERT INTO projecte_balance(project_id,employee_id,title,`date`,balance) VALUES (%s,%s,%s,%s,%s)"
                query2=""
                if Ui_BalanceForm.title=="Less Cash Advance":
                    query2=(Ui_AE.projectid,Ui_AE.itemid,Ui_BalanceForm.title,date,"-"+Ui_BalanceForm.LEBalance.text())
                else:
                    query2=(Ui_AE.projectid,Ui_AE.itemid,Ui_BalanceForm.title,date,Ui_BalanceForm.LEBalance.text())

                cursor.execute(query1,query2)
                con.commit()

                Ui_AE.getAllowance(Ui_AE.TBLAllowance,Ui_AE.not_editable,False)
                Ui_AE.getCashAdvance(Ui_AE.TBLCash,Ui_AE.not_editable,False)
                Ui_BalanceForm.updatePayrollBalance()

                msgBox = QMessageBox()
                msgBox.setIcon(QMessageBox.Information)
                msgBox.setText(f"{Ui_BalanceForm.title} was added successfully")
                msgBox.setWindowTitle("Message Alert")
                msgBox.setStandardButtons(QMessageBox.Ok)
                msgBox.buttonClicked.connect(msgBox.close)

                returnValue = msgBox.exec()
                if returnValue == QMessageBox.Ok:
                    Ui_BalanceForm.DisplayGroup2.hide()
                    now = QDate.currentDate()
                    Ui_BalanceForm.dateEdit.setDate(now)
                    Ui_BalanceForm.LEBalance.setText("")
            except :
                Dialog.msg_dialog(str(sys.exc_info()))
        else:
            Dialog.msg_dialog("Please complete the form first")

    def updatePayrollBalance():
        cursor = con.cursor()
        try:
            
            cursor.execute(f"SELECT * FROM `projecte_balance` WHERE `project_id`={Ui_AE.projectid} AND `employee_id`={Ui_AE.itemid} AND `title`='Add Allowance'")
            res1 = cursor.fetchall()

            cursor.execute(f"SELECT * FROM `projecte_balance` WHERE `project_id`={Ui_AE.projectid} AND `employee_id`={Ui_AE.itemid} AND `title`='Add Cash Advance'")
            res2 = cursor.fetchall()

            cursor.execute(f"SELECT * FROM `projecte_balance` WHERE `project_id`={Ui_AE.projectid} AND `employee_id`={Ui_AE.itemid} AND `title`='Less Cash Advance'")
            res3 = cursor.fetchall()

            cursor.execute(f"SELECT * FROM `project_payroll` WHERE `project_id`={Ui_AE.projectid} AND `employee_id`={Ui_AE.itemid}")
            res4 = cursor.fetchall()

            startDate=[]
            endDate=[]

            
            for x in res4:
                startDate.append(x[3])
                endDate.append(x[4])

            # Update Allowance
            for x in range(0,len(startDate)):
                dateZ= ""
                dateX=""
                dateY=""
                allowance=0

                dateX=QDate(Ui_AE.process_date(startDate[x]))
                dateY=QDate(Ui_AE.process_date(endDate[x])) 

                for y in res1:
                    dateZ= QDate(Ui_AE.process_date(y[4]))
                    if (dateZ>=dateX) & (dateZ<=dateY):
                        allowance=allowance+float(y[5])

                #update payroll week here
                d1=dateX.toString("yyyy,MM,dd")
                d2=dateY.toString("yyyy,MM,dd")

                query2 = f"UPDATE `project_payroll` SET `Allowance`={allowance} WHERE `startDate`='{d1}' AND `endDate`='{d2}' AND `employee_id`={Ui_AE.itemid} AND `project_id`={Ui_AE.projectid}"
                cursor.execute(query2)
                con.commit()

            # Update Cash Advance and less CA and balance
            for x in range(0,len(startDate)):
                dateZ=""
                dateX=""
                dateY=""
                CashAdv=0
                LessCashAdv=0

                dateX=QDate(Ui_AE.process_date(startDate[x]))
                dateY=QDate(Ui_AE.process_date(endDate[x])) 

                for y in res2:#cash advance
                    dateZ= QDate(Ui_AE.process_date(y[4]))
                    if (dateZ>=dateX) & (dateZ<=dateY):
                        CashAdv=CashAdv+float(y[5])

                for y in res3:#less cash advance
                    dateZ= QDate(Ui_AE.process_date(y[4]))
                    if (dateZ>=dateX) & (dateZ<=dateY):
                        LessCashAdv=LessCashAdv+float(y[5])


                #update payroll week here
                d1=dateX.toString("yyyy,MM,dd")
                d2=dateY.toString("yyyy,MM,dd")

                balance = CashAdv+LessCashAdv

                query2 = f"UPDATE `project_payroll` SET `CashAdv`={CashAdv},`LessCA`={LessCashAdv},`Balance`={balance} WHERE `startDate`='{d1}' AND `endDate`='{d2}' AND `employee_id`={Ui_AE.itemid}  AND `project_id`={Ui_AE.projectid}"
                cursor.execute(query2)
                con.commit()


        except:
            Dialog.msg_dialog(str(sys.exc_info()))


    def BalanceForm(DashbaordWindow):

        Ui_BalanceForm.DisplayGroup2 = QtWidgets.QGroupBox(DashbaordWindow)
        Ui_BalanceForm.DisplayGroup2.setGeometry(QtCore.QRect(0, 0, 1230, 703))
        Ui_BalanceForm.DisplayGroup2.setStyleSheet("\n""")
        Ui_BalanceForm.DisplayGroup2.setTitle("")
        Ui_BalanceForm.DisplayGroup2.setObjectName("DisplayGroup")
        Ui_BalanceForm.DisplayGroup2.hide()
        # Adds

        Bg = QtWidgets.QLabel(Ui_BalanceForm.DisplayGroup2)
        Bg.setEnabled(True)
        Bg.setGeometry(QtCore.QRect(0, 0, 1230, 703))
        Bg.setMinimumSize(QtCore.QSize(1230, 703))
        Bg.setMaximumSize(QtCore.QSize(1230, 703))
        Bg.setStyleSheet("background-color: rgb(0, 0, 0,.9);")

        Designation = QtWidgets.QGroupBox(Ui_BalanceForm.DisplayGroup2)
        Designation.setGeometry(QtCore.QRect(500, 180, 561, 621))
        Designation.setStyleSheet(".QLabel{color:white;}\n"
                                             ".QPushButton{color:white;}\n"
                                             ".QGroupBox{border:none;}\n")
        Designation.setTitle("")
        Designation.setObjectName("Designation")



        
        BGForm1 = QtWidgets.QLabel(Designation)
        BGForm1.setGeometry(QtCore.QRect(0, 0, 331, 261))
        BGForm1.setStyleSheet("background-color: rgb(148, 0, 2,.4);\n"
"border-radius:5px;")
        BGForm1.setText("")
        BGForm1.setObjectName("BGForm1")
        BGForm2 = QtWidgets.QLabel(Designation)
        BGForm2.setGeometry(QtCore.QRect(5, 5, 321, 251))
        BGForm2.setStyleSheet("background-color: rgb(148, 0, 2,.6);\n"
"border-radius:5px;")
        BGForm2.setText("")
        BGForm2.setObjectName("BGForm2")
        Ui_BalanceForm.LBTitle = QtWidgets.QLabel(Designation)
        Ui_BalanceForm.LBTitle.setGeometry(QtCore.QRect(15, 10, 301, 81))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        Ui_BalanceForm.LBTitle.setFont(font)
        Ui_BalanceForm.LBTitle.setStyleSheet("color:white;")
        Ui_BalanceForm.LBTitle.setObjectName("LBTitle")
        Ui_BalanceForm.LBTitle.setAlignment(QtCore.Qt.AlignCenter)
        Ui_BalanceForm.BtnCancel = QtWidgets.QPushButton(Designation)
        Ui_BalanceForm.BtnCancel.setGeometry(QtCore.QRect(170, 200, 130, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        Ui_BalanceForm.BtnCancel.setFont(font)
        Ui_BalanceForm.BtnCancel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        Ui_BalanceForm.BtnCancel.setStyleSheet("background-color: rgb(0, 0, 0,.9);\n"
"color:white;\n"
"border-radius:5px;")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/Assets/FormCancelIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Ui_BalanceForm.BtnCancel.setIcon(icon)
        Ui_BalanceForm.BtnCancel.setIconSize(QtCore.QSize(30, 30))
        Ui_BalanceForm.BtnCancel.setObjectName("BtnCancel")
        Ui_BalanceForm.BtnSubmit = QtWidgets.QPushButton(Designation)
        Ui_BalanceForm.BtnSubmit.setGeometry(QtCore.QRect(30, 200, 130, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        Ui_BalanceForm.BtnSubmit.setFont(font)
        Ui_BalanceForm.BtnSubmit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        Ui_BalanceForm.BtnSubmit.setStyleSheet("background-color: rgb(0, 0, 0,.9);\n"
"color:white;\n"
"border-radius:5px;")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icons/Assets/FormSubmitIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Ui_BalanceForm.BtnSubmit.setIcon(icon1)
        Ui_BalanceForm.BtnSubmit.setIconSize(QtCore.QSize(30, 30))
        Ui_BalanceForm.BtnSubmit.setObjectName("BtnSubmit")
        Ui_BalanceForm.LEBalance = QtWidgets.QLineEdit(Designation)
        Ui_BalanceForm.LEBalance.setGeometry(QtCore.QRect(170, 130, 130, 30))
        Ui_BalanceForm.LEBalance.setStyleSheet("background-color: rgba(255, 255, 255);\n"
"border-radius:5px;")
        Ui_BalanceForm.LEBalance.setObjectName("LEBalance")
        Ui_BalanceForm.dateEdit = QtWidgets.QDateEdit(Designation)
        Ui_BalanceForm.dateEdit.setGeometry(QtCore.QRect(30, 130, 130, 31))
        Ui_BalanceForm.dateEdit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        Ui_BalanceForm.dateEdit.setStyleSheet("color:maroon;\n"
"background-color:rgb(255, 255, 255);\n"
"border-radius:5px;")
        Ui_BalanceForm.dateEdit.setCalendarPopup(True)
        Ui_BalanceForm.dateEdit.setObjectName("dateEdit")
        LBDate = QtWidgets.QLabel(Designation)
        LBDate.setGeometry(QtCore.QRect(30, 110, 47, 13))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        LBDate.setFont(font)
        LBDate.setStyleSheet("color:white;")
        LBDate.setObjectName("LBDate")
        Ui_BalanceForm.LBBalance = QtWidgets.QLabel(Designation)
        Ui_BalanceForm.LBBalance.setGeometry(QtCore.QRect(170, 110, 130, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        Ui_BalanceForm.LBBalance.setFont(font)
        Ui_BalanceForm.LBBalance.setStyleSheet("color:white;")
        Ui_BalanceForm.LBBalance.setObjectName("LBBalance")

        _translate = QtCore.QCoreApplication.translate
        Ui_BalanceForm.LBTitle.setText(_translate("DashbaordWindow", f"Add {Ui_BalanceForm.title}\nForm"))
        Ui_BalanceForm.BtnCancel.setText(_translate("DashbaordWindow", "  Cancel"))
        Ui_BalanceForm.BtnSubmit.setText(_translate("DashbaordWindow", "  Add"))
        LBDate.setText(_translate("DashbaordWindow", "Date"))
        Ui_BalanceForm.LBBalance.setText(_translate("DashbaordWindow", Ui_BalanceForm.title))


        Ui_BalanceForm.BtnCancel.clicked.connect(lambda: Ui_BalanceForm.cancelBalanceForm())
        Ui_BalanceForm.BtnSubmit.clicked.connect(lambda: Ui_BalanceForm.addBalance())

        now = QDate.currentDate()
        Ui_BalanceForm.dateEdit.setDate(now)

        my_regex = QtCore.QRegExp("^\\d{1,6}(\\.\\d{1,2})?$")
        my_validator = QtGui.QRegExpValidator(my_regex, Ui_BalanceForm.LEBalance)
        Ui_BalanceForm.LEBalance.setValidator(my_validator)

