# -*- coding: utf-8 -*-

# Form implementation generated from reading Ui_EmployeePage file 'employee_page.Ui_EmployeePage'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

import mysql
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QVariant, Qt, QDate
from PyQt5.QtGui import QColor, QImage, QPixmap
from PyQt5.QtWidgets import QMessageBox, QDialog, QFileDialog
from nationalities import nationality
from db import con
from dialogs import Dialog
import win32com.client as win32
import os
from project_activity import Ui_Activity




class Ui_EmployeePage(object):
    itemid=0
    LELastName, LEFirstName,LESuffix, LEMI, LEAge, LEContact, LEAddress, LECurrentSite, DEBirthday=QtWidgets,QtWidgets,QtWidgets,QtWidgets,QtWidgets,QtWidgets,QtWidgets,QtWidgets,QtWidgets
    DEDateHired, CbStatus, CbWorkStatus, CbJobPosition, LBImageContainer, CbSex,CbNationality=QtWidgets,QtWidgets,QtWidgets,QtWidgets,QtWidgets,QtWidgets,QtWidgets
    LbID=QtWidgets
    Upload=""
    BrnAdd=QtWidgets
    BtnCancel = ""
    BtnEdit = ""
    BtnSave = ""
    employee_item=QtWidgets
    search_area=QtWidgets


    employee_id = []
    employee_fname = []
    employee_lname = []
    employee_mname = []
    employee_position = []


    def printID():
        xlApp = win32.Dispatch('Excel.Application')
        xlApp.Visible = True

        # create a new excel workbook
        wb = xlApp.Workbooks.Add()

        # create a new excel worksheet
        ws = wb.worksheets.add
        ws.name = 'Employee ID'
        ws.PageSetup.Orientation = 2

        ws.Range(ws.cells(2, 2),ws.cells(25, 11)).ColumnWidth = 3.5
        ws.Range(ws.cells(2, 13),ws.cells(25, 22)).ColumnWidth = 3.5

        ws.Range(ws.cells(2, 2),ws.cells(25, 11)).verticalalignment=-4108
        ws.Range(ws.cells(2, 2),ws.cells(25, 11)).horizontalalignment=-4108
        ws.Range(ws.cells(2, 13),ws.cells(25, 22)).verticalalignment=-4108
        ws.Range(ws.cells(2, 13),ws.cells(25, 22)).horizontalalignment=-4108


        dir_path = os.path.dirname(os.path.realpath(__file__))
        # Insert logo
        cell = ws.Cells(1,1)
        logo_pic = ws.Pictures().Insert(dir_path+r"\id format.png")
        logo_pic.Left = cell.Left+63
        logo_pic.Top = cell.Top+20


        pixmap = Ui_EmployeePage.LBImageContainer.pixmap()
        pixmap5 = pixmap.scaled(119, 120)
        pixmap5.save(dir_path+r"\temp\temp.png")

        # Insert image employee
        cell = ws.Cells(7,7)
    
        logo_pic = ws.Pictures().Insert(dir_path+r"\temp\temp.png")
        logo_pic.Left = cell.Left+1
        logo_pic.Top = cell.Top+2



        #merge id number
        ws.Range(ws.Cells(10,3),ws.Cells(10,5)).MergeCells = True
        ws.Range(ws.Cells(11,3),ws.Cells(11,5)).MergeCells = True

        #name merge
        ws.Range(ws.Cells(14,3),ws.Cells(15,10)).MergeCells = True
        ws.Range(ws.Cells(16,3),ws.Cells(16,10)).MergeCells = True

        #posistion merge
        ws.Range(ws.Cells(18,3),ws.Cells(19,10)).MergeCells = True
        ws.Range(ws.Cells(20,3),ws.Cells(20,10)).MergeCells = True

        #sinature
        ws.Range(ws.Cells(24,3),ws.Cells(24,10)).MergeCells = True

        ws.Range(ws.cells(2, 2),ws.cells(25, 11)).BorderAround(1,4)
        ws.Range(ws.cells(2, 13),ws.cells(25, 22)).BorderAround(1,4)
        ws.Range(ws.cells(4, 14),ws.cells(13, 21)).BorderAround(1,4)
        ws.Range(ws.cells(7, 7),ws.cells(12, 10)).BorderAround(1,4)
        ws.Range(ws.cells(10, 3),ws.cells(10, 5)).BorderAround(1,4)

        #underlines
        ws.Range(ws.cells(16, 3),ws.cells(16, 10)).Borders(3).Weight = 3
        ws.Range(ws.cells(20, 3),ws.cells(20, 10)).Borders(3).Weight = 3
        ws.Range(ws.cells(24, 3),ws.cells(24, 10)).Borders(3).Weight = 3

        ws.Range(ws.cells(22, 14),ws.cells(22, 21)).Borders(3).Weight = 3

        ws.Range(ws.cells(8, 16),ws.cells(8, 20)).Borders(3).Weight = 3
        ws.Range(ws.cells(10, 16),ws.cells(10, 20)).Borders(3).Weight = 3
        ws.Range(ws.cells(12, 16),ws.cells(12, 20)).Borders(3).Weight = 3

        ws.cells(11, 3).value = "Employee No."
        ws.cells(16, 3).value = "Name of Employee"
        ws.cells(20, 3).value = "Position"
        ws.cells(24, 3).value = "Signature"

        ws.Range(ws.Cells(7,14),ws.Cells(7,15)).MergeCells = True
        ws.Range(ws.Cells(9,14),ws.Cells(9,15)).MergeCells = True
        ws.Range(ws.Cells(11,14),ws.Cells(11,15)).MergeCells = True

        ws.cells(7, 14).value = "Name :"
        ws.cells(9, 14).value = "CP# :"
        ws.cells(11, 14).value = "Tell# :"

        ws.Range(ws.Cells(16,14),ws.Cells(18,21)).MergeCells = True
        ws.cells(16, 14).value = "This certifies that the personnel\nregistered in this ID is a bonified\nemployee of RMEEC"
        ws.Range(ws.Cells(4,14),ws.Cells(5,21)).MergeCells = True
        ws.cells(4, 14).value = "Contact Incase of  emergency"
        ws.Range(ws.Cells(22,14),ws.Cells(22,21)).MergeCells = True
        ws.cells(22, 14).value =  "President"

        suffix = ""
        if Ui_EmployeePage.LESuffix.text() == "N/A":
            suffix=""
        else:
            suffix = Ui_EmployeePage.LESuffix.text()

        fullname = f"{Ui_EmployeePage.LEFirstName.text()} {Ui_EmployeePage.LEMI.text()}. {Ui_EmployeePage.LELastName.text()} {suffix}"

        ws.cells(10, 3).Font.Bold = True
        ws.cells(14, 3).Font.Bold = True
        ws.cells(18, 3).Font.Bold = True
        ws.cells(4, 14).Font.Bold = True
        ws.cells(22, 14).Font.Bold = True

        ws.cells(14, 3).Font.Size = 16
        ws.cells(18, 3).Font.Size = 16
        ws.cells(22, 14).Font.Size = 16

        ws.cells(10, 3).value =  Ui_EmployeePage.eid
        ws.cells(14, 3).value = fullname
        ws.cells(18, 3).value = f"{Ui_EmployeePage.CbJobPosition.currentText()}"

        


    def keyPressEvent(label):
        text = label.text()
        if len(text)>0:
            label.setText(text.title())

    def cancel_dialog(employee_list):
        msgBox = QMessageBox()
        msgBox.setIcon(QMessageBox.Information)
        msgBox.setText("Are you sure you want to discard changes?")
        msgBox.setWindowTitle("Message Alert")
        msgBox.setStandardButtons(QMessageBox.Ok|QMessageBox.Cancel)
        msgBox.buttonClicked.connect(msgBox.close)

        returnValue = msgBox.exec()
        if returnValue == QMessageBox.Ok:
            Ui_EmployeePage.set_readonly(False, employee_list)



    def show_dialog(msg):
        msgBox = QMessageBox()
        msgBox.setIcon(QMessageBox.Information)
        msgBox.setText(msg)
        msgBox.setWindowTitle("Message Alert")
        msgBox.setStandardButtons(QMessageBox.Ok)
        msgBox.buttonClicked.connect(msgBox.close)

        returnValue = msgBox.exec()

    def openImage(centralwidget,label):

        imagePath, _ = QFileDialog.getOpenFileName(centralwidget, "openImage", '', "Image Files (*.jpg *.png)")
        if len(str(imagePath)) > 0:
            image = QImage(imagePath)

            pixmap = QPixmap.fromImage(image)
            pixmap5 = pixmap.scaled(label.width(), label.height())

            label.setPixmap(pixmap5)
            label.setStyleSheet("border-radius:8px;\n"
                    "font-size:16px;\n"
                    "padding-left:0px;\n"
                    "border:1px solid black;")
            label.setText("")

    def submitForm(employee_list,employee_item):
        if (Ui_EmployeePage.LELastName.text() == "") | (Ui_EmployeePage.LEFirstName.text() == "") | (Ui_EmployeePage.LEMI.text() == "") | (Ui_EmployeePage.LEAge.text() == "") | (Ui_EmployeePage.LEContact.text() == "") | (Ui_EmployeePage.LEAddress.text() == "") :
            Ui_EmployeePage.show_dialog("Please complete the form first")

        elif Ui_EmployeePage.LBImageContainer.text()=="Image":
            Ui_EmployeePage.show_dialog("Please select an Image")

        elif not len(Ui_EmployeePage.LEContact.text())==10:
            Ui_EmployeePage.show_dialog("Invalid Contact Number")

        else:

            pixmap = Ui_EmployeePage.LBImageContainer.pixmap()
            ba = QtCore.QByteArray()
            buff = QtCore.QBuffer(ba)
            buff.open(QtCore.QIODevice.WriteOnly)
            ok = pixmap.save(buff, "PNG")
            assert ok
            pixmap_bytes = ba.data()

            suffix = ""
            if Ui_EmployeePage.LESuffix.text() == "":
                suffix="N/A"
            else:
                suffix = Ui_EmployeePage.LESuffix.text()



            bday = (f"{Ui_EmployeePage.DEBirthday.date().year()},{Ui_EmployeePage.DEBirthday.date().month()},{Ui_EmployeePage.DEBirthday.date().day()}")
            dhired = (f"{Ui_EmployeePage.DEDateHired.date().year()},{Ui_EmployeePage.DEDateHired.date().month()},{Ui_EmployeePage.DEDateHired.date().day()}")
            try:

                cursor = con.cursor()


                query1 = (f"UPDATE `employees` SET `Last_name` = '{Ui_EmployeePage.LELastName.text()}', `First_name` = '{Ui_EmployeePage.LEFirstName.text()}', `MI` = '{Ui_EmployeePage.LEMI.text()}', `Birthday` = '{bday}', `Age` = {Ui_EmployeePage.LEAge.text()}, `Contact_Number` = '{Ui_EmployeePage.LEContact.text()}', `Status` = '{Ui_EmployeePage.CbStatus.currentText()}', `Address` = '{Ui_EmployeePage.LEAddress.text()}', `Work_Status` = '{Ui_EmployeePage.CbWorkStatus.currentText()}', `Date_Hired` = '{dhired}', `Job_Position` = '{Ui_EmployeePage.CbJobPosition.currentText()}', `Nationality` = '{Ui_EmployeePage.CbNationality.currentText()}', `Sex` = '{Ui_EmployeePage.CbSex.currentText()}', `Suffix` = '{suffix}' WHERE `id` = {Ui_EmployeePage.itemid}")

                #query1 = "UPDATE employees SET Last_name = %s, First_name = %s, Last_name = %s, MI = %s, Sex = %s, Birthday = %s, Age = %s, Contact_Number = %s, Status = %s, Address = %s, Work_Status = %s, Current_Site = %s,Date_Hired=%s, Job_Position = %s WHERE id = `%s`"
                #query5 = (Ui_EmployeePage.LELastName.text(), Ui_EmployeePage.LEFirstName.text(), Ui_EmployeePage.LEMI.text(), sex, bday, Ui_EmployeePage.LEAge.text(), Ui_EmployeePage.LEContact.text(), Ui_EmployeePage.CbStatus.currentText(),Ui_EmployeePage.LEAddress.text(), Ui_EmployeePage.CbWorkStatus.currentText(), Ui_EmployeePage.LECurrentSite.text(), dhired,Ui_EmployeePage.CbJobPosition.currentText(), Ui_EmployeePage.itemid)


                cursor.execute(query1)
                con.commit()

                #update for image
                query2 = "UPDATE employees SET Image=%s WHERE id=%s"
                query3 = (pixmap_bytes,Ui_EmployeePage.itemid)
                cursor.execute(query2,query3)
                con.commit()

                Ui_Activity.record_activity("admin",f"Update Employee Information of : {Ui_EmployeePage.LEFirstName.text()} {Ui_EmployeePage.LEMI.text()}. {Ui_EmployeePage.LELastName.text()}")

                msgBox = QMessageBox()
                msgBox.setIcon(QMessageBox.Information)
                msgBox.setText("Information was edited Successfully")
                msgBox.setWindowTitle("Message Alert")
                msgBox.setStandardButtons(QMessageBox.Ok)
                msgBox.buttonClicked.connect(msgBox.close)

                returnValue = msgBox.exec()
                if returnValue == QMessageBox.Ok:
                    Ui_EmployeePage.set_readonly(False, employee_list)
                    Ui_EmployeePage.get_employee(Ui_EmployeePage.employee_item)


            except :
                Ui_EmployeePage.show_dialog(str(sys.exc_info()))

    def mysql_select():


        cursor = con.cursor()
        cursor.execute("SELECT * FROM `employees`")

        return cursor.fetchall()

    def process_date(bday):
        index = 0
        start = 0
        flag1 = True
        flag2 = False
        flag3 = False

        while index < len(bday):
            if flag1 and (bday[index] == ","):
                year = bday[start:index]
                start = index + 1
                flag1 = False
                flag2 = True
            elif flag2 and (bday[index] == ","):
                month = bday[start:index]
                start = index + 1
                flag2 = False
                flag3 = True
            if flag3:
                day = bday[start:len(bday)]
                break
            index = index + 1

        return QDate(int(year), int(month), int(day))


    def set_info():
        # get_info_database
        if Ui_EmployeePage.itemid > 0:
            try:
                cursor = con.cursor()
                cursor.execute(f"SELECT * FROM `employees` WHERE `id` = {Ui_EmployeePage.itemid}")
                res = cursor.fetchall()


                for x in res:

                    

                    Ui_EmployeePage.LELastName.setText(x[1])
                    Ui_EmployeePage.LEFirstName.setText(x[2])
                    Ui_EmployeePage.LEMI.setText(x[3])
                    Ui_EmployeePage.LEAge.setText(str(x[7]))
                    Ui_EmployeePage.LEContact.setText(x[8])
                    Ui_EmployeePage.LEAddress.setText(x[11])
                    Ui_EmployeePage.LECurrentSite.setText(x[13])


                    
                    Ui_EmployeePage.CbStatus.setCurrentText(x[9])
                    Ui_EmployeePage.CbWorkStatus.setCurrentText(x[12])
                    Ui_EmployeePage.CbJobPosition.setCurrentText(x[15])

                    Ui_EmployeePage.LESuffix.setText(x[4])
                    Ui_EmployeePage.CbSex.setCurrentText(x[5])
                    Ui_EmployeePage.CbNationality.setCurrentText(x[10])


                    qimg = QtGui.QImage.fromData(x[16])
                    pixmap = QtGui.QPixmap.fromImage(qimg)
                    pixmap5 = pixmap.scaled(Ui_EmployeePage.LBImageContainer.width(), Ui_EmployeePage.LBImageContainer.height())

                    Ui_EmployeePage.LBImageContainer.setPixmap(pixmap5)
                    Ui_EmployeePage.LBImageContainer.setStyleSheet("border-radius:8px;\n"
                                        "font-size:16px;\n"
                                        "padding-left:0px;\n"
                                        "border:1px solid black;")
                    Ui_EmployeePage.LBImageContainer.setText("")



                    Ui_EmployeePage.DEBirthday.setDate(Ui_EmployeePage.process_date(x[6]))
                    Ui_EmployeePage.DEDateHired.setDate(Ui_EmployeePage.process_date(x[14]))

                    Ui_EmployeePage.LbID.setText(f"ID : {Ui_EmployeePage.DEDateHired.date().year()}00{x[0]}")
                    Ui_EmployeePage.eid=f"{Ui_EmployeePage.DEDateHired.date().year()}00{x[0]}"


            except mysql.connector.Error as e:
                Dialog.msg_dialog(str(e))  


    def get_info(item):
        Ui_EmployeePage.itemid = item.value
        Ui_EmployeePage.search_area.setText("")
        try:
            Ui_EmployeePage.set_info()
            Ui_EmployeePage.BtnPrint.show()
        except:
            Dialog.msg_dialog(str(sys.exc_info())) 

    def set_readonly1(bool,employee_list):
            Ui_EmployeePage.LELastName.setEnabled(bool)
            Ui_EmployeePage.LEFirstName.setEnabled(bool)
            Ui_EmployeePage.LEAge.setEnabled(False)
            Ui_EmployeePage.LEMI.setEnabled(bool)
            Ui_EmployeePage.LEContact.setEnabled(bool)
            Ui_EmployeePage.LEAddress.setEnabled(bool)
            Ui_EmployeePage.LECurrentSite.setEnabled(False)
            Ui_EmployeePage.DEBirthday.setEnabled(bool)
            Ui_EmployeePage.DEDateHired.setEnabled(bool)
            Ui_EmployeePage.CbStatus.setEnabled(bool)

            Ui_EmployeePage.CbWorkStatus.setEnabled(bool)
            Ui_EmployeePage.CbJobPosition.setEnabled(bool)
            Ui_EmployeePage.LESuffix.setEnabled(bool)
            Ui_EmployeePage.CbSex.setEnabled(bool)
            Ui_EmployeePage.CbNationality.setEnabled(bool)


            if bool == False:
                Ui_EmployeePage.Upload.hide()
                Ui_EmployeePage.BrnAdd.show()
                Ui_EmployeePage.BtnEdit.show()
                Ui_EmployeePage.BtnCancel.hide()
                employee_list.setEnabled(True)
                Ui_EmployeePage.BtnSave.hide()
                if Ui_EmployeePage.itemid > 0:
                    Ui_EmployeePage.set_info()
            else:
                Ui_EmployeePage.Upload.show()
                Ui_EmployeePage.BrnAdd.hide()
                Ui_EmployeePage.BtnCancel.show()
                Ui_EmployeePage.BtnEdit.hide()
                employee_list.setEnabled(False)
                Ui_EmployeePage.BtnSave.show()



    def set_readonly(bool,employee_list):
        if Ui_EmployeePage.itemid > 0:
            Ui_EmployeePage.LELastName.setEnabled(bool)
            Ui_EmployeePage.LEFirstName.setEnabled(bool)
            Ui_EmployeePage.LEAge.setEnabled(False)
            Ui_EmployeePage.LEMI.setEnabled(bool)
            Ui_EmployeePage.LEContact.setEnabled(bool)
            Ui_EmployeePage.LEAddress.setEnabled(bool)
            Ui_EmployeePage.LECurrentSite.setEnabled(False)
            Ui_EmployeePage.DEBirthday.setEnabled(bool)
            Ui_EmployeePage.DEDateHired.setEnabled(bool)
            Ui_EmployeePage.CbStatus.setEnabled(bool)


            Ui_EmployeePage.CbWorkStatus.setEnabled(bool)
            Ui_EmployeePage.CbJobPosition.setEnabled(bool)
            Ui_EmployeePage.LESuffix.setEnabled(bool)
            Ui_EmployeePage.CbSex.setEnabled(bool)
            Ui_EmployeePage.CbNationality.setEnabled(bool)


            if bool == False:
                Ui_EmployeePage.Upload.hide()
                Ui_EmployeePage.BrnAdd.show()
                Ui_EmployeePage.BtnEdit.show()
                Ui_EmployeePage.BtnCancel.hide()
                employee_list.setEnabled(True)
                Ui_EmployeePage.BtnSave.hide()
                if Ui_EmployeePage.itemid > 0:
                    Ui_EmployeePage.set_info()
                    Ui_EmployeePage.BtnPrint.show()
            else:
                Ui_EmployeePage.Upload.show()
                Ui_EmployeePage.BrnAdd.hide()
                Ui_EmployeePage.BtnCancel.show()
                Ui_EmployeePage.BtnEdit.hide()
                employee_list.setEnabled(False)
                Ui_EmployeePage.BtnSave.show()
                Ui_EmployeePage.BtnPrint.hide()
                
        else:
            Ui_EmployeePage.show_dialog("Please Select an Employee First")

    def search(list, string):
        list.clear()
        names=[]
        index = 0
        for x in range(len(Ui_EmployeePage.employee_id)):
            full_name = (f"{Ui_EmployeePage.employee_lname[index]}, {Ui_EmployeePage.employee_fname[index]} {Ui_EmployeePage.employee_mname[index]}.\n[{Ui_EmployeePage.employee_position[index]}]")
            item = QtWidgets.QListWidgetItem(full_name)
            item.setBackground(QColor('#666666')) if (index % 2) == 0 else item.setBackground(QColor('#595959'))
            item.setTextAlignment(QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
            item.value = Ui_EmployeePage.employee_id[index]
            list.addItem(item)
            names.append(full_name)
            index += 1

        if string != "":
            items = list.findItems(string, Qt.MatchStartsWith)
            if len(items) > 0:
                searched = {}
                z = 0
                for item in items:
                    list.takeItem(list.row(item))
                    searched[z] = item
                    z += 1

                list.clear()
                for i in range(len(searched)):
                    j = 0
                    while (searched[i].text() != names[j]):
                        j += 1
                    searched[i].value = Ui_EmployeePage.employee_id[j]
                    searched[i].setBackground(QColor('#666666')) if (i % 2) == 0 else searched[i].setBackground(QColor('#595959'))
                    searched[i].setTextAlignment(QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
                    list.addItem(searched[i])
            else:
                list.clear()



    def get_employee(employee_item):
        employee_item.clear()
        # get_info_database
        Ui_EmployeePage.employee_id=[]
        Ui_EmployeePage.employee_fname=[]
        Ui_EmployeePage.employee_lname=[]
        Ui_EmployeePage.employee_mname=[]
        Ui_EmployeePage.employee_position=[]

        try:
            res = Ui_EmployeePage.mysql_select()

            for x in res:
                Ui_EmployeePage.employee_id.append(x[0])
                Ui_EmployeePage.employee_fname.append(x[2])
                Ui_EmployeePage.employee_lname.append(x[1])
                Ui_EmployeePage.employee_mname.append(x[3])
                Ui_EmployeePage.employee_position.append(x[15])

        except mysql.connector.Error as e:
            Dialog.msg_dialog(str(e))  

        # insert elements
        index = 0
        while index < len(Ui_EmployeePage.employee_id):
            try:
                full_name = (
                    f"{Ui_EmployeePage.employee_lname[index]}, {Ui_EmployeePage.employee_fname[index]} {Ui_EmployeePage.employee_mname[index]}.\n[{Ui_EmployeePage.employee_position[index]}]")
                item = QtWidgets.QListWidgetItem(full_name)
                item.setBackground(QColor('#666666')) if (index % 2) == 0 else item.setBackground(QColor('#595959'))
                item.value = Ui_EmployeePage.employee_id[index]
                item.setTextAlignment(QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
                employee_item.addItem(item)
                # item = project_list.item(index)
                # item.setText(_translate("DashbaordWindow", ))
                index = index + 1
            except:
                Dialog.msg_dialog(str(sys.exc_info()))  




    def addnationality(_translate):
        y=0
        for x in nationality:
            Ui_EmployeePage.CbNationality.addItem("")
            Ui_EmployeePage.CbNationality.setItemText(y, _translate("DashbaordWindow", x))
            y += 1

        Ui_EmployeePage.CbNationality.setCurrentText('Filipino')



    def EmployeePage(employee_page,DashbaordWindow):
        employee_label = QtWidgets.QLabel(employee_page)
        employee_label.setGeometry(QtCore.QRect(10, 10, 281, 81))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        employee_label.setFont(font)
        employee_label.setStyleSheet("color: rgb(255, 255, 255);\n"
                                     "background-color: rgb(148, 0, 2,.4);\n"
                                     "border-radius:8px;\n"
                                     "")
        employee_label.setLineWidth(7)
        employee_label.setIndent(50)
        employee_label.setObjectName("employee_label")
        employee_list = QtWidgets.QScrollArea(employee_page)
        employee_list.setGeometry(QtCore.QRect(10, 176, 281, 281))
        employee_list.setStyleSheet("background-color: rgba(0, 0, 0,.3);\n"
                                    "border-radius:5px;")
        employee_list.setWidgetResizable(True)
        employee_list.setObjectName("employee_list")
        EmployeeListScroll = QtWidgets.QWidget()
        EmployeeListScroll.setGeometry(QtCore.QRect(0, 0, 281, 281))
        EmployeeListScroll.setObjectName("EmployeeListScroll")
        employee_list.setWidget(EmployeeListScroll)
        SearchGroup = QtWidgets.QGroupBox(employee_page)
        SearchGroup.setGeometry(QtCore.QRect(20, 120, 261, 41))
        SearchGroup.setStyleSheet("color:white;\n"
                                  "border-radius:5px;\n"
                                  " border-bottom:3px  solid white;\n"
                                  " border-left:3px  solid white;\n"
                                  " border-right:3px  solid white;\n"
                                  " border-top:3px  solid white;")
        SearchGroup.setTitle("")
        SearchGroup.setObjectName("SearchGroup")
        Ui_EmployeePage.search_area = QtWidgets.QLineEdit(SearchGroup)
        Ui_EmployeePage.search_area.setGeometry(QtCore.QRect(0, 0, 211, 41))
        Ui_EmployeePage.search_area.setStyleSheet("padding-left:10px;background-color: rgba(255, 255, 255,0.2);\n"
                                  "font-size:16px;\n"
                                  "border: none;\n"
                                  "color:white\n"
                                  "")
        Ui_EmployeePage.search_area.setText("")
        Ui_EmployeePage.search_area.setCursorPosition(0)
        Ui_EmployeePage.search_area.setObjectName("search_area")
        search_button = QtWidgets.QPushButton(SearchGroup)
        search_button.setGeometry(QtCore.QRect(210, 0, 51, 41))
        search_button.setStyleSheet("border-radius:5px;")
        search_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/Assets/SearchIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        search_button.setIcon(icon)
        search_button.setIconSize(QtCore.QSize(20, 20))
        search_button.setObjectName("search_button")
        Ui_EmployeePage.BrnAdd = QtWidgets.QPushButton(employee_page)
        Ui_EmployeePage.BrnAdd.setGeometry(QtCore.QRect(24, 470, 104, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        Ui_EmployeePage.BrnAdd.setFont(font)
        Ui_EmployeePage.BrnAdd.setLayoutDirection(QtCore.Qt.LeftToRight)
        Ui_EmployeePage.BrnAdd.setStyleSheet("background-color: rgba(0, 0, 0,0.9);\n"
                                             "border-radius:5px;\n"
                                             "color:white;")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icons/Assets/AddIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Ui_EmployeePage.BrnAdd.setIcon(icon1)
        Ui_EmployeePage.BrnAdd.setObjectName("BrnAdd")
        Ui_EmployeePage.BtnEdit = QtWidgets.QPushButton(employee_page)
        Ui_EmployeePage.BtnEdit.setGeometry(QtCore.QRect(167, 470, 104, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        Ui_EmployeePage.BtnEdit.setFont(font)
        Ui_EmployeePage.BtnEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        Ui_EmployeePage.BtnEdit.setStyleSheet("background-color: rgba(0, 0, 0,0.9);\n"
                                              "border-radius:5px;\n"
                                              "color:white;")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Icons/Assets/EditIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Ui_EmployeePage.BtnEdit.setIcon(icon2)
        Ui_EmployeePage.BtnEdit.setObjectName("BtnEdit")
        DisplayGroup = QtWidgets.QGroupBox(employee_page)
        DisplayGroup.setGeometry(QtCore.QRect(318, 10, 731, 501))
        DisplayGroup.setStyleSheet("color: rgb(255, 255, 255);border:none;\n"
                                   "")
        DisplayGroup.setTitle("")
        DisplayGroup.setObjectName("DisplayGroup")
        DisplayGroupBG = QtWidgets.QLabel(DisplayGroup)
        DisplayGroupBG.setGeometry(QtCore.QRect(0, 0, 731, 500))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        DisplayGroupBG.setFont(font)
        DisplayGroupBG.setLayoutDirection(QtCore.Qt.LeftToRight)
        DisplayGroupBG.setStyleSheet("color: rgb(255, 255, 255);\n"
                                     "background-color: rgb(148, 0, 2,.4);\n"
                                     "border-radius:10px;")
        DisplayGroupBG.setFrameShadow(QtWidgets.QFrame.Plain)
        DisplayGroupBG.setText("")
        DisplayGroupBG.setObjectName("DisplayGroupBG")
        Ui_EmployeePage.LELastName = QtWidgets.QLineEdit(DisplayGroup)
        Ui_EmployeePage.LELastName.setGeometry(QtCore.QRect(450, 60, 161, 31))
        Ui_EmployeePage.LELastName.setStyleSheet("background-color: rgba(255, 255, 255);color:black;\n"
                                                 "border-radius:5px;")
        Ui_EmployeePage.LELastName.setObjectName("LELastName")
        Ui_EmployeePage.LEFirstName = QtWidgets.QLineEdit(DisplayGroup)
        Ui_EmployeePage.LEFirstName.setGeometry(QtCore.QRect(190, 60, 181, 31))
        Ui_EmployeePage.LEFirstName.setStyleSheet("background-color: rgba(255, 255, 255);color:black;\n"
                                                  "border-radius:5px;")
        Ui_EmployeePage.LEFirstName.setObjectName("LEFirstName")
        Ui_EmployeePage.LBImageContainer = QtWidgets.QLabel(DisplayGroup)
        Ui_EmployeePage.LBImageContainer.setGeometry(QtCore.QRect(20, 60, 131, 131))
        Ui_EmployeePage.LBImageContainer.setStyleSheet("color: rgb(255, 255, 255);\n"
                                                       "background-color: rgb(0, 0, 0,.4);\n"
                                                       "border-radius:8px;\n"
                                                       "font-size:16px;\n"
                                                       "padding-left:40px;\n"
                                                       "border:1px solid black;")
        Ui_EmployeePage.LBImageContainer.setObjectName("LBImageContainer")
        Ui_EmployeePage.LEMI = QtWidgets.QLineEdit(DisplayGroup)
        Ui_EmployeePage.LEMI.setGeometry(QtCore.QRect(380, 60, 61, 31))
        Ui_EmployeePage.LEMI.setStyleSheet("background-color: rgba(255, 255, 255);color:black;\n"
                                           "border-radius:5px;")
        Ui_EmployeePage.LEMI.setObjectName("LEMI")
        Ui_EmployeePage.DEBirthday = QtWidgets.QDateEdit(DisplayGroup)
        Ui_EmployeePage.DEBirthday.setGeometry(QtCore.QRect(190, 130, 181, 31))
        Ui_EmployeePage.DEBirthday.setStyleSheet("color:maroon;\n"
                                                 "background-color:rgb(255, 255, 255);\n"
                                                 "border-radius:5px;")
        Ui_EmployeePage.DEBirthday.setCalendarPopup(True)
        Ui_EmployeePage.DEBirthday.setObjectName("DEBirthday")
        Ui_EmployeePage.CbStatus = QtWidgets.QComboBox(DisplayGroup)
        Ui_EmployeePage.CbStatus.setGeometry(QtCore.QRect(350, 210, 150, 31))
        Ui_EmployeePage.CbStatus.setStyleSheet("color: rgb(255, 255, 255);\n"
                                               "background-color: rgb(255,255,255,.2);\n"
                                               "font-size:15px;\n"
                                               "border-radius:5px;")
        Ui_EmployeePage.CbStatus.setObjectName("CbStatus")
        Ui_EmployeePage.CbStatus.addItem("")
        Ui_EmployeePage.CbStatus.addItem("")
        Ui_EmployeePage.CbStatus.addItem("")
        Ui_EmployeePage.CbStatus.addItem("")
        Ui_EmployeePage.LEAge = QtWidgets.QLineEdit(DisplayGroup)
        Ui_EmployeePage.LEAge.setGeometry(QtCore.QRect(390, 130, 101, 31))
        Ui_EmployeePage.LEAge.setStyleSheet("background-color: rgba(255, 255, 255);color:black;\n"
                                            "border-radius:5px;")
        Ui_EmployeePage.LEAge.setReadOnly(True)
        Ui_EmployeePage.LEAge.setObjectName("LEAge")
        Ui_EmployeePage.LEAddress = QtWidgets.QLineEdit(DisplayGroup)
        Ui_EmployeePage.LEAddress.setGeometry(QtCore.QRect(190, 280, 500, 31))
        Ui_EmployeePage.LEAddress.setStyleSheet("background-color: rgba(255, 255, 255);color:black;\n"
                                                "border-radius:5px;")
        Ui_EmployeePage.LEAddress.setObjectName("LEAddress")
        Ui_EmployeePage.CbWorkStatus = QtWidgets.QComboBox(DisplayGroup)
        Ui_EmployeePage.CbWorkStatus.setGeometry(QtCore.QRect(560, 350, 131, 31))
        Ui_EmployeePage.CbWorkStatus.setStyleSheet("color: rgb(255, 255, 255);\n"
                                                   "background-color: rgb(255,255,255,.2);\n"
                                                   "font-size:15px;\n"
                                                   "border-radius:5px;")
        Ui_EmployeePage.CbWorkStatus.setObjectName("CbWorkStatus")
        Ui_EmployeePage.CbWorkStatus.addItem("")
        Ui_EmployeePage.CbWorkStatus.addItem("")
        Ui_EmployeePage.LECurrentSite = QtWidgets.QLineEdit(DisplayGroup)
        Ui_EmployeePage.LECurrentSite.setEnabled(True)
        Ui_EmployeePage.LECurrentSite.setGeometry(QtCore.QRect(190, 420, 500, 31))
        Ui_EmployeePage.LECurrentSite.setAcceptDrops(False)
        Ui_EmployeePage.LECurrentSite.setStyleSheet("background-color: rgba(255, 255, 255);color:black;\n"
                                                    "border-radius:5px;")
        Ui_EmployeePage.LECurrentSite.setText("")
        Ui_EmployeePage.LECurrentSite.setObjectName("LECurrentSite")
        Ui_EmployeePage.Upload = QtWidgets.QPushButton(DisplayGroup)
        Ui_EmployeePage.Upload.setGeometry(QtCore.QRect(20, 210, 130, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        Ui_EmployeePage.Upload.setFont(font)
        Ui_EmployeePage.Upload.setLayoutDirection(QtCore.Qt.LeftToRight)
        Ui_EmployeePage.Upload.setStyleSheet("background-color: rgba(0, 0, 0,0.9);\n"
                                             "border-radius:5px;")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Icons/Assets/UploadIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Ui_EmployeePage.Upload.setIcon(icon3)
        Ui_EmployeePage.Upload.setObjectName("Upload")
        LbLastname = QtWidgets.QLabel(DisplayGroup)
        LbLastname.setGeometry(QtCore.QRect(450, 40, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        LbLastname.setFont(font)
        LbLastname.setObjectName("LbLastname")
        LbFirstname = QtWidgets.QLabel(DisplayGroup)
        LbFirstname.setGeometry(QtCore.QRect(190, 40, 111, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        LbFirstname.setFont(font)
        LbFirstname.setObjectName("LbFirstname")
        LbMi = QtWidgets.QLabel(DisplayGroup)
        LbMi.setGeometry(QtCore.QRect(380, 40, 31, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        LbMi.setFont(font)
        LbMi.setObjectName("LbMi")
        LbSex = QtWidgets.QLabel(DisplayGroup)
        LbSex.setGeometry(QtCore.QRect(190, 190, 47, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        LbSex.setFont(font)
        LbSex.setObjectName("LbSex")
        LbBirthday = QtWidgets.QLabel(DisplayGroup)
        LbBirthday.setGeometry(QtCore.QRect(190, 110, 151, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        LbBirthday.setFont(font)
        LbBirthday.setObjectName("LbBirthday")
        LbStatus = QtWidgets.QLabel(DisplayGroup)
        LbStatus.setGeometry(QtCore.QRect(350, 190, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        LbStatus.setFont(font)
        LbStatus.setObjectName("LbStatus")
        LbAddress = QtWidgets.QLabel(DisplayGroup)
        LbAddress.setGeometry(QtCore.QRect(190, 260, 161, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        LbAddress.setFont(font)
        LbAddress.setObjectName("LbAddress")
        LbWorkStatus = QtWidgets.QLabel(DisplayGroup)
        LbWorkStatus.setGeometry(QtCore.QRect(560, 330, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        LbWorkStatus.setFont(font)
        LbWorkStatus.setObjectName("LbWorkStatus")
        LbJobPosition = QtWidgets.QLabel(DisplayGroup)
        LbJobPosition.setGeometry(QtCore.QRect(360, 330, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        LbJobPosition.setFont(font)
        LbJobPosition.setObjectName("LbJobPosition")
        LbHiredDate = QtWidgets.QLabel(DisplayGroup)
        LbHiredDate.setGeometry(QtCore.QRect(190, 330, 151, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        LbHiredDate.setFont(font)
        LbHiredDate.setObjectName("LbHiredDate")
        LbContact = QtWidgets.QLabel(DisplayGroup)
        LbContact.setGeometry(QtCore.QRect(510, 110, 121, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        LbContact.setFont(font)
        LbContact.setObjectName("LbContact")
        LbAge = QtWidgets.QLabel(DisplayGroup)
        LbAge.setGeometry(QtCore.QRect(390, 110, 47, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        LbAge.setFont(font)
        LbAge.setObjectName("LbAge")
        LbCurrent = QtWidgets.QLabel(DisplayGroup)
        LbCurrent.setGeometry(QtCore.QRect(190, 400, 171, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        LbCurrent.setFont(font)
        LbCurrent.setObjectName("LbCurrent")
        Ui_EmployeePage.LbID = QtWidgets.QLabel(DisplayGroup)
        Ui_EmployeePage.LbID.setGeometry(QtCore.QRect(30, 30, 111, 25))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        Ui_EmployeePage.LbID.setFont(font)
        Ui_EmployeePage.LbID.setObjectName("LbID")
        Ui_EmployeePage.DEDateHired = QtWidgets.QDateEdit(DisplayGroup)
        Ui_EmployeePage.DEDateHired.setGeometry(QtCore.QRect(190, 350, 151, 31))
        Ui_EmployeePage.DEDateHired.setStyleSheet("color:maroon;;\n"
                                                  "background-color:rgb(255, 255, 255);\n"
                                                  "border-radius:5px;")
        Ui_EmployeePage.DEDateHired.setCalendarPopup(True)
        Ui_EmployeePage.DEDateHired.setObjectName("DEDateHired")
        Ui_EmployeePage.CbJobPosition = QtWidgets.QComboBox(DisplayGroup)
        Ui_EmployeePage.CbJobPosition.setGeometry(QtCore.QRect(360, 350, 181, 31))
        Ui_EmployeePage.CbJobPosition.setStyleSheet("color: rgb(255, 255, 255);\n"
                                                    "background-color: rgb(255,255,255,.2);\n"
                                                    "font-size:15px;\n"
                                                    "border-radius:5px;")
        Ui_EmployeePage.CbJobPosition.setObjectName("CbJobPosition")
        Ui_EmployeePage.CbJobPosition.addItem("")
        Ui_EmployeePage.CbJobPosition.addItem("")
        Ui_EmployeePage.CbJobPosition.addItem("")
        Ui_EmployeePage.CbJobPosition.addItem("")
        Ui_EmployeePage.CbJobPosition.addItem("")
        Ui_EmployeePage.CbJobPosition.addItem("")
        Ui_EmployeePage.CbJobPosition.addItem("")
        Ui_EmployeePage.CbJobPosition.addItem("")
        Prenumber = QtWidgets.QLabel(DisplayGroup)
        Prenumber.setGeometry(QtCore.QRect(510, 138, 31, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        Prenumber.setFont(font)
        Prenumber.setObjectName("Prenumber")
        Ui_EmployeePage.LESuffix = QtWidgets.QLineEdit(DisplayGroup)
        Ui_EmployeePage.LESuffix.setGeometry(QtCore.QRect(620, 60, 71, 31))
        Ui_EmployeePage.LESuffix.setStyleSheet("background-color: rgba(255, 255, 255);color:black;\n"
                                               "border-radius:5px;")
        Ui_EmployeePage.LESuffix.setObjectName("LESuffix")
        LbSuffix = QtWidgets.QLabel(DisplayGroup)
        LbSuffix.setGeometry(QtCore.QRect(620, 40, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        LbSuffix.setFont(font)
        LbSuffix.setObjectName("LbSuffix")
        Ui_EmployeePage.CbSex = QtWidgets.QComboBox(DisplayGroup)
        Ui_EmployeePage.CbSex.setGeometry(QtCore.QRect(190, 210, 141, 31))
        Ui_EmployeePage.CbSex.setStyleSheet("color: rgb(255, 255, 255);\n"
                                            "background-color: rgb(255,255,255,.2);\n"
                                            "font-size:15px;\n"
                                            "border-radius:5px;")
        Ui_EmployeePage.CbSex.setObjectName("CbSex")
        Ui_EmployeePage.CbSex.addItem("")
        Ui_EmployeePage.CbSex.addItem("")
        Ui_EmployeePage.CbNationality = QtWidgets.QComboBox(DisplayGroup)
        Ui_EmployeePage.CbNationality.setGeometry(QtCore.QRect(520, 210, 171, 31))
        Ui_EmployeePage.CbNationality.setStyleSheet("border-radius:5px;color: rgb(255, 255, 255);\n"
                                                    "background-color: rgb(255,255,255,.2);\n"
                                                    "font-size:15px;")
        Ui_EmployeePage.CbNationality.setObjectName("CbNationality")
        LbNationality = QtWidgets.QLabel(DisplayGroup)
        LbNationality.setGeometry(QtCore.QRect(520, 190, 151, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        LbNationality.setFont(font)
        LbNationality.setObjectName("LbNationality")
        Ui_EmployeePage.LEContact = QtWidgets.QLineEdit(DisplayGroup)
        Ui_EmployeePage.LEContact.setGeometry(QtCore.QRect(540, 130, 151, 31))
        Ui_EmployeePage.LEContact.setStyleSheet("background-color: rgba(255, 255, 255);color:black;\n"
                                                "border-radius:5px;")
        Ui_EmployeePage.LEContact.setObjectName("LEContact")
        Ui_EmployeePage.BtnSave = QtWidgets.QPushButton(DisplayGroup)
        Ui_EmployeePage.BtnSave.setGeometry(QtCore.QRect(20, 460, 130, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        Ui_EmployeePage.BtnSave.setFont(font)
        Ui_EmployeePage.BtnSave.setLayoutDirection(QtCore.Qt.LeftToRight)
        Ui_EmployeePage.BtnSave.setStyleSheet("background-color: rgba(0, 0, 0,0.9);\n"
                                              "border-radius:5px;")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Icons/Assets/SaveIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Ui_EmployeePage.BtnSave.setIcon(icon4)
        Ui_EmployeePage.BtnSave.setObjectName("Save")

        Ui_EmployeePage.BtnPrint = QtWidgets.QPushButton(DisplayGroup)
        Ui_EmployeePage.BtnPrint.setGeometry(QtCore.QRect(20, 460, 130, 31))
        Ui_EmployeePage.BtnPrint.setFont(font)
        Ui_EmployeePage.BtnPrint.setLayoutDirection(QtCore.Qt.LeftToRight)
        Ui_EmployeePage.BtnPrint.setStyleSheet("background-color: rgba(0, 0, 0,0.9);\n"
                                              "border-radius:5px;")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Icons/Assets/PrintIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Ui_EmployeePage.BtnPrint.setIcon(icon4)
        Ui_EmployeePage.BtnPrint.setObjectName("Print")
        Ui_EmployeePage.BtnPrint.hide()

        DisplayGroupBG.raise_()
        Ui_EmployeePage.LELastName.raise_()
        Ui_EmployeePage.LBImageContainer.raise_()
        Ui_EmployeePage.LEMI.raise_()
        Ui_EmployeePage.DEBirthday.raise_()
        Ui_EmployeePage.CbStatus.raise_()
        Ui_EmployeePage.LEAge.raise_()
        Ui_EmployeePage.LEAddress.raise_()
        Ui_EmployeePage.CbWorkStatus.raise_()
        Ui_EmployeePage.LECurrentSite.raise_()
        Ui_EmployeePage.Upload.raise_()
        LbLastname.raise_()
        LbFirstname.raise_()
        LbMi.raise_()
        LbSex.raise_()
        LbBirthday.raise_()
        LbStatus.raise_()
        LbAddress.raise_()
        LbWorkStatus.raise_()
        LbJobPosition.raise_()
        LbHiredDate.raise_()
        LbContact.raise_()
        LbAge.raise_()
        LbCurrent.raise_()
        Ui_EmployeePage.LbID.raise_()
        Ui_EmployeePage.DEDateHired.raise_()
        Ui_EmployeePage.CbJobPosition.raise_()
        Prenumber.raise_()
        Ui_EmployeePage.LESuffix.raise_()
        LbSuffix.raise_()
        Ui_EmployeePage.CbSex.raise_()
        Ui_EmployeePage.CbNationality.raise_()
        LbNationality.raise_()
        Ui_EmployeePage.LEContact.raise_()
        Ui_EmployeePage.BtnSave.raise_()
        Ui_EmployeePage.BtnPrint.raise_()
        Ui_EmployeePage.LEFirstName.raise_()
        DisplayGroup.raise_()
        employee_label.raise_()
        employee_list.raise_()
        SearchGroup.raise_()
        Ui_EmployeePage.BrnAdd.raise_()
        Ui_EmployeePage.BtnEdit.raise_()

        _translate = QtCore.QCoreApplication.translate
        employee_label.setText(_translate("DashbaordWindow", "Employee List"))
        Ui_EmployeePage.BrnAdd.setText(_translate("DashbaordWindow", "  Add"))
        Ui_EmployeePage.BtnEdit.setText(_translate("DashbaordWindow", "  Edit"))
        Ui_EmployeePage.LELastName.setPlaceholderText(_translate("DashbaordWindow", "Last Name"))
        Ui_EmployeePage.LEFirstName.setPlaceholderText(_translate("DashbaordWindow", "First Name"))
        Ui_EmployeePage.LBImageContainer.setText(_translate("DashbaordWindow", "Image"))
        Ui_EmployeePage.LEMI.setPlaceholderText(_translate("DashbaordWindow", "M.I."))
        Ui_EmployeePage.DEBirthday.setDisplayFormat(_translate("DashbaordWindow", "MMM d  yyyy"))
        Ui_EmployeePage.CbStatus.setItemText(0, _translate("DashbaordWindow", "Single"))
        Ui_EmployeePage.CbStatus.setItemText(1, _translate("DashbaordWindow", "Married"))
        Ui_EmployeePage.CbStatus.setItemText(2, _translate("DashbaordWindow", "Widowed"))
        Ui_EmployeePage.CbStatus.setItemText(3, _translate("DashbaordWindow", "Divorced"))
        Ui_EmployeePage.LEAge.setPlaceholderText(_translate("DashbaordWindow", "Age"))
        Ui_EmployeePage.LEAddress.setPlaceholderText(_translate("DashbaordWindow", "Complete Address"))
        Ui_EmployeePage.CbWorkStatus.setItemText(0, _translate("DashbaordWindow", "Active"))
        Ui_EmployeePage.CbWorkStatus.setItemText(1, _translate("DashbaordWindow", "Inactive"))
        Ui_EmployeePage.LECurrentSite.setPlaceholderText(_translate("DashbaordWindow", "Current Site Designation"))
        Ui_EmployeePage.Upload.setText(_translate("DashbaordWindow", "  Upload"))
        LbLastname.setText(_translate("DashbaordWindow", "Last Name"))
        LbFirstname.setText(_translate("DashbaordWindow", "First Name"))
        LbMi.setText(_translate("DashbaordWindow", "M.I"))
        LbSex.setText(_translate("DashbaordWindow", "Sex"))
        LbBirthday.setText(_translate("DashbaordWindow", "Date of Birth"))
        LbStatus.setText(_translate("DashbaordWindow", "Civil Status"))
        LbAddress.setText(_translate("DashbaordWindow", "Complete Address"))
        LbWorkStatus.setText(_translate("DashbaordWindow", "Work Status"))
        LbJobPosition.setText(_translate("DashbaordWindow", "Job Position"))
        LbHiredDate.setText(_translate("DashbaordWindow", "Date Hired"))
        LbContact.setText(_translate("DashbaordWindow", "Contact Number"))
        LbAge.setText(_translate("DashbaordWindow", "Age"))
        LbCurrent.setText(_translate("DashbaordWindow", "Current Site Designation"))
        Ui_EmployeePage.LbID.setText(_translate("DashbaordWindow", "ID"))
        Ui_EmployeePage.DEDateHired.setDisplayFormat(_translate("DashbaordWindow", "MMM d  yyyy"))
        Ui_EmployeePage.CbJobPosition.setItemText(0, _translate("DashbaordWindow", "General Manager"))
        Ui_EmployeePage.CbJobPosition.setItemText(1, _translate("DashbaordWindow", "Purchaser"))
        Ui_EmployeePage.CbJobPosition.setItemText(2, _translate("DashbaordWindow", "Supervisor"))
        Ui_EmployeePage.CbJobPosition.setItemText(3, _translate("DashbaordWindow", "Warehouseman"))
        Ui_EmployeePage.CbJobPosition.setItemText(4, _translate("DashbaordWindow", "Leanman"))
        Ui_EmployeePage.CbJobPosition.setItemText(5, _translate("DashbaordWindow", "Helper"))
        Ui_EmployeePage.CbJobPosition.setItemText(6, _translate("DashbaordWindow", "Installer"))
        Ui_EmployeePage.CbJobPosition.setItemText(7, _translate("DashbaordWindow", "AC Tech"))
        Prenumber.setText(_translate("DashbaordWindow", "+63"))
        Ui_EmployeePage.LESuffix.setPlaceholderText(_translate("DashbaordWindow", "Suffix"))
        LbSuffix.setText(_translate("DashbaordWindow", "Suffix"))
        Ui_EmployeePage.CbSex.setItemText(0, _translate("DashbaordWindow", "Male"))
        Ui_EmployeePage.CbSex.setItemText(1, _translate("DashbaordWindow", "Female"))

        LbNationality.setText(_translate("DashbaordWindow", "Nationality"))
        Ui_EmployeePage.LEContact.setPlaceholderText(_translate("DashbaordWindow", "9xxxxxxxxx"))
        Ui_EmployeePage.BtnSave.setText(_translate("DashbaordWindow", "  Save"))
        Ui_EmployeePage.BtnPrint.setText(_translate("DashbaordWindow", "  Print ID"))
        Ui_EmployeePage.search_area.setPlaceholderText(_translate("DashbaordWindow", "Search Employee"))

        # employee_item

        Ui_EmployeePage.employee_item = QtWidgets.QListWidget(EmployeeListScroll)
        Ui_EmployeePage.employee_item.setGeometry(QtCore.QRect(0, 0, 281, 281))
        Ui_EmployeePage.employee_item.setStyleSheet("background-color: rgb(167, 167, 167,.4);\n"
                                    "border-radius:5px;\n"
                                    "font-size:16px;\n"
                                    "color:white;\n"

                                    "")
        Ui_EmployeePage.employee_item.setLayoutDirection(QtCore.Qt.RightToLeft)
        Ui_EmployeePage.employee_item.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        Ui_EmployeePage.employee_item.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        Ui_EmployeePage.employee_item.setObjectName("project_list")
        Ui_EmployeePage.employee_item.raise_()

        # Cancel
        Ui_EmployeePage.BtnCancel = QtWidgets.QPushButton(employee_page)
        Ui_EmployeePage.BtnCancel.setGeometry(QtCore.QRect(167, 470, 104, 30))
        Ui_EmployeePage.BtnCancel.setStyleSheet("background-color: rgba(0, 0, 0,0.9);\n"
                                              "border-radius:5px;\n"
                                              "color:white;")
        Ui_EmployeePage.BtnCancel.setText("  Cancel")
        Ui_EmployeePage.BtnCancel.setObjectName("BtnCancel")
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        Ui_EmployeePage.BtnCancel.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icons/Assets/RemoveIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Ui_EmployeePage.BtnCancel.setIcon(icon1)

        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(-1)

        Ui_EmployeePage.LELastName.setFont(font)
        Ui_EmployeePage.LEFirstName.setFont(font)
        Ui_EmployeePage.LEMI.setFont(font)
        Ui_EmployeePage.LEAge.setFont(font)
        Ui_EmployeePage.LEContact.setFont(font)
        Ui_EmployeePage.LEAddress.setFont(font)
        Ui_EmployeePage.DEBirthday.setFont(font)
        Ui_EmployeePage.DEDateHired.setFont(font)
        Ui_EmployeePage.CbStatus.setFont(font)
        Ui_EmployeePage.CbWorkStatus.setFont(font)
        Ui_EmployeePage.CbJobPosition.setFont(font)
        Ui_EmployeePage.LBImageContainer.setFont(font)
        Ui_EmployeePage.LESuffix.setFont(font)
        Ui_EmployeePage.CbSex.setFont(font)
        Ui_EmployeePage.CbNationality.setFont(font)

        Ui_EmployeePage.CbSex.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        Ui_EmployeePage.CbNationality.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        Ui_EmployeePage.CbStatus.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        Ui_EmployeePage.CbWorkStatus.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        Ui_EmployeePage.CbJobPosition.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))

        #load EMployee form
        Ui_EmployeeForm.employee_page_form(DashbaordWindow)

        #Functions
        Ui_EmployeePage.get_employee(Ui_EmployeePage.employee_item)

        # selection function
        Ui_EmployeePage.employee_item.itemClicked.connect(Ui_EmployeePage.get_info)

        #btn add functions
        Ui_EmployeePage.BrnAdd.clicked.connect(lambda: Ui_EmployeeForm.showForm())
        Ui_EmployeePage.Upload.clicked.connect(lambda: Ui_EmployeeForm.openImage(DashbaordWindow, Ui_EmployeePage.LBImageContainer))
        #Default Input Readonly
        Ui_EmployeePage.set_readonly1(False,employee_list)
        #set Enable
        Ui_EmployeePage.BtnEdit.clicked.connect(lambda: Ui_EmployeePage.set_readonly(True,employee_list))
        Ui_EmployeePage.BtnCancel.clicked.connect(lambda : Ui_EmployeePage.cancel_dialog(employee_list))
        Ui_EmployeePage.BtnSave.clicked.connect(lambda: Ui_EmployeePage.submitForm(employee_list,Ui_EmployeePage.employee_item))

        # LB Functions

        Ui_EmployeePage.LELastName.textEdited.connect(lambda: Ui_EmployeeForm.keyPressEvent(Ui_EmployeePage.LELastName))
        Ui_EmployeePage.LEFirstName.textEdited.connect(lambda: Ui_EmployeeForm.keyPressEvent(Ui_EmployeePage.LEFirstName))
        Ui_EmployeePage.LEMI.textEdited.connect(lambda: Ui_EmployeeForm.keyPressEvent(Ui_EmployeePage.LEMI))
        Ui_EmployeePage.LEAddress.textEdited.connect(lambda: Ui_EmployeeForm.keyPressEvent(Ui_EmployeePage.LEAddress))
        Ui_EmployeePage.LECurrentSite.textEdited.connect(lambda: Ui_EmployeeForm.keyPressEvent(Ui_EmployeePage.LECurrentSite))


        #Addition Line edit limit
        Ui_EmployeePage.LELastName.setMaxLength(25)
        Ui_EmployeePage.LEFirstName.setMaxLength(25)
        Ui_EmployeePage.LEMI.setMaxLength(1)
        Ui_EmployeePage.LEContact.setMaxLength(10)
        Ui_EmployeePage.LEAddress.setMaxLength(100)
        Ui_EmployeePage.LECurrentSite.setMaxLength(50)

        my_regex = QtCore.QRegExp("^[0-9]*$")
        my_validator = QtGui.QRegExpValidator(my_regex, Ui_EmployeePage.LEContact)
        Ui_EmployeePage.LEContact.setValidator(my_validator)

        #Nationality
        Ui_EmployeePage.addnationality(_translate)

        #search
        Ui_EmployeePage.search_area.textChanged.connect(lambda :Ui_EmployeePage.search(Ui_EmployeePage.employee_item,Ui_EmployeePage.search_area.text()))

        #printbtn

        Ui_EmployeePage.BtnPrint.clicked.connect(lambda: Ui_EmployeePage.printID())

        Ui_EmployeePage.DEBirthday.dateChanged.connect(lambda: Ui_EmployeeForm.setAge(Ui_EmployeePage.DEBirthday,Ui_EmployeePage.LEAge))




class Ui_EmployeeForm(object):
    DisplayGroup2 = QtWidgets
    LbID=QtWidgets

    def keyPressEvent(label):
        text = label.text()
        if len(text)>0:
            label.setText(text.title())


    def submitForm(LELastName,LEFirstName,LEMI,LEAge,LEContact, EAddress,DEBirthday,
        DEDateHired,CbStatus,CbWorkStatus,CbJobPosition,LBImageContainer,LESuffix,CbSex,CbNationality):

        if (LELastName.text() == "") | (LEFirstName.text() =="")| (LEMI.text() =="") |(LEAge.text() =="") |(LEContact.text() =="") |(EAddress.text() ==""):
            msgBox = QMessageBox()
            msgBox.setIcon(QMessageBox.Information)
            msgBox.setText("Please complete the form first")
            msgBox.setWindowTitle("Message Alert")
            msgBox.setStandardButtons(QMessageBox.Ok)
            msgBox.buttonClicked.connect(msgBox.close)
            returnValue = msgBox.exec()

        elif (LBImageContainer.text()=="Image"):
            msgBox = QMessageBox()
            msgBox.setIcon(QMessageBox.Information)
            msgBox.setText("Please select an Image")
            msgBox.setWindowTitle("Message Alert")
            msgBox.setStandardButtons(QMessageBox.Ok)
            msgBox.buttonClicked.connect(msgBox.close)
            returnValue = msgBox.exec()

        elif not len(LEContact.text())==10:
            msgBox = QMessageBox()
            msgBox.setIcon(QMessageBox.Information)
            msgBox.setText("Invalid Contact Number")
            msgBox.setWindowTitle("Message Alert")
            msgBox.setStandardButtons(QMessageBox.Ok)
            msgBox.buttonClicked.connect(msgBox.close)
            returnValue = msgBox.exec()


        else:
            pixmap = LBImageContainer.pixmap()
            ba = QtCore.QByteArray()
            buff = QtCore.QBuffer(ba)
            buff.open(QtCore.QIODevice.WriteOnly)
            ok = pixmap.save(buff, "PNG")
            assert ok
            pixmap_bytes = ba.data()

            suffix = ""
            if LESuffix.text() == "":
                suffix = "N/A"
            else:
                suffix = LESuffix.text()

            bday = (f"{DEBirthday.date().year()},{DEBirthday.date().month()},{DEBirthday.date().day()}")
            dhired = (f"{DEDateHired.date().year()},{DEDateHired.date().month()},{DEDateHired.date().day()}")

            try:

                cursor = con.cursor()
                query1 = "INSERT INTO employees(Last_name, First_name, MI, Sex, Birthday, Age, Contact_Number, Status, Address, Work_Status, Date_Hired, Job_Position, Image, Suffix, Nationality,Designated,Current_Site) VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)"

                query5 = (LELastName.text(),LEFirstName.text(),LEMI.text(),CbSex.currentText(),bday,LEAge.text(),LEContact.text(),CbStatus.currentText(),
                         EAddress.text(),CbWorkStatus.currentText(),dhired,CbJobPosition.currentText(),pixmap_bytes,suffix,CbNationality.currentText(),"No","None")

                cursor.execute(query1,query5)
                con.commit()

                Ui_Activity.record_activity("admin",f"Add Employee Information")

                msgBox = QMessageBox()
                msgBox.setIcon(QMessageBox.Information)
                msgBox.setText("Employee was added successfully")
                msgBox.setWindowTitle("Message Alert")
                msgBox.setStandardButtons(QMessageBox.Ok)
                msgBox.buttonClicked.connect(msgBox.close)

                returnValue = msgBox.exec()
                if returnValue == QMessageBox.Ok:
                    Ui_EmployeeForm.DisplayGroup2.hide()
                    Ui_EmployeePage.get_employee(Ui_EmployeePage.employee_item)
                    Ui_EmployeeForm.updateReset(LELastName, LEFirstName, LEMI, LEAge, LEContact, EAddress
                                                , DEBirthday, DEDateHired, CbStatus, CbWorkStatus,
                                                CbJobPosition, LBImageContainer, LESuffix, CbSex, CbNationality)


                else:
                    Ui_EmployeeForm.DisplayGroup2.hide()

            except :
                Dialog.msg_dialog(str(sys.exc_info()))  



    def setAge(DEBirthday,LBAge):
        try:
            cdate = QDate.currentDate()
            bday = DEBirthday.date()
            x = bday.year()

            if (cdate.month()>=bday.month()) & (cdate.day()>=bday.day()):
                temp = cdate.addYears(-x)
                LBAge.setText(str(temp.year()))

            else:
                temp = cdate.addYears(-x-1)
                LBAge.setText(str(temp.year()))


        except:
            Dialog.msg_dialog(str(sys.exc_info()))  




    def openImage(centralwidget,label):

        imagePath, _ = QFileDialog.getOpenFileName(centralwidget, "openImage", '', "Image Files (*.jpg *.png)")
        if len(str(imagePath)) > 0:
            image = QImage(imagePath)

            pixmap = QPixmap.fromImage(image)
            pixmap5 = pixmap.scaled(label.width(), label.height())

            label.setPixmap(pixmap5)

            label.setStyleSheet("border-radius:8px;\n"
                    "font-size:16px;\n"
                    "padding-left:0px;\n"
                    "border:1px solid black;")
            label.setText("")

    def updateReset(LELastName,LEFirstName,LEMI,LEAge,LEContact,LEAddress,
        DEBirthday,DEDateHired,CbStatus,CbWorkStatus,CbJobPosition,LBImageContainer,LESuffix,CbSex,CbNationality):

                LELastName.setText("")
                LEFirstName.setText("")
                LEMI.setText("")
                LEContact.setText("")
                LEAddress.setText("")
                d = QDate(2000, 1, 1)
                DEBirthday.setDate(d)
                now = QDate.currentDate()
                DEDateHired.setDate(now)
                CbStatus.setCurrentIndex(0)
                CbWorkStatus.setCurrentIndex(0)
                CbJobPosition.setCurrentIndex(0)
                LBImageContainer.setStyleSheet("color: rgb(255, 255, 255);\n"
                                               "background-color: rgb(0, 0, 0,.4);\n"
                                               "border-radius:8px;\n"
                                               "font-size:16px;\n"
                                               "padding-left:40px;\n"
                                               "border:1px solid black;")
                LBImageContainer.setText("Image")
                LEAge.setText("")
                LESuffix.setText("")
                CbSex.setCurrentIndex(0)
                CbNationality.setCurrentText("Filipino")


    def clearForm(LELastName,LEFirstName,LEMI,LEAge,LEContact,LEAddress,LECurrentSite,
        DEBirthday,DEDateHired,CbStatus,CbWorkStatus,CbJobPosition,LBImageContainer,LESuffix,CbSex,CbNationality):

        msgBox = QMessageBox()
        msgBox.setIcon(QMessageBox.Information)
        msgBox.setText("Are you sure you want to clear")
        msgBox.setWindowTitle("Message Alert")
        msgBox.setStandardButtons(QMessageBox.Ok | QMessageBox.Cancel)
        msgBox.buttonClicked.connect(msgBox.close)

        returnValue = msgBox.exec()
        if returnValue == QMessageBox.Ok:
            try:
                LELastName.setText("")
                LEFirstName.setText("")
                LEMI.setText("")
                LEContact.setText("")
                LEAddress.setText("")
                LECurrentSite.setText("")
                d = QDate(2000, 1, 1)
                DEBirthday.setDate(d)
                now = QDate.currentDate()
                DEDateHired.setDate(now)
                CbStatus.setCurrentIndex(0)
                CbWorkStatus.setCurrentIndex(0)
                CbJobPosition.setCurrentIndex(0)
                LBImageContainer.setStyleSheet("color: rgb(255, 255, 255);\n"
                                               "background-color: rgb(0, 0, 0,.4);\n"
                                               "border-radius:8px;\n"
                                               "font-size:16px;\n"
                                               "padding-left:40px;\n"
                                               "border:1px solid black;")
                LBImageContainer.setText("Image")
                LEAge.setText("")
                LESuffix.setText("")
                CbSex.setCurrentIndex(0)
                CbNationality.setCurrentText("Filipino")
                d = QDate(1999, 1, 1)
                DEBirthday.setDate(d)
            except:
                Dialog.msg_dialog(str(sys.exc_info()))  


    def showForm():
        Ui_EmployeeForm.DisplayGroup2.show()
        Ui_EmployeeForm.getPreIndex()
        d = QDate(1999, 1, 1)
        Ui_EmployeeForm.DEBirthday.setDate(d)




    def hideForm(LELastName, LEFirstName, LEMI, LEAge, LEContact, LEAddress,LECurrentSite, DEBirthday, DEDateHired, CbStatus, CbWorkStatus,CbJobPosition, LBImageContainer,LESuffix,CbSex,CbNationality):

        msgBox = QMessageBox()
        msgBox.setIcon(QMessageBox.Information)
        msgBox.setText("Are you sure you want to Cancel?")
        msgBox.setWindowTitle("Message Alert")
        msgBox.setStandardButtons(QMessageBox.Ok | QMessageBox.Cancel)
        msgBox.buttonClicked.connect(msgBox.close)

        returnValue = msgBox.exec()
        if returnValue == QMessageBox.Ok:
            Ui_EmployeeForm.updateReset(LELastName, LEFirstName, LEMI, LEAge, LEContact, LEAddress
                                                    , DEBirthday, DEDateHired, CbStatus, CbWorkStatus,
                                                    CbJobPosition, LBImageContainer,LESuffix,CbSex,CbNationality)
            Ui_EmployeeForm.DisplayGroup2.hide()

    def addnationality(_translate,CbNationality):
        y=0
        for x in nationality:
            CbNationality.addItem("")
            CbNationality.setItemText(y, _translate("DashbaordWindow", x))
            y += 1

        CbNationality.setCurrentText('Filipino')

    def getPreIndex():
        cursor = con.cursor()
        query="SELECT AUTO_INCREMENT FROM information_schema.TABLES WHERE TABLE_SCHEMA = 'rms' AND TABLE_NAME = 'employees'"
        cursor.execute(query)
        res = cursor.fetchall()

        d = QDate.currentDate()
        a=str(res).replace("[(","")
        b=a.replace(",)]","")
        Ui_EmployeeForm.LbID.setText(f"ID : {d.year()}00{b}")



    def employee_page_form(DashbaordWindow):

        Ui_EmployeeForm.DisplayGroup2 = QtWidgets.QGroupBox(DashbaordWindow)
        Ui_EmployeeForm.DisplayGroup2.setGeometry(QtCore.QRect(0, 0, 1230, 703))
        Ui_EmployeeForm.DisplayGroup2.setStyleSheet("\n""")
        Ui_EmployeeForm.DisplayGroup2.setTitle("")
        Ui_EmployeeForm.DisplayGroup2.setObjectName("DisplayGroup")
        Ui_EmployeeForm.DisplayGroup2.hide()

        #Adds
        Bg = QtWidgets.QLabel(Ui_EmployeeForm.DisplayGroup2)
        Bg.setEnabled(True)
        Bg.setGeometry(QtCore.QRect(0, 0, 1230, 703))
        Bg.setMinimumSize(QtCore.QSize(1230, 703))
        Bg.setMaximumSize(QtCore.QSize(1230, 703))
        Bg.setStyleSheet("background-color: rgb(0, 0, 0,.9);")

        DisplayGroup = QtWidgets.QGroupBox(Ui_EmployeeForm.DisplayGroup2)
        DisplayGroup.setGeometry(QtCore.QRect(300, 140, 730, 490))
        DisplayGroup.setStyleSheet(".QLabel{color:white;}\n"
                                   ".QPushButton{color:white;}\n"
                                   ".QGroupBox{border:none;}")
        DisplayGroup.setTitle("")
        DisplayGroup.setObjectName("DisplayGroup")


        #Continue
        DisplayGroupBG = QtWidgets.QLabel(DisplayGroup)
        DisplayGroupBG.setGeometry(QtCore.QRect(0, 0, 730, 490))
        DisplayGroupBG.setStyleSheet("color: rgb(255, 255, 255);\n"
        "background-color: rgb(148, 0, 2,.3);\n"
        "border-radius:10px;border: 2px solid white; ")
        DisplayGroupBG.setText("")
        DisplayGroupBG.setObjectName("DisplayGroupBG")

        LELastName = QtWidgets.QLineEdit(DisplayGroup)
        LELastName.setGeometry(QtCore.QRect(450, 80, 161, 31))
        LELastName.setStyleSheet("background-color: rgba(255, 255, 255);\n"
                                 "border-radius:5px;")
        LELastName.setObjectName("LELastName")
        LEFirstName = QtWidgets.QLineEdit(DisplayGroup)
        LEFirstName.setGeometry(QtCore.QRect(190, 80, 181, 31))
        LEFirstName.setStyleSheet("background-color: rgba(255, 255, 255);\n"
                                  "border-radius:5px;")
        LEFirstName.setObjectName("LEFirstName")
        LBImageContainer = QtWidgets.QLabel(DisplayGroup)
        LBImageContainer.setGeometry(QtCore.QRect(20, 70, 131, 131))
        LBImageContainer.setStyleSheet("color: rgb(255, 255, 255);\n"
                                       "background-color: rgb(0, 0, 0,.4);\n"
                                       "border-radius:8px;\n"
                                       "font-size:16px;\n"
                                       "padding-left:40px;\n"
                                       "border:1px solid black;")
        LBImageContainer.setObjectName("LBImageContainer")
        LEMI = QtWidgets.QLineEdit(DisplayGroup)
        LEMI.setGeometry(QtCore.QRect(380, 80, 61, 31))
        LEMI.setStyleSheet("background-color: rgba(255, 255, 255);\n"
                           "border-radius:5px;")
        LEMI.setObjectName("LEMI")
        Ui_EmployeeForm.DEBirthday = QtWidgets.QDateEdit(DisplayGroup)
        Ui_EmployeeForm.DEBirthday.setGeometry(QtCore.QRect(190, 150, 181, 31))
        Ui_EmployeeForm.DEBirthday.setStyleSheet("color:maroon;\n"
                                 "background-color:rgb(255, 255, 255);\n"
                                 "border-radius:5px;")
        Ui_EmployeeForm.DEBirthday.setCalendarPopup(True)
        Ui_EmployeeForm.DEBirthday.setObjectName("DEBirthday")
        CbStatus = QtWidgets.QComboBox(DisplayGroup)
        CbStatus.setGeometry(QtCore.QRect(350, 230, 150, 31))
        CbStatus.setStyleSheet("color: rgb(255, 255, 255);\n"
                               "background-color: rgb(255,255,255,.2);\n"
                               "font-size:15px;\n"
                               "border-radius:5px;")
        CbStatus.setObjectName("CbStatus")
        CbStatus.addItem("")
        CbStatus.addItem("")
        CbStatus.addItem("")
        CbStatus.addItem("")
        LEAge = QtWidgets.QLineEdit(DisplayGroup)
        LEAge.setGeometry(QtCore.QRect(390, 150, 101, 31))
        LEAge.setStyleSheet("background-color: rgba(255, 255, 255);\n"
                            "border-radius:5px;")
        LEAge.setReadOnly(True)
        LEAge.setObjectName("LEAge")
        LEAddress = QtWidgets.QLineEdit(DisplayGroup)
        LEAddress.setGeometry(QtCore.QRect(190, 300, 500, 31))
        LEAddress.setStyleSheet("background-color: rgba(255, 255, 255);\n"
                                "border-radius:5px;")
        LEAddress.setObjectName("LEAddress")
        CbWorkStatus = QtWidgets.QComboBox(DisplayGroup)
        CbWorkStatus.setGeometry(QtCore.QRect(560, 370, 131, 31))
        CbWorkStatus.setStyleSheet("color: rgb(255, 255, 255);\n"
                                   "background-color: rgb(255,255,255,.2);\n"
                                   "font-size:15px;\n"
                                   "border-radius:5px;")
        CbWorkStatus.setObjectName("CbWorkStatus")
        CbWorkStatus.addItem("")
        CbWorkStatus.addItem("")
        LECurrentSite = QtWidgets.QLineEdit(DisplayGroup)
        LECurrentSite.setEnabled(True)
        LECurrentSite.setGeometry(QtCore.QRect(190, 440, 500, 31))
        LECurrentSite.setAcceptDrops(False)
        LECurrentSite.setStyleSheet("background-color: rgba(255, 255, 255);\n"
                                    "border-radius:5px;")
        LECurrentSite.setText("")
        LECurrentSite.setObjectName("LECurrentSite")
        Upload = QtWidgets.QPushButton(DisplayGroup)
        Upload.setGeometry(QtCore.QRect(20, 220, 130, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        Upload.setFont(font)
        Upload.setLayoutDirection(QtCore.Qt.LeftToRight)
        Upload.setStyleSheet("background-color: rgba(0, 0, 0,0.9);\n"
                             "border-radius:5px;")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/Assets/UploadIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Upload.setIcon(icon)
        Upload.setObjectName("Upload")
        LbLastname = QtWidgets.QLabel(DisplayGroup)
        LbLastname.setGeometry(QtCore.QRect(450, 60, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        LbLastname.setFont(font)
        LbLastname.setObjectName("LbLastname")
        LbFirstname = QtWidgets.QLabel(DisplayGroup)
        LbFirstname.setGeometry(QtCore.QRect(190, 60, 111, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        LbFirstname.setFont(font)
        LbFirstname.setObjectName("LbFirstname")
        LbMi = QtWidgets.QLabel(DisplayGroup)
        LbMi.setGeometry(QtCore.QRect(380, 60, 31, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        LbMi.setFont(font)
        LbMi.setObjectName("LbMi")
        LbSex = QtWidgets.QLabel(DisplayGroup)
        LbSex.setGeometry(QtCore.QRect(190, 210, 47, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        LbSex.setFont(font)
        LbSex.setObjectName("LbSex")
        LbBirthday = QtWidgets.QLabel(DisplayGroup)
        LbBirthday.setGeometry(QtCore.QRect(190, 130, 151, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        LbBirthday.setFont(font)
        LbBirthday.setObjectName("LbBirthday")
        LbStatus = QtWidgets.QLabel(DisplayGroup)
        LbStatus.setGeometry(QtCore.QRect(350, 210, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        LbStatus.setFont(font)
        LbStatus.setObjectName("LbStatus")
        LbAddress = QtWidgets.QLabel(DisplayGroup)
        LbAddress.setGeometry(QtCore.QRect(190, 280, 161, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        LbAddress.setFont(font)
        LbAddress.setObjectName("LbAddress")
        LbWorkStatus = QtWidgets.QLabel(DisplayGroup)
        LbWorkStatus.setGeometry(QtCore.QRect(560, 350, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        LbWorkStatus.setFont(font)
        LbWorkStatus.setObjectName("LbWorkStatus")
        LbJobPosition = QtWidgets.QLabel(DisplayGroup)
        LbJobPosition.setGeometry(QtCore.QRect(360, 350, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        LbJobPosition.setFont(font)
        LbJobPosition.setObjectName("LbJobPosition")
        LbHiredDate = QtWidgets.QLabel(DisplayGroup)
        LbHiredDate.setGeometry(QtCore.QRect(190, 350, 151, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        LbHiredDate.setFont(font)
        LbHiredDate.setObjectName("LbHiredDate")
        LbContact = QtWidgets.QLabel(DisplayGroup)
        LbContact.setGeometry(QtCore.QRect(510, 130, 121, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        LbContact.setFont(font)
        LbContact.setObjectName("LbContact")
        LbAge = QtWidgets.QLabel(DisplayGroup)
        LbAge.setGeometry(QtCore.QRect(390, 130, 47, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        LbAge.setFont(font)
        LbAge.setObjectName("LbAge")
        LbCurrent = QtWidgets.QLabel(DisplayGroup)
        LbCurrent.setGeometry(QtCore.QRect(190, 420, 171, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        LbCurrent.setFont(font)
        LbCurrent.setObjectName("LbCurrent")
        Ui_EmployeeForm.LbID = QtWidgets.QLabel(DisplayGroup)
        Ui_EmployeeForm.LbID.setGeometry(QtCore.QRect(30, 40, 111, 25))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        Ui_EmployeeForm.LbID.setFont(font)
        Ui_EmployeeForm.LbID.setObjectName("LbID")
        DEDateHired = QtWidgets.QDateEdit(DisplayGroup)
        DEDateHired.setGeometry(QtCore.QRect(190, 370, 151, 31))
        DEDateHired.setStyleSheet("color:maroon;;\n"
                                  "background-color:rgb(255, 255, 255);\n"
                                  "border-radius:5px;")
        DEDateHired.setCalendarPopup(True)
        DEDateHired.setObjectName("DEDateHired")
        CbJobPosition = QtWidgets.QComboBox(DisplayGroup)
        CbJobPosition.setGeometry(QtCore.QRect(360, 370, 181, 31))
        CbJobPosition.setStyleSheet("color: rgb(255, 255, 255);\n"
                                    "background-color: rgb(255,255,255,.2);\n"
                                    "font-size:15px;\n"
                                    "border-radius:5px;")
        CbJobPosition.setObjectName("CbJobPosition")
        CbJobPosition.addItem("")
        CbJobPosition.addItem("")
        CbJobPosition.addItem("")
        CbJobPosition.addItem("")
        CbJobPosition.addItem("")
        CbJobPosition.addItem("")
        CbJobPosition.addItem("")
        CbJobPosition.addItem("")
        Prenumber = QtWidgets.QLabel(DisplayGroup)
        Prenumber.setGeometry(QtCore.QRect(510, 148, 31, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        Prenumber.setFont(font)
        Prenumber.setObjectName("Prenumber")
        LESuffix = QtWidgets.QLineEdit(DisplayGroup)
        LESuffix.setGeometry(QtCore.QRect(620, 80, 71, 31))
        LESuffix.setStyleSheet("background-color: rgba(255, 255, 255);\n"
                               "border-radius:5px;")
        LESuffix.setObjectName("LESuffix")
        LbSuffix = QtWidgets.QLabel(DisplayGroup)
        LbSuffix.setGeometry(QtCore.QRect(620, 60, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        LbSuffix.setFont(font)
        LbSuffix.setObjectName("LbSuffix")
        CbSex = QtWidgets.QComboBox(DisplayGroup)
        CbSex.setGeometry(QtCore.QRect(190, 230, 141, 31))
        CbSex.setStyleSheet("color: rgb(255, 255, 255);\n"
                            "background-color: rgb(255,255,255,.2);\n"
                            "font-size:15px;\n"
                            "border-radius:5px;")
        CbSex.setObjectName("CbSex")
        CbSex.addItem("")
        CbSex.addItem("")
        CbNationality = QtWidgets.QComboBox(DisplayGroup)
        CbNationality.setGeometry(QtCore.QRect(520, 230, 171, 31))
        CbNationality.setStyleSheet("border-radius:5px;color: rgb(255, 255, 255);\n"
                                    "background-color: rgb(255,255,255,.2);\n"
                                    "font-size:15px;")
        CbNationality.setObjectName("CbNationality")
        CbNationality.addItem("")
        LbNationality = QtWidgets.QLabel(DisplayGroup)
        LbNationality.setGeometry(QtCore.QRect(520, 210, 151, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        LbNationality.setFont(font)
        LbNationality.setObjectName("LbNationality")
        LEContact = QtWidgets.QLineEdit(DisplayGroup)
        LEContact.setGeometry(QtCore.QRect(540, 150, 151, 31))
        LEContact.setStyleSheet("background-color: rgba(255, 255, 255);\n"
                                "border-radius:5px;")
        LEContact.setObjectName("LEContact")
        BtnCancel = QtWidgets.QPushButton(DisplayGroup)
        BtnCancel.setGeometry(QtCore.QRect(20, 430, 130, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        BtnCancel.setFont(font)
        BtnCancel.setLayoutDirection(QtCore.Qt.LeftToRight)
        BtnCancel.setStyleSheet("background-color: rgba(0, 0, 0,0.9);\n"
                            "border-radius:5px;")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icons/Assets/FormCancelIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        BtnCancel.setIcon(icon1)
        BtnCancel.setIconSize(QtCore.QSize(30, 30))
        BtnCancel.setObjectName("BtnCa")


        DisplayGroupBG = QtWidgets.QLabel(DisplayGroup)
        DisplayGroupBG.setGeometry(QtCore.QRect(0, 0, 731, 500))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        DisplayGroupBG.setFont(font)
        DisplayGroupBG.setLayoutDirection(QtCore.Qt.LeftToRight)
        DisplayGroupBG.setStyleSheet("color: rgb(255, 255, 255);\n"
                                     "background-color: rgb(148, 0, 2,.4);\n"
                                     "border-radius:10px;")
        DisplayGroupBG.setFrameShadow(QtWidgets.QFrame.Plain)
        DisplayGroupBG.setLineWidth(0)
        DisplayGroupBG.setText("")
        DisplayGroupBG.setObjectName("DisplayGroupBG")
        BtnSubmit = QtWidgets.QPushButton(DisplayGroup)
        BtnSubmit.setGeometry(QtCore.QRect(20, 390, 130, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        BtnSubmit.setFont(font)
        BtnSubmit.setLayoutDirection(QtCore.Qt.LeftToRight)
        BtnSubmit.setStyleSheet("background-color: rgba(0, 0, 0,0.9);\n"
                                "border-radius:5px;")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Icons/Assets/FormSubmitIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        BtnSubmit.setIcon(icon2)
        BtnSubmit.setIconSize(QtCore.QSize(30, 30))
        BtnSubmit.setObjectName("BtnSubmit")
        BtnClear = QtWidgets.QPushButton(DisplayGroup)
        BtnClear.setGeometry(QtCore.QRect(20, 290, 130, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        BtnClear.setFont(font)
        BtnClear.setLayoutDirection(QtCore.Qt.LeftToRight)
        BtnClear.setStyleSheet("background-color: rgba(0, 0, 0,0.9);\n"
                               "border-radius:5px;")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Icons/Assets/FormClearIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        BtnClear.setIcon(icon3)
        BtnClear.setIconSize(QtCore.QSize(30, 30))
        BtnClear.setObjectName("BtnClear")
        BtnClear.setObjectName("BtnClear")

        label = QtWidgets.QLabel(DisplayGroup)
        label.setGeometry(QtCore.QRect(230, 5, 271, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        label.setFont(font)
        label.setStyleSheet("background:transparent;color: rgb(255, 255, 255);")
        label.setObjectName("label")



        DisplayGroupBG.raise_()
        LELastName.raise_()
        LBImageContainer.raise_()
        LEMI.raise_()
        Ui_EmployeeForm.DEBirthday.raise_()
        CbStatus.raise_()
        LEAge.raise_()
        LEAddress.raise_()
        CbWorkStatus.raise_()
        LECurrentSite.raise_()
        Upload.raise_()
        LbLastname.raise_()
        LbFirstname.raise_()
        LbMi.raise_()
        LbSex.raise_()
        LbBirthday.raise_()
        LbStatus.raise_()
        LbAddress.raise_()
        LbWorkStatus.raise_()
        LbJobPosition.raise_()
        LbHiredDate.raise_()
        LbContact.raise_()
        LbAge.raise_()
        LbCurrent.raise_()
        Ui_EmployeeForm.LbID.raise_()
        DEDateHired.raise_()
        CbJobPosition.raise_()
        Prenumber.raise_()
        LESuffix.raise_()
        LbSuffix.raise_()
        CbSex.raise_()
        CbNationality.raise_()
        LbNationality.raise_()
        LEContact.raise_()
        BtnCancel.raise_()
        LEFirstName.raise_()
        BtnSubmit.raise_()
        BtnClear.raise_()
        label.raise_()

        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(-1)

        LELastName.setFont(font)
        LEFirstName.setFont(font)
        LEMI.setFont(font)
        LEAge.setFont(font)
        LEContact.setFont(font)
        LEAddress.setFont(font)
        Ui_EmployeeForm.DEBirthday.setFont(font)
        DEDateHired.setFont(font)
        CbStatus.setFont(font)
        CbWorkStatus.setFont(font)
        CbJobPosition.setFont(font)
        LBImageContainer.setFont(font)
        LESuffix.setFont(font)
        CbSex.setFont(font)
        CbNationality.setFont(font)

        CbSex.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        CbNationality.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        CbStatus.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        CbWorkStatus.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        CbJobPosition.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))

        _translate = QtCore.QCoreApplication.translate
        LELastName.setPlaceholderText(_translate("EmployeeForm", "Last Name"))

        LEFirstName.setPlaceholderText(_translate("EmployeeForm", "First Name"))
        LBImageContainer.setText(_translate("EmployeeForm", "Image"))
        LEMI.setPlaceholderText(_translate("EmployeeForm", "M.I."))
        Ui_EmployeeForm.DEBirthday.setDisplayFormat(_translate("EmployeeForm", "MMM d  yyyy"))
        CbStatus.setItemText(0, _translate("EmployeeForm", "Single"))
        CbStatus.setItemText(1, _translate("EmployeeForm", "Married"))
        CbStatus.setItemText(2, _translate("EmployeeForm", "Widowed"))
        CbStatus.setItemText(3, _translate("EmployeeForm", "Divorced"))
        LEAge.setPlaceholderText(_translate("EmployeeForm", "Age"))
        LEAddress.setPlaceholderText(_translate("EmployeeForm", "Complete Address"))
        CbWorkStatus.setItemText(0, _translate("EmployeeForm", "Active"))
        CbWorkStatus.setItemText(1, _translate("EmployeeForm", "Inactive"))
        LECurrentSite.setPlaceholderText(_translate("EmployeeForm", "Current Site Designation"))
        Upload.setText(_translate("EmployeeForm", "  Upload"))
        LbLastname.setText(_translate("EmployeeForm", "Last Name"))
        LbFirstname.setText(_translate("EmployeeForm", "First Name"))
        LbMi.setText(_translate("EmployeeForm", "M.I"))
        LbSex.setText(_translate("EmployeeForm", "Sex"))
        LbBirthday.setText(_translate("EmployeeForm", "Date of Birth"))
        LbStatus.setText(_translate("EmployeeForm", "Civil Status"))
        LbAddress.setText(_translate("EmployeeForm", "Complete Address"))
        LbWorkStatus.setText(_translate("EmployeeForm", "Work Status"))
        LbJobPosition.setText(_translate("EmployeeForm", "Job Position"))
        LbHiredDate.setText(_translate("EmployeeForm", "Date Hired"))
        LbContact.setText(_translate("EmployeeForm", "Contact Number"))
        LbAge.setText(_translate("EmployeeForm", "Age"))
        LbCurrent.setText(_translate("EmployeeForm", "Current Site Designation"))
        Ui_EmployeeForm.LbID.setText(_translate("EmployeeForm", "ID"))
        DEDateHired.setDisplayFormat(_translate("EmployeeForm", "MMM d  yyyy"))
        CbJobPosition.setItemText(0, _translate("EmployeeForm", "General Manager"))
        CbJobPosition.setItemText(1, _translate("EmployeeForm", "Purchaser"))
        CbJobPosition.setItemText(2, _translate("EmployeeForm", "Supervisor"))
        CbJobPosition.setItemText(3, _translate("EmployeeForm", "Warehouseman"))
        CbJobPosition.setItemText(4, _translate("EmployeeForm", "Leanman"))
        CbJobPosition.setItemText(5, _translate("EmployeeForm", "Helper"))
        CbJobPosition.setItemText(6, _translate("EmployeeForm", "Installer"))
        CbJobPosition.setItemText(7, _translate("EmployeeForm", "AC Tech"))
        Prenumber.setText(_translate("EmployeeForm", "+63"))
        LESuffix.setPlaceholderText(_translate("EmployeeForm", "Suffix"))
        LbSuffix.setText(_translate("EmployeeForm", "Suffix"))
        CbSex.setItemText(0, _translate("EmployeeForm", "Male"))
        CbSex.setItemText(1, _translate("EmployeeForm", "Female"))
        CbNationality.setItemText(0, _translate("EmployeeForm", "Filipino"))
        LbNationality.setText(_translate("EmployeeForm", "Nationality"))
        LEContact.setPlaceholderText(_translate("EmployeeForm", "9xxxxxxxxx"))
        BtnCancel.setText(_translate("EmployeeForm", "         Cancel"))
        BtnSubmit.setText(_translate("EmployeeForm", "        Submit"))
        BtnClear.setText(_translate("EmployeeForm", "           Clear"))
        label.setText(_translate("EmployeeForm", "Add Employee Form"))

        #Addition
        LEAge.setEnabled(False)
        now = QDate.currentDate()
        DEDateHired.setDate(now)

        LELastName.setMaxLength(25)
        LEFirstName.setMaxLength(25)
        LEMI.setMaxLength(1)
        LEContact.setMaxLength(10)
        LEAddress.setMaxLength(100)
        LECurrentSite.setMaxLength(50)

        my_regex = QtCore.QRegExp("^[0-9]*$")
        my_validator = QtGui.QRegExpValidator(my_regex, LEContact)
        LEContact.setValidator(my_validator)

        #Functions

        Ui_EmployeeForm.DEBirthday.dateChanged.connect(lambda: Ui_EmployeeForm.setAge(Ui_EmployeeForm.DEBirthday,LEAge))
        d = QDate(1999, 1, 1)
        Ui_EmployeeForm.DEBirthday.setDate(d)




        Upload.clicked.connect(lambda :Ui_EmployeeForm.openImage(DashbaordWindow,LBImageContainer))

        BtnSubmit.clicked.connect(lambda :Ui_EmployeeForm.submitForm(LELastName,LEFirstName,LEMI,LEAge,LEContact,
        LEAddress,Ui_EmployeeForm.DEBirthday,DEDateHired,CbStatus,CbWorkStatus,CbJobPosition,LBImageContainer,LESuffix,CbSex,CbNationality ))

        BtnCancel.clicked.connect(lambda :Ui_EmployeeForm.hideForm(LELastName,LEFirstName,LEMI,LEAge,LEContact,LEAddress,
        LECurrentSite,Ui_EmployeeForm.DEBirthday,DEDateHired,CbStatus,CbWorkStatus,CbJobPosition,LBImageContainer,LESuffix,CbSex,CbNationality))

        BtnClear.clicked.connect(lambda :Ui_EmployeeForm.clearForm(LELastName,LEFirstName,LEMI,LEAge,LEContact,LEAddress,
        LECurrentSite,Ui_EmployeeForm.DEBirthday,DEDateHired,CbStatus,CbWorkStatus,CbJobPosition,LBImageContainer,LESuffix,CbSex,CbNationality))


        LECurrentSite.hide()
        LbCurrent.hide()
        #LB Functions

        LELastName.textEdited.connect(lambda: Ui_EmployeeForm.keyPressEvent(LELastName))
        LEFirstName.textEdited.connect(lambda: Ui_EmployeeForm.keyPressEvent(LEFirstName))
        LEMI.textEdited.connect(lambda: Ui_EmployeeForm.keyPressEvent(LEMI))
        LEAddress.textEdited.connect(lambda: Ui_EmployeeForm.keyPressEvent(LEAddress))
        LECurrentSite.textEdited.connect(lambda: Ui_EmployeeForm.keyPressEvent(LECurrentSite))

        # Nationality
        Ui_EmployeeForm.addnationality(_translate,CbNationality)






