# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'project_employee_page1.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys


import mysql
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QDate
from PyQt5.QtGui import QColor
from PyQt5.QtWidgets import QMessageBox
from db import con
from project_dtr import Ui_DTR,Ui_Payroll
from project_transaction import Ui_Trans
from project_summary import Ui_Summary
from dialogs import Dialog
from project_activity import Ui_Activity


class Ui_PE(object):
	ProjectTab=""
	BtnBack=""
	projectid=0
	BtnDtr=""
	BtnPayroll=""
	BtnTransaction=""
	BtnSummary=""

	BtnEditSalary=""
	BtnSaveSalary=""
	BtnCancelSalary=""

	BtnEditAllow=""
	BtnSaveAllow=""
	BtnCancelAllow=""
	BtnAddAllow=""

	BtnEditCash=""
	BtnSaveCash= ""
	BtnCancelCash=""
	BtnAddCash=""
	BtnLessCash=""

	BtnRemoveEmployee=""
	BtnAddEmployee=""

	BtnRemoveCash=""
	BtnRemoveAllow=""

	Allowid=0
	Cashid=0

	PEList=""

	employee_id = []
	employee_fname = []
	employee_lname = []
	employee_mname = []
	employee_position = []

	LEName = ""
	LEBday = ""
	LEAge = ""
	LESex = ""
	LEContact = ""
	LEJob = ""

	LBName=""
	LBBday=""
	LBAge=""
	LBSex=""
	LBContact=""
	LBJob=""
	ImgEmployee=""
	LBRate=""


	LERate=""
	DateWorkStart=""
	DateWorkEnd=""

	itemid=0

	TBLAllowance=""
	TBLCash=""

	# Table Date & LE
	TBADates=[]
	TBCDates=[]
	TBALE=[]
	TBCLE=[]


	TBAid=[]
	TBCid=[]
	LBProjectTitle=""

	# status
	editable = QtCore.Qt.ItemIsSelectable | QtCore.Qt.ItemIsEnabled | QtCore.Qt.ItemIsEditable
	not_editable = QtCore.Qt.ItemIsSelectable | QtCore.Qt.ItemIsEnabled 

	def setProjectTitle():
		try:
			cursor = con.cursor()
			cursor.execute(f"SELECT * FROM `projects` WHERE `project_id` = {Ui_PE.projectid}")
			res = cursor.fetchall()
			Ui_PE.LBProjectTitle.setText(res[0][1])

		except:
			Ui_PEForm.show_dialog(str(sys.exc_info()))

	def showpage(page):
		Ui_PE.StackProject.setCurrentWidget(page)
	def showdtr(page):
		Ui_PE.StackProject.setCurrentWidget(page)
		Ui_DTR.projectid=Ui_PE.projectid
		# Insert Items(Week) at DTR List (Default Values)
		Ui_DTR.insert_week()
		
	def showpayroll(page):
		Ui_PE.StackProject.setCurrentWidget(page)
		Ui_DTR.projectid=Ui_PE.projectid
		Ui_DTR.insert_week()
		Ui_Payroll.insert_week()
		Ui_Payroll.resetTable()

	def showtrans(page):
		Ui_Trans.project_id=Ui_PE.projectid
		Ui_Trans.projectName=Ui_PE.LBProjectTitle.text()

		Ui_PE.StackProject.setCurrentWidget(page)
		# Insert Data in Transaction Table
		Ui_Trans.insert_trans(Ui_Trans.not_editable,False) # Default Cell non editable

	def showsummary(page):
		Ui_PE.StackProject.setCurrentWidget(page)
		Ui_Summary.project_id=Ui_PE.projectid
		Ui_Summary.get_summary()


	
	
	def getAllowance(table,status,edit_status):

		#Font for Input
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(12)
		# Regex
		my_regex = QtCore.QRegExp("^\\d{1,6}(\\.\\d{1,2})?$")

		try:
			# Identify Start End Date
			cursor = con.cursor()
			query = f"SELECT * FROM `projects` WHERE `project_id`={Ui_PE.projectid}"
			cursor.execute(query)
			res = cursor.fetchall()
			d1=""
			d2=""
			for x in res:
				d1=x[4]
				d2=x[5]
			# process date
			startdate = QDate(Ui_PE.process_date(d1))
			enddate = QDate(Ui_PE.process_date(d2))

			# Select Balance
			cursor = con.cursor()
			cursor.execute(f"SELECT * FROM `projecte_balance` WHERE `employee_id` = {Ui_PE.itemid} AND `project_id`={Ui_PE.projectid} AND `title`='Add Allowance'")
			res = cursor.fetchall()
			row=0
			while (table.rowCount() > 0):
				table.removeRow(0)
			table.setRowCount(len(res))
			Ui_PE.TBADates=[]
			Ui_PE.TBAid=[]

			for x in res:

				Ui_PE.TBAid.append(x[0])

				#LEReceipt
				LEAllow = QtWidgets.QLineEdit(Ui_Trans.TBLTrans)
				LEAllow.setGeometry(QtCore.QRect(0, 0, 100, 31))
				LEAllow.setAlignment(QtCore.Qt.AlignCenter)
				LEAllow.setStyleSheet("color:white;")
				LEAllow.setObjectName("LEAllow")
				LEAllow.setText(str(x[5]))
				LEAllow.setEnabled(edit_status)
				LEAllow.setAlignment(QtCore.Qt.AlignCenter)
				LEAllow.setFont(font)

				my_validator = QtGui.QRegExpValidator(my_regex,LEAllow)
				LEAllow.setValidator(my_validator)

				table.setCellWidget(row, 0, LEAllow)

				DateAllow = QtWidgets.QDateEdit(table)
				DateAllow.setCalendarPopup(True)
				DateAllow.setDate(Ui_PE.process_date(x[4]))
				DateAllow.setEnabled(edit_status) 
				DateAllow.setFont(font)
				DateAllow.setAlignment(QtCore.Qt.AlignCenter)
				Ui_PE.TBADates.append(DateAllow)
				table.setCellWidget(row, 1, Ui_PE.TBADates[row])

				# set min max
				DateAllow.setMinimumDate(startdate)
				DateAllow.setMaximumDate(enddate)

				row=row+1


		except:
			Ui_PEForm.show_dialog(str(sys.exc_info()))

	def getCashAdvance(table,status,edit_status):

		#Font for Input
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(12)
		# Regex
		less_regex = QtCore.QRegExp("^\\-\\d{1,6}(\\.\\d{1,2})?$")
		my_regex = QtCore.QRegExp("^\\d{1,6}(\\.\\d{1,2})?$")
		try:

			# Identify Start End Date
			cursor = con.cursor()
			query = f"SELECT * FROM `projects` WHERE `project_id`={Ui_PE.projectid}"
			cursor.execute(query)
			res = cursor.fetchall()
			d1=""
			d2=""
			for x in res:
				d1=x[4]
				d2=x[5]
			# process date
			startdate = QDate(Ui_PE.process_date(d1))
			enddate = QDate(Ui_PE.process_date(d2))

			# Select Project Balance
			cursor = con.cursor()
			cursor.execute(f"SELECT * FROM `projecte_balance` WHERE `employee_id` = {Ui_PE.itemid} AND `project_id`={Ui_PE.projectid} AND `title`='Add Cash Advance'")
			res = cursor.fetchall()
			while (table.rowCount() > 0):
				table.removeRow(0)
			table.setRowCount(len(res))
			row=0
			Ui_PE.TBCDates=[]
			Ui_PE.TBCid=[]
			for x in res:
				Ui_PE.TBCid.append(x[0])

				#LEReceipt
				LECash = QtWidgets.QLineEdit(Ui_Trans.TBLTrans)
				LECash.setGeometry(QtCore.QRect(0, 0, 100, 31))
				LECash.setAlignment(QtCore.Qt.AlignCenter)
				LECash.setStyleSheet("color:white;")
				LECash.setObjectName("LECash")
				LECash.setText(str(x[5]))
				LECash.setEnabled(edit_status)
				LECash.setAlignment(QtCore.Qt.AlignCenter)
				LECash.setFont(font)
				cash = str(x[5])
				if (cash[0] == "-"):
					my_validator = QtGui.QRegExpValidator(less_regex,LECash)
				else:
					my_validator = QtGui.QRegExpValidator(my_regex,LECash)
				
				LECash.setValidator(my_validator)

				table.setCellWidget(row, 0, LECash)


				DateAllow = QtWidgets.QDateEdit(table)
				DateAllow.setCalendarPopup(True)
				DateAllow.setDate(Ui_PE.process_date(x[4]))
				DateAllow.setEnabled(edit_status)
				DateAllow.setAlignment(QtCore.Qt.AlignCenter)
				DateAllow.setFont(font)
				Ui_PE.TBCDates.append(DateAllow)
				table.setCellWidget(row, 1, Ui_PE.TBCDates[row])

				# set min max
				DateAllow.setMinimumDate(startdate)
				DateAllow.setMaximumDate(enddate)

				row=row+1
				
				
		except:
			Ui_PEForm.show_dialog(str(sys.exc_info()))




	def addTable(table):
		now = QDate.currentDate()
		item = table.item(0, 0)
		item.setText("tesing")
		DateAllow = QtWidgets.QDateEdit(table)
		DateAllow.setCalendarPopup(True)
		DateAllow.setDate(now)
		table.setCellWidget(0, 1, DateAllow)


	def EditSalary():

			Ui_PE.BtnEditSalary.hide()
			Ui_PE.BtnSaveSalary.show()
			Ui_PE.BtnCancelSalary.show()

			Ui_PE.BtnEditAllow.hide()
			Ui_PE.BtnSaveAllow.hide()
			Ui_PE.BtnCancelAllow.hide()
			Ui_PE.BtnAddAllow.hide()

			Ui_PE.BtnEditCash.hide()
			Ui_PE.BtnSaveCash.hide()
			Ui_PE.BtnCancelCash.hide()
			Ui_PE.BtnAddCash.hide()
			Ui_PE.BtnLessCash.hide()

			Ui_PE.BtnRemoveEmployee.hide()
			Ui_PE.BtnAddEmployee.hide()
			Ui_PE.BtnBack.hide()

			Ui_PE.LERate.setEnabled(True)
			Ui_PE.DateWorkStart.setEnabled(True)
			Ui_PE.DateWorkEnd.setEnabled(True)

			Ui_PE.ProjectTab.setEnabled(False)
			Ui_PE.PEList.setEnabled(False)

			try:
				cursor = con.cursor()
				query = f"SELECT * FROM `projects` WHERE `project_id`={Ui_PE.projectid}"
				cursor.execute(query)
				res = cursor.fetchall()
				d1=""
				d2=""
				for x in res:
					d1=x[4]
					d2=x[5]
				# process date
				startdate = QDate(Ui_PE.process_date(d1))
				enddate = QDate(Ui_PE.process_date(d2))
				# set min max
				Ui_PE.DateWorkStart.setMinimumDate(startdate)
				Ui_PE.DateWorkStart.setMaximumDate(enddate)
				# set min max
				Ui_PE.DateWorkEnd.setMinimumDate(startdate)
				Ui_PE.DateWorkEnd.setMaximumDate(enddate)


			except mysql.connector.Error as e:
				Dialog.msg_dialog(str(e))




	def SaveSalary():
		if (Dialog.confirm_dialog("Are you sure you want to save changes?") == QMessageBox.Ok):
			SD=""
			ED=""

			try:
				cursor = con.cursor()
				cursor.execute(f"SELECT * FROM `projects` WHERE `project_id` = {Ui_PE.projectid}")
				res = cursor.fetchall()

				for x in res:
					SD=QDate(Ui_PE.process_date(x[4]))
					ED=QDate(Ui_PE.process_date(x[5]))
			except :
					Ui_PEForm.show_dialog(str(sys.exc_info())) 

			if (Ui_PE.DateWorkStart.date() >= Ui_PE.DateWorkEnd.date()) | (Ui_PE.DateWorkStart.date()<SD) | (Ui_PE.DateWorkEnd.date()>ED) :
				Ui_PEForm.show_dialog("Invalid Date Setup") 
			elif (Ui_PE.LERate.text()=="" or float(Ui_PE.LERate.text())<62.5): 
				Ui_PEForm.show_dialog("Invalid Rate Per Hour")  if (Ui_PE.LERate.text()=="") else Ui_PEForm.show_dialog("The Minimum Rate per Hour is 62.5") 
			else:
				Ui_PE.BtnEditSalary.show()
				Ui_PE.BtnSaveSalary.hide()
				Ui_PE.BtnCancelSalary.hide()

				Ui_PE.BtnEditAllow.show()
				Ui_PE.BtnSaveAllow.hide()
				Ui_PE.BtnCancelAllow.hide()
				Ui_PE.BtnAddAllow.show()

				Ui_PE.BtnEditCash.show()
				Ui_PE.BtnSaveCash.hide()
				Ui_PE.BtnCancelCash.hide()
				Ui_PE.BtnAddCash.show()
				Ui_PE.BtnLessCash.hide()

				Ui_PE.BtnRemoveEmployee.show()
				Ui_PE.BtnAddEmployee.show()
				Ui_PE.BtnBack.show()

				Ui_PE.LERate.setEnabled(False)
				Ui_PE.DateWorkStart.setEnabled(False)
				Ui_PE.DateWorkEnd.setEnabled(False)
				Ui_PE.ProjectTab.setEnabled(True)
				Ui_PE.PEList.setEnabled(True)


				rate = Ui_PE.LERate.text()
				start = (f"{Ui_PE.DateWorkStart.date().year()},{Ui_PE.DateWorkStart.date().month()},{Ui_PE.DateWorkStart.date().day()}")
				end = (f"{Ui_PE.DateWorkEnd.date().year()},{Ui_PE.DateWorkEnd.date().month()},{Ui_PE.DateWorkEnd.date().day()}")
				rpd= float(rate)*float(8)

				try:

					cursor = con.cursor()
					query1 = (f"UPDATE `projecte` SET `rate` = {rate}, `work_start` = '{start}', `work_end` = '{end}' WHERE `employee_id` = {Ui_PE.itemid} AND `project_id`={Ui_PE.projectid}")
					cursor.execute(query1)
					con.commit()

					

					cursor = con.cursor()
					query1 = (f"UPDATE `project_payroll` SET `rateDay`={rpd}, `rateHrs` = {rate} WHERE `employee_id` = {Ui_PE.itemid} AND `project_id`={Ui_PE.projectid}")
					cursor.execute(query1)
					con.commit()


					startdate=QDate(Ui_PE.process_date(start))
					enddate=QDate(Ui_PE.process_date(end))

					cursor.execute(f"SELECT * FROM `projectdtr` WHERE `employee_id` = {Ui_PE.itemid} AND `project_id`={Ui_PE.projectid}")
					res = cursor.fetchall()


					#trim dtr
					for x in res:
						tempdate = QDate(Ui_PE.process_date(x[3]))
						date = tempdate.toString("yyyy,MM,dd")
						if (tempdate < startdate) | (tempdate>enddate):
							query2 = (f"DELETE FROM `projectdtr` WHERE `employee_id` = {Ui_PE.itemid} AND `date`='{date}' AND `project_id`={Ui_PE.projectid}")
							cursor.execute(query2)
							con.commit()


					alldates=[]

					startdate2=startdate
					enddate2=enddate

					while startdate2<=enddate2:
						alldates.append(startdate2.toString("yyyy,MM,dd"))
						startdate2=startdate2.addDays(1)

					cursor.execute(f"SELECT * FROM `projectdtr` WHERE `employee_id` = {Ui_PE.itemid} AND `project_id`={Ui_PE.projectid}")
					res = cursor.fetchall()

					addeddates=[]
					temp=""
					
					#add missing
					for x in alldates:
						flag=True
						for y in res:
							temp=x
							if x==y[3]:
								flag=False
								break
						if flag:
							query1 = "INSERT INTO projectdtr(project_id, employee_id,`date`,AM_TimeIN,AM_TimeOut,PM_TimeIN,PM_TimeOut,RH,OT) VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s)"
							query5 = (Ui_PE.projectid, Ui_PE.itemid,temp,0,0,0,0,0,0)
							cursor.execute(query1, query5)
							con.commit()

					Ui_Activity.record_activity("admin",f"Update Salary Information of {Ui_PE.LEName.text()}")


					msgBox = QMessageBox()
					msgBox.setIcon(QMessageBox.Information)
					msgBox.setText("Information was edited Successfully")
					msgBox.setWindowTitle("Message Alert")
					msgBox.setStandardButtons(QMessageBox.Ok)
					msgBox.buttonClicked.connect(msgBox.close)

					returnValue = msgBox.exec()
					if returnValue == QMessageBox.Ok:
						Ui_PE.set_info()


				except :
					Ui_PEForm.show_dialog(str(sys.exc_info())) 


	def CancelSalary():
		x=Ui_PEForm.cancel_dialog("Are you sure you want to discard changes?")
		if x:
			Ui_PE.BtnEditSalary.show()
			Ui_PE.BtnSaveSalary.hide()
			Ui_PE.BtnCancelSalary.hide()

			Ui_PE.BtnEditAllow.show()
			Ui_PE.BtnSaveAllow.hide()
			Ui_PE.BtnCancelAllow.hide()
			Ui_PE.BtnAddAllow.show()


			Ui_PE.BtnEditCash.show()
			Ui_PE.BtnSaveCash.hide()
			Ui_PE.BtnCancelCash.hide()
			Ui_PE.BtnAddCash.show()
			Ui_PE.BtnLessCash.hide()

			Ui_PE.BtnRemoveEmployee.show()
			Ui_PE.BtnAddEmployee.show()
			Ui_PE.BtnBack.show()

			Ui_PE.LERate.setEnabled(False)
			Ui_PE.DateWorkStart.setEnabled(False)
			Ui_PE.DateWorkEnd.setEnabled(False)
			Ui_PE.ProjectTab.setEnabled(True)
			Ui_PE.PEList.setEnabled(True)
			Ui_PE.set_info()


	def EditAllow():
		Ui_PE.getAllowance(Ui_PE.TBLAllowance,Ui_PE.editable,True)

		Ui_PE.BtnEditSalary.hide()
		Ui_PE.BtnSaveSalary.hide()
		Ui_PE.BtnCancelSalary.hide()

		Ui_PE.BtnEditAllow.hide()
		Ui_PE.BtnSaveAllow.show()
		Ui_PE.BtnCancelAllow.show()
		Ui_PE.BtnAddAllow.hide()
		Ui_PE.BtnRemoveAllow.show()


		Ui_PE.BtnEditCash.hide()
		Ui_PE.BtnSaveCash.hide()
		Ui_PE.BtnCancelCash.hide()
		Ui_PE.BtnAddCash.hide()
		Ui_PE.BtnLessCash.hide()

		Ui_PE.BtnRemoveEmployee.hide()
		Ui_PE.BtnAddEmployee.hide()
		Ui_PE.BtnBack.hide()

		Ui_PE.ProjectTab.setEnabled(False)
		Ui_PE.PEList.setEnabled(False)

		


	def SaveAllow():
		if (Dialog.confirm_dialog("Are you sure you want to save changes?") == QMessageBox.Ok):
			
			allow_rows = Ui_PE.TBLAllowance.rowCount()
			if allow_rows > 0:

				try:
					rows = Ui_PE.TBLAllowance.rowCount()
					invalid_row = ""
					invalid = False
					for x in range(0,rows):
						if (Ui_PE.TBLAllowance.cellWidget(x,0).text() == "" or float(Ui_PE.TBLAllowance.cellWidget(x,0).text()) == 0):
							invalid = True
							invalid_row = invalid_row + ", " + str(x+1)

					if invalid == False:
						
						x=0
						for i in range(rows):
							date = (f"{Ui_PE.TBADates[x].date().year()},{Ui_PE.TBADates[x].date().month()},{Ui_PE.TBADates[x].date().day()}")
							balance = Ui_PE.TBLAllowance.cellWidget(x,0).text()

							cursor = con.cursor()
							query1 = (f"UPDATE `projecte_balance` SET `date` = '{date}', `balance` = {balance} WHERE `id` = {Ui_PE.TBAid[x]}")
							cursor.execute(query1)
							con.commit()
							x=x+1


						msgBox = QMessageBox()
						msgBox.setIcon(QMessageBox.Information)
						msgBox.setText("Information was edited Successfully")
						msgBox.setWindowTitle("Message Alert")
						msgBox.setStandardButtons(QMessageBox.Ok)
						msgBox.buttonClicked.connect(msgBox.close)

						Ui_BalanceForm.updatePayrollBalance()

						Ui_Activity.record_activity("admin",f"Update Allowance Information of {Ui_PE.LEName.text()}")


						returnValue = msgBox.exec()
						if returnValue == QMessageBox.Ok:
							Ui_PE.getAllowance(Ui_PE.TBLAllowance,Ui_PE.not_editable,False)

							Ui_PE.BtnEditSalary.show()
							Ui_PE.BtnSaveSalary.hide()
							Ui_PE.BtnCancelSalary.hide()

							Ui_PE.BtnEditAllow.show()
							Ui_PE.BtnSaveAllow.hide()
							Ui_PE.BtnCancelAllow.hide()
							Ui_PE.BtnAddAllow.show()
							Ui_PE.BtnRemoveAllow.hide()

							Ui_PE.BtnEditCash.show()
							Ui_PE.BtnSaveCash.hide()
							Ui_PE.BtnCancelCash.hide()
							Ui_PE.BtnAddCash.show()
							Ui_PE.BtnLessCash.hide()

							Ui_PE.BtnRemoveEmployee.show()
							Ui_PE.BtnAddEmployee.show()
							Ui_PE.BtnBack.show()

							Ui_PE.ProjectTab.setEnabled(True)
							Ui_PE.PEList.setEnabled(True)
					
					else:
						invalid_row = invalid_row.replace(",","",1)
						Dialog.msg_dialog(f"Allowance Update Unsuccessful \u2794 Invalid Input at Row(s) {invalid_row.strip()}")
				except:
					Ui_PEForm.show_dialog(str(sys.exc_info()))

			else:
				Dialog.msg_dialog("There is nothing to update !")

			

	def SaveAllow2():
		Ui_PE.BtnEditSalary.show()
		Ui_PE.BtnSaveSalary.hide()
		Ui_PE.BtnCancelSalary.hide()

		Ui_PE.BtnEditAllow.show()
		Ui_PE.BtnSaveAllow.hide()
		Ui_PE.BtnCancelAllow.hide()
		Ui_PE.BtnAddAllow.show()
		Ui_PE.BtnRemoveAllow.hide()

		Ui_PE.BtnEditCash.show()
		Ui_PE.BtnSaveCash.hide()
		Ui_PE.BtnCancelCash.hide()
		Ui_PE.BtnAddCash.show()
		Ui_PE.BtnLessCash.hide()

		Ui_PE.BtnRemoveEmployee.show()
		Ui_PE.BtnAddEmployee.show()
		Ui_PE.BtnBack.show()

		Ui_PE.ProjectTab.setEnabled(True)
		Ui_PE.PEList.setEnabled(True)

		Ui_BalanceForm.updatePayrollBalance()



	def CancelAllow():
		x=Ui_PEForm.cancel_dialog("Are you sure you want to discard changes?")
		if x:
			Ui_PE.BtnEditSalary.show()
			Ui_PE.BtnSaveSalary.hide()
			Ui_PE.BtnCancelSalary.hide()

			Ui_PE.BtnEditAllow.show()
			Ui_PE.BtnSaveAllow.hide()
			Ui_PE.BtnCancelAllow.hide()
			Ui_PE.BtnAddAllow.show()
			Ui_PE.BtnRemoveAllow.hide()



			Ui_PE.BtnEditCash.show()
			Ui_PE.BtnSaveCash.hide()
			Ui_PE.BtnCancelCash.hide()
			Ui_PE.BtnAddCash.show()
			Ui_PE.BtnLessCash.hide()

			Ui_PE.BtnRemoveEmployee.show()
			Ui_PE.BtnAddEmployee.show()
			Ui_PE.BtnBack.show()

			Ui_PE.getAllowance(Ui_PE.TBLAllowance,Ui_PE.not_editable,False)
			Ui_PE.ProjectTab.setEnabled(True)
			Ui_PE.PEList.setEnabled(True)
			

	


	def EditCash():
		Ui_PE.getCashAdvance(Ui_PE.TBLCash,Ui_PE.editable,True)

		Ui_PE.BtnEditSalary.hide()
		Ui_PE.BtnSaveSalary.hide()
		Ui_PE.BtnCancelSalary.hide()

		Ui_PE.BtnEditAllow.hide()
		Ui_PE.BtnSaveAllow.hide()
		Ui_PE.BtnCancelAllow.hide()
		Ui_PE.BtnAddAllow.hide()

		Ui_PE.BtnEditCash.hide()
		Ui_PE.BtnSaveCash.show()
		Ui_PE.BtnCancelCash.show()
		Ui_PE.BtnAddCash.hide()
		Ui_PE.BtnLessCash.hide()
		Ui_PE.BtnRemoveCash.show()

		Ui_PE.BtnRemoveEmployee.hide()
		Ui_PE.BtnAddEmployee.hide()
		Ui_PE.BtnBack.hide()

		Ui_PE.ProjectTab.setEnabled(False)
		Ui_PE.PEList.setEnabled(False)

		Ui_PE.Allowid=0
		Ui_PE.Cashid=0




	def SaveCash():
		if (Dialog.confirm_dialog("Are you sure you want to save changes?") == QMessageBox.Ok):
			
			cash_rows = Ui_PE.TBLCash.rowCount()
			if cash_rows > 0:
				try:
					rows = Ui_PE.TBLCash.rowCount()
					invalid_row = ""
					invalid = False
					for x in range(rows):
						if (Ui_PE.TBLCash.cellWidget(x,0).text() == "" or float(Ui_PE.TBLCash.cellWidget(x,0).text()) == 0):
							invalid_row = invalid_row + ", " + str(x+1)
							invalid = True

					if invalid == False:

						x=0
						for i in range(rows):
							date = (f"{Ui_PE.TBCDates[x].date().year()},{Ui_PE.TBCDates[x].date().month()},{Ui_PE.TBCDates[x].date().day()}")
							balance = Ui_PE.TBLCash.cellWidget(x,0).text()

							cursor = con.cursor()
							query1 = (f"UPDATE `projecte_balance` SET `date` = '{date}', `balance` = {balance} WHERE `id` = {Ui_PE.TBCid[x]}")
							cursor.execute(query1)
							con.commit()

							query2 = (f"UPDATE `projecte_balance` SET `date` = '{date}', `balance` = -{balance} WHERE `id` = {Ui_PE.TBCid[x] + 1}")
							cursor.execute(query2)
							con.commit()

							x=x+1


						msgBox = QMessageBox()
						msgBox.setIcon(QMessageBox.Information)
						msgBox.setText("Information was edited Successfully")
						msgBox.setWindowTitle("Message Alert")
						msgBox.setStandardButtons(QMessageBox.Ok)
						msgBox.buttonClicked.connect(msgBox.close)

						Ui_BalanceForm.updatePayrollBalance()

						Ui_Activity.record_activity("admin",f"Update Cash Advance Information of {Ui_PE.LEName.text()}")


						returnValue = msgBox.exec()
						if returnValue == QMessageBox.Ok:
							Ui_PE.getCashAdvance(Ui_PE.TBLCash,Ui_PE.not_editable,False)
							Ui_PE.ProjectTab.setEnabled(True)

							Ui_PE.BtnEditSalary.show()
							Ui_PE.BtnSaveSalary.hide()
							Ui_PE.BtnCancelSalary.hide()

							Ui_PE.BtnEditAllow.show()
							Ui_PE.BtnSaveAllow.hide()
							Ui_PE.BtnCancelAllow.hide()
							Ui_PE.BtnAddAllow.show()

							Ui_PE.BtnEditCash.show()
							Ui_PE.BtnSaveCash.hide()
							Ui_PE.BtnCancelCash.hide()
							Ui_PE.BtnAddCash.show()
							Ui_PE.BtnLessCash.hide()
							Ui_PE.BtnRemoveCash.hide()

							Ui_PE.BtnRemoveEmployee.show()
							Ui_PE.BtnAddEmployee.show()
							Ui_PE.BtnBack.show()
							Ui_PE.PEList.setEnabled(True)
					else:
						invalid_row = invalid_row.replace(",","",1)
						Dialog.msg_dialog(f"Cash Update Unsuccessful \u2794 Invalid Input at Row(s) {invalid_row.strip()}")

				except:
					Ui_PEForm.show_dialog(str(sys.exc_info()))

			else:
				Dialog.msg_dialog("There is nothing to update !")



	def SaveCash2():
		Ui_PE.BtnEditSalary.show()
		Ui_PE.BtnSaveSalary.hide()
		Ui_PE.BtnCancelSalary.hide()

		Ui_PE.BtnEditAllow.show()
		Ui_PE.BtnSaveAllow.hide()
		Ui_PE.BtnCancelAllow.hide()
		Ui_PE.BtnAddAllow.show()

		Ui_PE.BtnEditCash.show()
		Ui_PE.BtnSaveCash.hide()
		Ui_PE.BtnCancelCash.hide()
		Ui_PE.BtnAddCash.show()
		Ui_PE.BtnLessCash.hide()
		Ui_PE.BtnRemoveCash.hide()

		Ui_PE.BtnRemoveEmployee.show()
		Ui_PE.BtnAddEmployee.show()
		Ui_PE.BtnBack.show()
		Ui_PE.PEList.setEnabled(True)

		Ui_PE.ProjectTab.setEnabled(True)

		Ui_BalanceForm.updatePayrollBalance()



	def CancelCash():
		x=Ui_PEForm.cancel_dialog("Are you sure you want to discard changes?")
		if x:
			Ui_PE.getCashAdvance(Ui_PE.TBLCash,Ui_PE.not_editable,False)

			Ui_PE.BtnEditSalary.show()
			Ui_PE.BtnSaveSalary.hide()
			Ui_PE.BtnCancelSalary.hide()

			Ui_PE.BtnEditAllow.show()
			Ui_PE.BtnSaveAllow.hide()
			Ui_PE.BtnCancelAllow.hide()
			Ui_PE.BtnAddAllow.show()

			Ui_PE.BtnEditCash.show()
			Ui_PE.BtnSaveCash.hide()
			Ui_PE.BtnCancelCash.hide()
			Ui_PE.BtnAddCash.show()
			Ui_PE.BtnLessCash.hide()
			Ui_PE.BtnRemoveCash.hide()

			Ui_PE.BtnRemoveEmployee.show()
			Ui_PE.BtnAddEmployee.show()
			Ui_PE.BtnBack.show()
			Ui_PE.PEList.setEnabled(True)


			Ui_PE.ProjectTab.setEnabled(True)


	def process_date(bday):
		index = 0
		start = 0
		flag1 = True
		flag2 = False
		flag3 = False

		while index < len(bday):
			if flag1 and (bday[index] == ","):
				year = bday[start:index]
				start = index + 1
				flag1 = False
				flag2 = True
			elif flag2 and (bday[index] == ","):
				month = bday[start:index]
				start = index + 1
				flag2 = False
				flag3 = True
			if flag3:
				day = bday[start:len(bday)]
				break
			index = index + 1

		return QDate(int(year), int(month), int(day))

	def get_info(item):
		Ui_PE.itemid = item.value
		# Ui_PE.search_area.setText("")

		try:
			Ui_PE.set_info()
			#call get allow

			Ui_PE.getAllowance(Ui_PE.TBLAllowance,Ui_PE.not_editable,False)
			Ui_PE.getCashAdvance(Ui_PE.TBLCash,Ui_PE.not_editable,False)

		except:
			Ui_PEForm.show_dialog(str(sys.exc_info()))

	def removeEmployee():
		
		if Ui_PE.itemid >0:
			x = Ui_PEForm.cancel_dialog("Are you sure you want to remove employee from the project?")
			if x:
				try:
					cursor = con.cursor()
					query1 = (f"UPDATE `employees` SET `Designated`='No',`Current_Site`='None' WHERE `id` = {Ui_PE.itemid}")
					cursor.execute(query1)
					con.commit()
	
					query2 = (f"DELETE FROM `projecte` WHERE `employee_id` = {Ui_PE.itemid} AND `project_id`={Ui_PE.projectid}")
					cursor.execute(query2)
					con.commit()
					query2 = (f"DELETE FROM `projecte_balance` WHERE `employee_id` = {Ui_PE.itemid} AND `project_id`={Ui_PE.projectid}")
					cursor.execute(query2)
					con.commit()

					query2 = (f"DELETE FROM `projectdtr` WHERE `employee_id` = {Ui_PE.itemid} AND `project_id`={Ui_PE.projectid}")
					cursor.execute(query2)
					con.commit()

					query2 = (f"DELETE FROM `project_payroll` WHERE `employee_id` = {Ui_PE.itemid} AND `project_id`={Ui_PE.projectid}")
					cursor.execute(query2)
					con.commit()

					Ui_Activity.record_activity("admin",f"{Ui_PE.LEName.text()} has been removed from the Project: {Ui_PE.LBProjectTitle.text()}")

				
					Ui_PEForm.show_dialog("Employee has been removed from the project")
					Ui_PE.getProjEmp()
					Ui_PE.LEName.setText("")
					Ui_PE.LEAge.setText("")
					Ui_PE.LEContact.setText("")
					Ui_PE.LESex.setText("")
					Ui_PE.LEJob.setText("")
	
					Ui_PE.ImgEmployee.clear()
					Ui_PE.ImgEmployee.setStyleSheet("color: rgb(255, 255, 255);\n"
													"background-color: rgba(0, 0, 0,0.8);")
					Ui_PE.ImgEmployee.setText("")
	
					Ui_PE.LEBday.setText("")
					Ui_PE.LERate.setText("Rate/Hour")
					now  = QDate.currentDate()
					Ui_PE.DateWorkStart.setDate(now)
					Ui_PE.DateWorkEnd.setDate(now)

					#Reset item id
					Ui_PE.itemid = 0

					# Hide Buttons @ Employee Project Page
					Ui_PE.BtnEditSalary.hide()
					Ui_PE.BtnSaveSalary.hide()
					Ui_PE.BtnCancelSalary.hide()

					Ui_PE.BtnEditAllow.hide()
					Ui_PE.BtnSaveAllow.hide()
					Ui_PE.BtnCancelAllow.hide()
					Ui_PE.BtnAddAllow.hide()
					Ui_PE.BtnRemoveAllow.hide()

					Ui_PE.BtnEditCash.hide()
					Ui_PE.BtnSaveCash.hide()
					Ui_PE.BtnCancelCash.hide()
					Ui_PE.BtnAddCash.hide()
					Ui_PE.BtnLessCash.hide()
  
				except:
					Ui_PEForm.show_dialog(str(sys.exc_info()))
		else:
			Ui_PEForm.show_dialog("Please select an employee first")


	def set_info():
		# get_info_database
		if Ui_PE.itemid > 0:
			Ui_PE.BtnEditSalary.show()
			Ui_PE.BtnEditAllow.show()
			Ui_PE.BtnEditCash.show()
			Ui_PE.BtnAddAllow.show()
			Ui_PE.BtnAddCash.show()
			Ui_PE.BtnLessCash.hide()
			try:
				cursor = con.cursor()
				cursor.execute(f"SELECT * FROM `employees` WHERE `id` = {Ui_PE.itemid}")
				res = cursor.fetchall()

				for x in res:
					suffix = ""
					if x[4] == "N/A":

						suffix = ""
					else:
						suffix = x[4]

					full_name = (f"{x[2]} {x[3]}. {x[1]} {suffix}")

					Ui_PE.LEName.setText(full_name)
					Ui_PE.LEAge.setText(str(x[7]))
					Ui_PE.LEContact.setText(f"0{x[8]}")
					Ui_PE.LESex.setText(x[5])
					Ui_PE.LEJob.setText(x[15])

					qimg = QtGui.QImage.fromData(x[16])
					pixmap = QtGui.QPixmap.fromImage(qimg)
					pixmap5 = pixmap.scaled(Ui_PE.ImgEmployee.width(), Ui_PE.ImgEmployee.height())

					Ui_PE.ImgEmployee.setPixmap(pixmap5)
					Ui_PE.ImgEmployee.setStyleSheet("color: rgb(255, 255, 255);\n"
													"background-color: rgba(0, 0, 0,0.8);")
					Ui_PE.ImgEmployee.setText("")
					Ui_PE.LEBday.setText(x[6].replace(",","/"))

				cursor.execute(f"SELECT * FROM `projecte` WHERE `employee_id` = {Ui_PE.itemid} AND `project_id`={Ui_PE.projectid}")
				res2 = cursor.fetchall()
				for y in res2:
					Ui_PE.LERate.setText(str(y[3]))
					Ui_PE.DateWorkStart.setDate(Ui_PE.process_date(y[4]))
					Ui_PE.DateWorkEnd.setDate(Ui_PE.process_date(y[5]))


			except mysql.connector.Error as e:
				Ui_PEForm.show_dialog(e)


				

	def getProjEmp():
			Ui_PE.PEList.clear()
			# get_info_database
			try:
					res = Ui_PE.mysql_select()
					Ui_PE.employee_id=[]
					Ui_PE.employee_fname=[]
					Ui_PE.employee_lname=[]
					Ui_PE.employee_mname=[]
					Ui_PE.employee_position=[]

					for x in res:
							Ui_PE.employee_id.append(x[0][0])
							Ui_PE.employee_fname.append(x[0][2])
							Ui_PE.employee_lname.append(x[0][1])
							Ui_PE.employee_mname.append(x[0][3])
							Ui_PE.employee_position.append(x[0][15])

			except mysql.connector.Error as e:
					Ui_PEForm.show_dialog(e)

			# insert elements
			index = 0
			while index < len(Ui_PE.employee_id):
					try:
							full_name = (
									f"{Ui_PE.employee_lname[index]}, {Ui_PE.employee_fname[index]} {Ui_PE.employee_mname[index]}.\n[{Ui_PE.employee_position[index]}]")
							item = QtWidgets.QListWidgetItem(full_name)
							item.setBackground(QColor('#666666')) if (index % 2) == 0 else item.setBackground(
									QColor('#595959'))
							item.value = Ui_PE.employee_id[index]
							item.setTextAlignment(QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
							Ui_PE.PEList.addItem(item)
							index = index + 1
					except:
							Ui_PEForm.show_dialog(str(sys.exc_info()))

	def mysql_select():
			cursor = con.cursor()

			cursor.execute(f"SELECT * FROM `projecte` WHERE `project_id`='{Ui_PE.projectid}' ")
			res = cursor.fetchall()

			emp=[]
			for x in res:
				cursor.execute(f"SELECT * FROM `employees` WHERE `id`='{x[2]}' ")
				emp.append(cursor.fetchall())

			return emp

		
	def PE(Project_E,DashbaordWindow):
		Ui_PE.LBProjectTitle = QtWidgets.QLabel(Project_E)
		Ui_PE.LBProjectTitle.setGeometry(QtCore.QRect(10, 10, 271, 71))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(16)
		font.setBold(True)
		font.setWeight(75)
		Ui_PE.LBProjectTitle.setFont(font)
		Ui_PE.LBProjectTitle.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
		Ui_PE.LBProjectTitle.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(148, 0, 2,.4);\n"
"border-radius:8px;\n"
"\n"
"\n"
"\n"
"")
		Ui_PE.LBProjectTitle.setTextFormat(QtCore.Qt.AutoText)
		Ui_PE.LBProjectTitle.setAlignment(QtCore.Qt.AlignCenter)
		Ui_PE.LBProjectTitle.setWordWrap(True)
		Ui_PE.LBProjectTitle.setIndent(-1)
		Ui_PE.LBProjectTitle.setObjectName("Ui_PE.LBProjectTitle")
		Ui_PE.ProjectTab = QtWidgets.QGroupBox(Project_E)
		Ui_PE.ProjectTab.setGeometry(QtCore.QRect(310, 10, 741, 71))
		Ui_PE.ProjectTab.setStyleSheet("border:none;")
		Ui_PE.ProjectTab.setTitle("")
		Ui_PE.ProjectTab.setObjectName("Ui_PE.ProjectTab")
		BtnEmployee = QtWidgets.QPushButton(Ui_PE.ProjectTab)
		BtnEmployee.setGeometry(QtCore.QRect(20, 20, 121, 31))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(16)
		font.setBold(True)
		font.setWeight(75)
		BtnEmployee.setFont(font)
		BtnEmployee.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
		BtnEmployee.setStyleSheet("color: rgb(255, 255, 255);")
		BtnEmployee.setObjectName("BtnEmployee")
		BtnDtr = QtWidgets.QPushButton(Ui_PE.ProjectTab)
		BtnDtr.setGeometry(QtCore.QRect(180, 20, 75, 31))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(16)
		font.setBold(True)
		font.setWeight(75)
		BtnDtr.setFont(font)
		BtnDtr.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
		BtnDtr.setStyleSheet("color: rgb(255, 255, 255);")
		BtnDtr.setObjectName("BtnDtr")
		BtnPayroll = QtWidgets.QPushButton(Ui_PE.ProjectTab)
		BtnPayroll.setGeometry(QtCore.QRect(300, 20, 75, 31))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(16)
		font.setBold(True)
		font.setWeight(75)
		BtnPayroll.setFont(font)
		BtnPayroll.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
		BtnPayroll.setStyleSheet("color: rgb(255, 255, 255);")
		BtnPayroll.setObjectName("BtnPayroll")
		BtnTransaction = QtWidgets.QPushButton(Ui_PE.ProjectTab)
		BtnTransaction.setGeometry(QtCore.QRect(420, 20, 141, 31))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(16)
		font.setBold(True)
		font.setWeight(75)
		BtnTransaction.setFont(font)
		BtnTransaction.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
		BtnTransaction.setStyleSheet("color: rgb(255, 255, 255);")
		BtnTransaction.setObjectName("BtnTransaction")
		BtnSummary = QtWidgets.QPushButton(Ui_PE.ProjectTab)
		BtnSummary.setGeometry(QtCore.QRect(600, 20, 131, 31))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(16)
		font.setBold(True)
		font.setWeight(75)
		BtnSummary.setFont(font)
		BtnSummary.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
		BtnSummary.setStyleSheet("color: rgb(255, 255, 255);")
		BtnSummary.setObjectName("BtnSummary")
		BGtab = QtWidgets.QLabel(Ui_PE.ProjectTab)
		BGtab.setGeometry(QtCore.QRect(0, 0, 741, 71))
		BGtab.setStyleSheet("background-color: rgb(148, 0, 2,.4);\n"
"border-radius:8px;\n"
"\n"
"")
		BGtab.setText("")
		BGtab.setObjectName("BGtab")
		BGtab.raise_()
		BtnEmployee.raise_()
		BtnDtr.raise_()
		BtnPayroll.raise_()
		BtnTransaction.raise_()
		BtnSummary.raise_()
		Ui_PE.StackProject = QtWidgets.QStackedWidget(Project_E)
		Ui_PE.StackProject.setGeometry(QtCore.QRect(0, 110, 1051, 411))
		Ui_PE.StackProject.setStyleSheet("")
		Ui_PE.StackProject.setObjectName("Ui_PE.StackProject")
		ProjectEmployee = QtWidgets.QWidget()
		ProjectEmployee.setObjectName("ProjectEmployee")
		LBProjectEmp = QtWidgets.QLabel(ProjectEmployee)
		LBProjectEmp.setGeometry(QtCore.QRect(10, 10, 271, 31))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(16)
		font.setBold(True)
		font.setWeight(75)
		LBProjectEmp.setFont(font)
		LBProjectEmp.setStyleSheet("color: rgb(255, 255, 255);\n"
"")
		LBProjectEmp.setAlignment(QtCore.Qt.AlignCenter)
		LBProjectEmp.setObjectName("LBProjectEmp")
		EmpInfo = QtWidgets.QGroupBox(ProjectEmployee)
		EmpInfo.setGeometry(QtCore.QRect(310, 0, 741, 141))
		EmpInfo.setStyleSheet("border:none;\n"
"color:white;")
		EmpInfo.setTitle("")
		EmpInfo.setObjectName("EmpInfo")
		Ui_PE.ImgEmployee = QtWidgets.QLabel(EmpInfo)
		Ui_PE.ImgEmployee.setGeometry(QtCore.QRect(10, 10, 131, 121))
		Ui_PE.ImgEmployee.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(0, 0, 0,0.8);")
		Ui_PE.ImgEmployee.setText("")
		Ui_PE.ImgEmployee.setObjectName("Ui_PE.ImgEmployee")
		Ui_PE.LBName = QtWidgets.QLabel(EmpInfo)
		Ui_PE.LBName.setGeometry(QtCore.QRect(150, 10, 90, 20))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(12)
		font.setBold(True)
		font.setWeight(75)
		Ui_PE.LBName.setFont(font)
		Ui_PE.LBName.setObjectName("Ui_PE.LBName")
		Ui_PE.LBBday = QtWidgets.QLabel(EmpInfo)
		Ui_PE.LBBday.setGeometry(QtCore.QRect(150, 30, 90, 20))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(12)
		font.setBold(True)
		font.setWeight(75)
		Ui_PE.LBBday.setFont(font)
		Ui_PE.LBBday.setObjectName("Ui_PE.LBBday")
		Ui_PE.LBAge = QtWidgets.QLabel(EmpInfo)
		Ui_PE.LBAge.setGeometry(QtCore.QRect(150, 50, 90, 20))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(12)
		font.setBold(True)
		font.setWeight(75)
		Ui_PE.LBAge.setFont(font)
		Ui_PE.LBAge.setObjectName("Ui_PE.LBAge")
		Ui_PE.LBSex = QtWidgets.QLabel(EmpInfo)
		Ui_PE.LBSex.setGeometry(QtCore.QRect(150, 70, 90, 20))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(12)
		font.setBold(True)
		font.setWeight(75)
		Ui_PE.LBSex.setFont(font)
		Ui_PE.LBSex.setObjectName("Ui_PE.LBSex")
		Ui_PE.LBContact = QtWidgets.QLabel(EmpInfo)
		Ui_PE.LBContact.setGeometry(QtCore.QRect(150, 110, 90, 20))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(12)
		font.setBold(True)
		font.setWeight(75)
		Ui_PE.LBContact.setFont(font)
		Ui_PE.LBContact.setObjectName("Ui_PE.LBContact")
		Ui_PE.LBJob = QtWidgets.QLabel(EmpInfo)
		Ui_PE.LBJob.setGeometry(QtCore.QRect(150, 90, 90, 20))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(12)
		font.setBold(True)
		font.setWeight(75)
		Ui_PE.LBJob.setFont(font)
		Ui_PE.LBJob.setStyleSheet("")
		Ui_PE.LBJob.setObjectName("Ui_PE.LBJob")
		Ui_PE.BtnEditSalary = QtWidgets.QPushButton(EmpInfo)
		Ui_PE.BtnEditSalary.setGeometry(QtCore.QRect(670, 110, 60, 25))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(10)
		font.setBold(True)
		font.setWeight(75)
		Ui_PE.BtnEditSalary.setFont(font)
		Ui_PE.BtnEditSalary.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
		Ui_PE.BtnEditSalary.setStyleSheet("background-color: rgb(0, 0, 0.9);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:5px;")
		icon = QtGui.QIcon()
		icon.addPixmap(QtGui.QPixmap(":/Icons/Assets/EditIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		Ui_PE.BtnEditSalary.setIcon(icon)
		Ui_PE.BtnEditSalary.setIconSize(QtCore.QSize(16, 16))
		Ui_PE.BtnEditSalary.setObjectName("Ui_PE.BtnEditSalary")
		partition = QtWidgets.QLabel(EmpInfo)
		partition.setGeometry(QtCore.QRect(430, 5, 2, 131))
		partition.setStyleSheet("background-color: rgb(255, 255, 255);")
		partition.setText("")
		partition.setObjectName("partition")
		BgEmployee = QtWidgets.QLabel(EmpInfo)
		BgEmployee.setGeometry(QtCore.QRect(0, 0, 741, 141))
		font = QtGui.QFont()
		font.setPointSize(12)
		font.setBold(True)
		font.setWeight(75)
		BgEmployee.setFont(font)
		BgEmployee.setStyleSheet("background-color: rgb(148, 0, 2,.4);\n"
"border-radius:8px;\n"
"")
		BgEmployee.setText("")
		BgEmployee.setObjectName("BgEmployee")
		Ui_PE.LEName = QtWidgets.QLineEdit(EmpInfo)
		Ui_PE.LEName.setGeometry(QtCore.QRect(250, 12, 175, 20))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(12)
		Ui_PE.LEName.setFont(font)
		Ui_PE.LEName.setStyleSheet("")
		Ui_PE.LEName.setText("")
		Ui_PE.LEName.setObjectName("Ui_PE.LEName")
		Ui_PE.LEBday = QtWidgets.QLineEdit(EmpInfo)
		Ui_PE.LEBday.setGeometry(QtCore.QRect(250, 32, 175, 20))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(12)
		Ui_PE.LEBday.setFont(font)
		Ui_PE.LEBday.setStyleSheet("")
		Ui_PE.LEBday.setText("")
		Ui_PE.LEBday.setObjectName("Ui_PE.LEBday")
		Ui_PE.LEAge = QtWidgets.QLineEdit(EmpInfo)
		Ui_PE.LEAge.setGeometry(QtCore.QRect(250, 52, 175, 20))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(12)
		Ui_PE.LEAge.setFont(font)
		Ui_PE.LEAge.setStyleSheet("")
		Ui_PE.LEAge.setText("")
		Ui_PE.LEAge.setObjectName("Ui_PE.LEAge")
		Ui_PE.LESex = QtWidgets.QLineEdit(EmpInfo)
		Ui_PE.LESex.setGeometry(QtCore.QRect(250, 72, 175, 20))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(12)
		Ui_PE.LESex.setFont(font)
		Ui_PE.LESex.setStyleSheet("")
		Ui_PE.LESex.setText("")
		Ui_PE.LESex.setObjectName("Ui_PE.LESex")
		Ui_PE.LEJob = QtWidgets.QLineEdit(EmpInfo)
		Ui_PE.LEJob.setGeometry(QtCore.QRect(250, 92, 175, 20))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(12)
		Ui_PE.LEJob.setFont(font)
		Ui_PE.LEJob.setStyleSheet("")
		Ui_PE.LEJob.setText("")
		Ui_PE.LEJob.setObjectName("Ui_PE.LEJob")
		Ui_PE.LEContact = QtWidgets.QLineEdit(EmpInfo)
		Ui_PE.LEContact.setGeometry(QtCore.QRect(250, 112, 175, 20))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(12)
		Ui_PE.LEContact.setFont(font)
		Ui_PE.LEContact.setStyleSheet("")
		Ui_PE.LEContact.setText("")
		Ui_PE.LEContact.setObjectName("Ui_PE.LEContact")
		LBWorkDate = QtWidgets.QLabel(EmpInfo)
		LBWorkDate.setGeometry(QtCore.QRect(540, 10, 111, 20))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(12)
		font.setBold(True)
		font.setWeight(75)
		LBWorkDate.setFont(font)
		LBWorkDate.setObjectName("LBWorkDate")
		Ui_PE.DateWorkStart = QtWidgets.QDateEdit(EmpInfo)
		Ui_PE.DateWorkStart.setGeometry(QtCore.QRect(470, 30, 110, 20))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(12)
		Ui_PE.DateWorkStart.setFont(font)
		Ui_PE.DateWorkStart.setStyleSheet("border:1px solid white;")
		Ui_PE.DateWorkStart.setCalendarPopup(True)
		Ui_PE.DateWorkStart.setObjectName("Ui_PE.DateWorkStart")
		Ui_PE.DateWorkEnd = QtWidgets.QDateEdit(EmpInfo)
		Ui_PE.DateWorkEnd.setGeometry(QtCore.QRect(600, 30, 110, 20))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(12)
		Ui_PE.DateWorkEnd.setFont(font)
		Ui_PE.DateWorkEnd.setStyleSheet("border:1px solid white;")
		Ui_PE.DateWorkEnd.setCalendarPopup(True)
		Ui_PE.DateWorkEnd.setObjectName("Ui_PE.DateWorkEnd")
		Dash = QtWidgets.QLabel(EmpInfo)
		Dash.setGeometry(QtCore.QRect(588, 30, 16, 20))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(12)
		font.setBold(True)
		font.setWeight(75)
		Dash.setFont(font)
		Dash.setObjectName("Dash")
		Ui_PE.LBRate = QtWidgets.QLabel(EmpInfo)
		Ui_PE.LBRate.setGeometry(QtCore.QRect(540, 60, 101, 20))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(12)
		font.setBold(True)
		font.setWeight(75)
		Ui_PE.LBRate.setFont(font)
		Ui_PE.LBRate.setAlignment(QtCore.Qt.AlignCenter)
		Ui_PE.LBRate.setObjectName("Ui_PE.LBRate")
		Ui_PE.LERate = QtWidgets.QLineEdit(EmpInfo)
		Ui_PE.LERate.setGeometry(QtCore.QRect(530, 80, 113, 20))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(12)
		Ui_PE.LERate.setFont(font)
		Ui_PE.LERate.setStyleSheet("border:1px solid white;")
		Ui_PE.LERate.setText("")
		Ui_PE.LERate.setAlignment(QtCore.Qt.AlignCenter)
		Ui_PE.LERate.setObjectName("Ui_PE.LERate")
		colon1 = QtWidgets.QLabel(EmpInfo)
		colon1.setGeometry(QtCore.QRect(242, 10, 16, 20))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(12)
		font.setBold(True)
		font.setWeight(75)
		colon1.setFont(font)
		colon1.setObjectName("colon1")
		colon2 = QtWidgets.QLabel(EmpInfo)
		colon2.setGeometry(QtCore.QRect(242, 30, 16, 20))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(12)
		font.setBold(True)
		font.setWeight(75)
		colon2.setFont(font)
		colon2.setObjectName("colon2")
		colon3 = QtWidgets.QLabel(EmpInfo)
		colon3.setGeometry(QtCore.QRect(242, 50, 16, 20))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(12)
		font.setBold(True)
		font.setWeight(75)
		colon3.setFont(font)
		colon3.setObjectName("colon3")
		colon4 = QtWidgets.QLabel(EmpInfo)
		colon4.setGeometry(QtCore.QRect(242, 70, 16, 20))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(12)
		font.setBold(True)
		font.setWeight(75)
		colon4.setFont(font)
		colon4.setObjectName("colon4")
		colon5 = QtWidgets.QLabel(EmpInfo)
		colon5.setGeometry(QtCore.QRect(242, 90, 16, 20))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(12)
		font.setBold(True)
		font.setWeight(75)
		colon5.setFont(font)
		colon5.setObjectName("colon5")
		colon6 = QtWidgets.QLabel(EmpInfo)
		colon6.setGeometry(QtCore.QRect(242, 110, 16, 20))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(12)
		font.setBold(True)
		font.setWeight(75)
		colon6.setFont(font)
		colon6.setObjectName("colon6")
		LEPHP = QtWidgets.QLabel(EmpInfo)
		LEPHP.setGeometry(QtCore.QRect(495, 80, 31, 20))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(12)
		LEPHP.setFont(font)
		LEPHP.setStyleSheet("")
		LEPHP.setObjectName("LEPHP")
		BgEmployee.raise_()
		Ui_PE.ImgEmployee.raise_()
		Ui_PE.LBName.raise_()
		Ui_PE.LBBday.raise_()
		Ui_PE.LBAge.raise_()
		Ui_PE.LBSex.raise_()
		Ui_PE.LBContact.raise_()
		Ui_PE.LBJob.raise_()
		Ui_PE.BtnEditSalary.raise_()
		partition.raise_()
		Ui_PE.LEName.raise_()
		Ui_PE.LEBday.raise_()
		Ui_PE.LEAge.raise_()
		Ui_PE.LESex.raise_()
		Ui_PE.LEJob.raise_()
		Ui_PE.LEContact.raise_()
		LBWorkDate.raise_()
		Ui_PE.DateWorkStart.raise_()
		Ui_PE.DateWorkEnd.raise_()
		Dash.raise_()
		Ui_PE.LBRate.raise_()
		Ui_PE.LERate.raise_()
		colon1.raise_()
		colon2.raise_()
		colon3.raise_()
		colon4.raise_()
		colon5.raise_()
		colon6.raise_()
		LEPHP.raise_()
		Ui_PE.BtnRemoveEmployee = QtWidgets.QPushButton(ProjectEmployee)
		Ui_PE.BtnRemoveEmployee.setGeometry(QtCore.QRect(167, 360, 100, 31))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(12)
		font.setBold(True)
		font.setWeight(75)
		Ui_PE.BtnRemoveEmployee.setFont(font)
		Ui_PE.BtnRemoveEmployee.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
		Ui_PE.BtnRemoveEmployee.setStyleSheet("background-color: rgb(0, 0, 0.9);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:5px;")
		icon1 = QtGui.QIcon()
		icon1.addPixmap(QtGui.QPixmap(":/Icons/Assets/RemoveIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		Ui_PE.BtnRemoveEmployee.setIcon(icon1)
		Ui_PE.BtnRemoveEmployee.setObjectName("Ui_PE.BtnRemoveEmployee")
		Ui_PE.BtnAddEmployee = QtWidgets.QPushButton(ProjectEmployee)
		Ui_PE.BtnAddEmployee.setGeometry(QtCore.QRect(24, 360, 100, 31))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(12)
		font.setBold(True)
		font.setWeight(75)
		Ui_PE.BtnAddEmployee.setFont(font)
		Ui_PE.BtnAddEmployee.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
		Ui_PE.BtnAddEmployee.setStyleSheet("background-color: rgb(0, 0, 0.9);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:5px;")
		icon2 = QtGui.QIcon()
		icon2.addPixmap(QtGui.QPixmap(":/Icons/Assets/AddIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		Ui_PE.BtnAddEmployee.setIcon(icon2)
		Ui_PE.BtnAddEmployee.setObjectName("Ui_PE.BtnAddEmployee")
		Balance = QtWidgets.QGroupBox(ProjectEmployee)
		Balance.setGeometry(QtCore.QRect(310, 160, 741, 241))
		Balance.setStyleSheet("border:none;")
		Balance.setTitle("")
		Balance.setObjectName("Balance")
		BGBalance = QtWidgets.QLabel(Balance)
		BGBalance.setGeometry(QtCore.QRect(0, 0, 751, 241))
		BGBalance.setStyleSheet("background-color: rgb(148, 0, 2,.4);\n"
"border-radius:8px;\n"
"")
		BGBalance.setText("")
		BGBalance.setObjectName("BGBalance")
		Ui_PE.BtnEditAllow = QtWidgets.QPushButton(Balance)
		Ui_PE.BtnEditAllow.setGeometry(QtCore.QRect(270, 210, 60, 25))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(12)
		font.setBold(True)
		font.setWeight(75)
		Ui_PE.BtnEditAllow.setFont(font)
		Ui_PE.BtnEditAllow.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
		Ui_PE.BtnEditAllow.setStyleSheet("background-color: rgb(0, 0, 0.9);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:5px;")
		Ui_PE.BtnEditAllow.setIcon(icon)
		Ui_PE.BtnEditAllow.setObjectName("Ui_PE.BtnEditAllow")
		Ui_PE.BtnEditCash = QtWidgets.QPushButton(Balance)
		Ui_PE.BtnEditCash.setGeometry(QtCore.QRect(650, 210, 60, 25))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(12)
		font.setBold(True)
		font.setWeight(75)
		Ui_PE.BtnEditCash.setFont(font)
		Ui_PE.BtnEditCash.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
		Ui_PE.BtnEditCash.setStyleSheet("background-color: rgb(0, 0, 0.9);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:5px;")
		Ui_PE.BtnEditCash.setIcon(icon)
		Ui_PE.BtnEditCash.setObjectName("Ui_PE.BtnEditCash")
		Allowance = QtWidgets.QGroupBox(Balance)
		Allowance.setGeometry(QtCore.QRect(10, 10, 341, 191))
		Allowance.setTitle("")
		Allowance.setObjectName("Allowance")
		Allowance.setStyleSheet("color:white;")
		BGAllowance = QtWidgets.QLabel(Allowance)
		BGAllowance.setGeometry(QtCore.QRect(0, 0, 341, 191))
		BGAllowance.setStyleSheet("background-color: rgb(60, 0, 0,.8);")
		BGAllowance.setText("")
		BGAllowance.setObjectName("BGAllowance")
		Ui_PE.TBLAllowance = QtWidgets.QTableWidget(Allowance)
		Ui_PE.TBLAllowance.setGeometry(QtCore.QRect(0, 0, 341, 191))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(12)
		Ui_PE.TBLAllowance.setFont(font)
		Ui_PE.TBLAllowance.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
		Ui_PE.TBLAllowance.setLayoutDirection(QtCore.Qt.LeftToRight)

		Ui_PE.TBLAllowance.horizontalHeader().setStyleSheet('''::section{background-color:transparent;}''')
		Ui_PE.TBLAllowance.setStyleSheet("QTableWidget::item{border:1px solid white;}")

		Ui_PE.TBLAllowance.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
		Ui_PE.TBLAllowance.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
		Ui_PE.TBLAllowance.setProperty("showDropIndicator", True)
		Ui_PE.TBLAllowance.setTextElideMode(QtCore.Qt.ElideRight)
		Ui_PE.TBLAllowance.setShowGrid(True)
		Ui_PE.TBLAllowance.setGridStyle(QtCore.Qt.SolidLine)
		Ui_PE.TBLAllowance.setColumnCount(2)
		Ui_PE.TBLAllowance.setObjectName("Ui_PE.TBLAllowance")
		item = QtWidgets.QTableWidgetItem()
		brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
		brush.setStyle(QtCore.Qt.NoBrush)
		item.setForeground(brush)
		Ui_PE.TBLAllowance.setVerticalHeaderItem(0, item)
		item = QtWidgets.QTableWidgetItem()
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(12)
		font.setBold(True)
		font.setWeight(75)
		item.setFont(font)
		item.setBackground(QtGui.QColor(0, 0, 0))
		Ui_PE.TBLAllowance.setHorizontalHeaderItem(0, item)
		item = QtWidgets.QTableWidgetItem()
		font = QtGui.QFont()
		font.setFamily("Calibri Light")
		font.setPointSize(12)
		font.setBold(True)
		font.setWeight(75)
		item.setFont(font)
		Ui_PE.TBLAllowance.setHorizontalHeaderItem(1, item)
		
		
		Ui_PE.TBLAllowance.horizontalHeader().setVisible(True)
		Ui_PE.TBLAllowance.horizontalHeader().setCascadingSectionResizes(True)
		Ui_PE.TBLAllowance.horizontalHeader().setDefaultSectionSize(150)
		Ui_PE.TBLAllowance.horizontalHeader().setHighlightSections(True)
		Ui_PE.TBLAllowance.horizontalHeader().setSortIndicatorShown(False)
		Ui_PE.TBLAllowance.horizontalHeader().setStretchLastSection(True)
		Ui_PE.TBLAllowance.verticalHeader().setVisible(False)
		Ui_PE.TBLAllowance.verticalHeader().setCascadingSectionResizes(False)
		Ui_PE.TBLAllowance.verticalHeader().setHighlightSections(True)
		Ui_PE.TBLAllowance.verticalHeader().setSortIndicatorShown(False)
		Ui_PE.TBLAllowance.verticalHeader().setStretchLastSection(False)
		Cash = QtWidgets.QGroupBox(Balance)
		Cash.setGeometry(QtCore.QRect(400, 10, 331, 191))
		Cash.setTitle("")
		Cash.setStyleSheet("color:white;")
		Cash.setObjectName("Cash")
		BGCash = QtWidgets.QLabel(Cash)
		BGCash.setGeometry(QtCore.QRect(0, 0, 331, 191))
		BGCash.setStyleSheet("background-color: rgb(60, 0, 0,.8);")
		BGCash.setText("")
		BGCash.setObjectName("BGCash")
		Ui_PE.TBLCash = QtWidgets.QTableWidget(Cash)
		Ui_PE.TBLCash.setGeometry(QtCore.QRect(0, 0, 331, 191))

		Ui_PE.TBLCash.horizontalHeader().setStyleSheet('''::section{background-color:transparent;}''')
		Ui_PE.TBLCash.setStyleSheet("QTableWidget::item{border:1px solid white;}")

		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(12)
		Ui_PE.TBLCash.setFont(font)
		Ui_PE.TBLCash.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
		Ui_PE.TBLCash.setLayoutDirection(QtCore.Qt.LeftToRight)
		Ui_PE.TBLCash.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
		Ui_PE.TBLCash.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
		Ui_PE.TBLCash.setProperty("showDropIndicator", True)
		Ui_PE.TBLCash.setAlternatingRowColors(False)
		Ui_PE.TBLCash.setTextElideMode(QtCore.Qt.ElideRight)
		Ui_PE.TBLCash.setShowGrid(True)
		Ui_PE.TBLCash.setGridStyle(QtCore.Qt.SolidLine)
		Ui_PE.TBLCash.setColumnCount(2)
		Ui_PE.TBLCash.setObjectName("Ui_PE.TBLCash")
		item = QtWidgets.QTableWidgetItem()
		Ui_PE.TBLCash.setVerticalHeaderItem(0, item)
		item = QtWidgets.QTableWidgetItem()
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(12)
		font.setBold(True)
		font.setWeight(75)
		item.setFont(font)
		Ui_PE.TBLCash.setHorizontalHeaderItem(0, item)
		item = QtWidgets.QTableWidgetItem()
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(12)
		font.setBold(True)
		font.setWeight(75)
		item.setFont(font)
		Ui_PE.TBLCash.setHorizontalHeaderItem(1, item)


		Ui_PE.TBLCash.horizontalHeader().setVisible(True)
		Ui_PE.TBLCash.horizontalHeader().setCascadingSectionResizes(True)
		Ui_PE.TBLCash.horizontalHeader().setDefaultSectionSize(150)
		Ui_PE.TBLCash.horizontalHeader().setHighlightSections(True)
		Ui_PE.TBLCash.horizontalHeader().setSortIndicatorShown(False)
		Ui_PE.TBLCash.horizontalHeader().setStretchLastSection(True)
		Ui_PE.TBLCash.verticalHeader().setVisible(False)
		Ui_PE.TBLCash.verticalHeader().setCascadingSectionResizes(False)
		Ui_PE.TBLCash.verticalHeader().setHighlightSections(True)
		Ui_PE.TBLCash.verticalHeader().setSortIndicatorShown(False)
		Ui_PE.TBLCash.verticalHeader().setStretchLastSection(False)
		PEmployeeList = QtWidgets.QScrollArea(ProjectEmployee)
		PEmployeeList.setEnabled(True)
		PEmployeeList.setGeometry(QtCore.QRect(10, 60, 281, 281))
		PEmployeeList.setStyleSheet("background-color: rgb(104, 0, 0,.1);\n"
"border-radius:8px;")
		PEmployeeList.setWidgetResizable(True)
		PEmployeeList.setObjectName("PEmployeeList")
		EmployeeListScroll_2 = QtWidgets.QWidget()
		EmployeeListScroll_2.setEnabled(True)
		EmployeeListScroll_2.setGeometry(QtCore.QRect(0, 0, 281, 281))
		EmployeeListScroll_2.setObjectName("EmployeeListScroll_2")
		Ui_PE.PEList = QtWidgets.QListWidget(EmployeeListScroll_2)
		Ui_PE.PEList.setGeometry(QtCore.QRect(0, 0, 281, 281))
		Ui_PE.PEList.setLayoutDirection(QtCore.Qt.RightToLeft)
		Ui_PE.PEList.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
		Ui_PE.PEList.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
		Ui_PE.PEList.setStyleSheet("background-color: rgb(167, 167, 167,.4);\n"
									"border-radius:5px;\n"
									"font-size:16px;\n"
									"color:white;\n"
									"")
		Ui_PE.PEList.setObjectName("Ui_PE.PEList")
		PEmployeeList.setWidget(EmployeeListScroll_2)
		Ui_PE.StackProject.addWidget(ProjectEmployee)

		Ui_PE.BtnBack = QtWidgets.QPushButton(DashbaordWindow)
		Ui_PE.BtnBack.setGeometry(QtCore.QRect(1119, 82, 91, 31))
		font = QtGui.QFont()
		font.setFamily("Calibri Light")
		font.setPointSize(12)
		font.setBold(True)
		font.setWeight(75)
		Ui_PE.BtnBack.setFont(font)
		Ui_PE.BtnBack.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
		Ui_PE.BtnBack.setStyleSheet("background-color: rgb(0, 0, 0.9);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:5px;")
		icon3 = QtGui.QIcon()
		icon3.addPixmap(QtGui.QPixmap(":/Icons/Assets/BackIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		Ui_PE.BtnBack.setIcon(icon3)
		Ui_PE.BtnBack.setObjectName("BtnBack")

		_translate = QtCore.QCoreApplication.translate
		Ui_PE.LBProjectTitle.setText(_translate("DashbaordWindow", "Project Title"))
		BtnEmployee.setText(_translate("DashbaordWindow", "Employees"))
		BtnDtr.setText(_translate("DashbaordWindow", "DTR"))
		BtnPayroll.setText(_translate("DashbaordWindow", "Payroll"))
		BtnTransaction.setText(_translate("DashbaordWindow", "Transaction"))
		BtnSummary.setText(_translate("DashbaordWindow", "Summary"))
		LBProjectEmp.setText(_translate("DashbaordWindow", "Project Employees"))
		Ui_PE.LBName.setText(_translate("DashbaordWindow", "Name          "))
		Ui_PE.LBBday.setText(_translate("DashbaordWindow", "Birthday    "))
		Ui_PE.LBAge.setText(_translate("DashbaordWindow", "Age"))
		Ui_PE.LBSex.setText(_translate("DashbaordWindow", "Sex"))
		Ui_PE.LBContact.setText(_translate("DashbaordWindow", "Contact No."))
		Ui_PE.LBJob.setText(_translate("DashbaordWindow", "Job Position"))
		Ui_PE.BtnEditSalary.setText(_translate("DashbaordWindow", "Edit"))
		Ui_PE.LEName.setPlaceholderText(_translate("DashbaordWindow", "Name"))
		Ui_PE.LEBday.setPlaceholderText(_translate("DashbaordWindow", "Birthday"))
		Ui_PE.LEAge.setPlaceholderText(_translate("DashbaordWindow", "Age"))
		Ui_PE.LESex.setPlaceholderText(_translate("DashbaordWindow", "Sex"))
		Ui_PE.LEJob.setPlaceholderText(_translate("DashbaordWindow", "Job Position"))
		Ui_PE.LEContact.setPlaceholderText(_translate("DashbaordWindow", "Contact No."))
		LBWorkDate.setText(_translate("DashbaordWindow", "Work Due Date"))
		Dash.setText(_translate("DashbaordWindow", "-"))
		Ui_PE.LBRate.setText(_translate("DashbaordWindow", "Rate Per Hour"))
		Ui_PE.LERate.setPlaceholderText(_translate("DashbaordWindow", "Rate/Hour"))
		colon1.setText(_translate("DashbaordWindow", ":"))
		colon2.setText(_translate("DashbaordWindow", ":"))
		colon3.setText(_translate("DashbaordWindow", ":"))
		colon4.setText(_translate("DashbaordWindow", ":"))
		colon5.setText(_translate("DashbaordWindow", ":"))
		colon6.setText(_translate("DashbaordWindow", ":"))
		LEPHP.setText(_translate("DashbaordWindow", "PHP"))
		Ui_PE.BtnRemoveEmployee.setText(_translate("DashbaordWindow", "  Remove"))
		Ui_PE.BtnAddEmployee.setText(_translate("DashbaordWindow", "  Add"))
		Ui_PE.BtnEditAllow.setText(_translate("DashbaordWindow", "Edit"))
		Ui_PE.BtnEditCash.setText(_translate("DashbaordWindow", "Edit"))
		item = Ui_PE.TBLAllowance.horizontalHeaderItem(0)
		item.setText(_translate("DashbaordWindow", "Allowance"))
		item = Ui_PE.TBLAllowance.horizontalHeaderItem(1)
		item.setText(_translate("DashbaordWindow", "Date"))
		__sortingEnabled = Ui_PE.TBLAllowance.isSortingEnabled()
		Ui_PE.TBLAllowance.setSortingEnabled(False)
		Ui_PE.TBLAllowance.setSortingEnabled(__sortingEnabled)
		Ui_PE.TBLCash.setSortingEnabled(False)
		item = Ui_PE.TBLCash.horizontalHeaderItem(0)
		item.setText(_translate("DashbaordWindow", "Cash Advance"))
		item = Ui_PE.TBLCash.horizontalHeaderItem(1)
		item.setText(_translate("DashbaordWindow", "Date"))
		__sortingEnabled = Ui_PE.TBLCash.isSortingEnabled()
		Ui_PE.TBLCash.setSortingEnabled(False)


		Ui_PE.TBLCash.setSortingEnabled(__sortingEnabled)
		Ui_PE.BtnBack.setText(_translate("DashbaordWindow", "  Back"))

		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(10)
		font.setBold(True)
		font.setWeight(75)


		#save button salary
		Ui_PE.BtnSaveSalary = QtWidgets.QPushButton(EmpInfo)
		Ui_PE.BtnSaveSalary.setGeometry(QtCore.QRect(600, 110, 60, 25))
		Ui_PE.BtnSaveSalary.setFont(font)
		Ui_PE.BtnSaveSalary.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
		Ui_PE.BtnSaveSalary.setStyleSheet("background-color: rgb(0, 0, 0.9);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:5px;")
		icon = QtGui.QIcon()
		icon.addPixmap(QtGui.QPixmap(":/Icons/Assets/SaveIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		Ui_PE.BtnSaveSalary.setIcon(icon)
		Ui_PE.BtnSaveSalary.setIconSize(QtCore.QSize(16, 16))
		Ui_PE.BtnSaveSalary.setObjectName("Ui_PE.BtnSaveSalary")
		Ui_PE.BtnSaveSalary.hide()
		Ui_PE.BtnSaveSalary.setText(_translate("DashbaordWindow", "Save"))



		#cancel ubtton salamry
		Ui_PE.BtnCancelSalary = QtWidgets.QPushButton(EmpInfo)
		Ui_PE.BtnCancelSalary.setGeometry(QtCore.QRect(670, 110, 60, 25))
		Ui_PE.BtnCancelSalary.setFont(font)
		Ui_PE.BtnCancelSalary.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
		Ui_PE.BtnCancelSalary.setStyleSheet("background-color: rgb(0, 0, 0.9);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:5px;")
		icon = QtGui.QIcon()
		icon.addPixmap(QtGui.QPixmap(":/Icons/Assets/CancelIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		Ui_PE.BtnCancelSalary.setIcon(icon)
		Ui_PE.BtnCancelSalary.setIconSize(QtCore.QSize(16, 16))
		Ui_PE.BtnCancelSalary.setObjectName("Ui_PE.BtnCancelSalary")
		Ui_PE.BtnCancelSalary.hide()
		Ui_PE.BtnCancelSalary.setText(_translate("DashbaordWindow", "Cancel"))


		#save button Allowwwwwww============
		Ui_PE.BtnSaveAllow = QtWidgets.QPushButton(Balance)
		Ui_PE.BtnSaveAllow.setGeometry(QtCore.QRect(200, 210, 60, 25))
		Ui_PE.BtnSaveAllow.setFont(font)
		Ui_PE.BtnSaveAllow.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
		Ui_PE.BtnSaveAllow.setStyleSheet("background-color: rgb(0, 0, 0.9);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:5px;")
		icon = QtGui.QIcon()
		icon.addPixmap(QtGui.QPixmap(":/Icons/Assets/SaveIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		Ui_PE.BtnSaveAllow.setIcon(icon)
		Ui_PE.BtnSaveAllow.setIconSize(QtCore.QSize(16, 16))
		Ui_PE.BtnSaveAllow.setObjectName("Ui_PE.BtnSaveAllow")
		Ui_PE.BtnSaveAllow.hide()
		Ui_PE.BtnSaveAllow.setText(_translate("DashbaordWindow", "Save"))

		#remove button Allowwwwwww============
		Ui_PE.BtnRemoveAllow = QtWidgets.QPushButton(Balance)
		Ui_PE.BtnRemoveAllow.setGeometry(QtCore.QRect(30, 210, 81, 25))
		Ui_PE.BtnRemoveAllow.setFont(font)
		Ui_PE.BtnRemoveAllow.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
		Ui_PE.BtnRemoveAllow.setStyleSheet("background-color: rgb(0, 0, 0.9);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:5px;")
		icon = QtGui.QIcon()
		icon.addPixmap(QtGui.QPixmap(":/Icons/Assets/RemoveIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		Ui_PE.BtnRemoveAllow.setIcon(icon)
		Ui_PE.BtnRemoveAllow.setIconSize(QtCore.QSize(16, 16))
		Ui_PE.BtnRemoveAllow.setObjectName("Ui_PE.BtnRemoveAllow")
		Ui_PE.BtnRemoveAllow.hide()
		Ui_PE.BtnRemoveAllow.setText(_translate("DashbaordWindow", "Remove"))

		#add button Allowwwwwww============
		Ui_PE.BtnAddAllow = QtWidgets.QPushButton(Balance)
		Ui_PE.BtnAddAllow.setGeometry(QtCore.QRect(200, 210, 60, 25))
		Ui_PE.BtnAddAllow.setFont(font)
		Ui_PE.BtnAddAllow.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
		Ui_PE.BtnAddAllow.setStyleSheet("background-color: rgb(0, 0, 0.9);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:5px;")
		icon = QtGui.QIcon()
		icon.addPixmap(QtGui.QPixmap(":/Icons/Assets/AddIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		Ui_PE.BtnAddAllow.setIcon(icon)
		Ui_PE.BtnAddAllow.setIconSize(QtCore.QSize(16, 16))
		Ui_PE.BtnAddAllow.setObjectName("Ui_PE.BtnAddAllow")
		Ui_PE.BtnAddAllow.setText(_translate("DashbaordWindow", "Add"))
		Ui_PE.BtnAddAllow.hide()



		#cancel ubtton sllow
		Ui_PE.BtnCancelAllow = QtWidgets.QPushButton(Balance)
		Ui_PE.BtnCancelAllow.setGeometry(QtCore.QRect(270, 210, 60, 25))
		Ui_PE.BtnCancelAllow.setFont(font)
		Ui_PE.BtnCancelAllow.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
		Ui_PE.BtnCancelAllow.setStyleSheet("background-color: rgb(0, 0, 0.9);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:5px;")
		icon = QtGui.QIcon()
		icon.addPixmap(QtGui.QPixmap(":/Icons/Assets/CancelIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		Ui_PE.BtnCancelAllow.setIcon(icon)
		Ui_PE.BtnCancelAllow.setIconSize(QtCore.QSize(16, 16))
		Ui_PE.BtnCancelAllow.setObjectName("Ui_PE.BtnCancelAllow")
		Ui_PE.BtnCancelAllow.hide()
		Ui_PE.BtnCancelAllow.setText(_translate("DashbaordWindow", "Cancel"))



		#save button Cash
		Ui_PE.BtnSaveCash = QtWidgets.QPushButton(Balance)
		Ui_PE.BtnSaveCash.setGeometry(QtCore.QRect(580, 210, 60, 25))
		Ui_PE.BtnSaveCash.setFont(font)
		Ui_PE.BtnSaveCash.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
		Ui_PE.BtnSaveCash.setStyleSheet("background-color: rgb(0, 0, 0.9);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:5px;")
		icon = QtGui.QIcon()
		icon.addPixmap(QtGui.QPixmap(":/Icons/Assets/SaveIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		Ui_PE.BtnSaveCash.setIcon(icon)
		Ui_PE.BtnSaveCash.setIconSize(QtCore.QSize(16, 16))
		Ui_PE.BtnSaveCash.setObjectName("Ui_PE.BtnSaveCash")
		Ui_PE.BtnSaveCash.hide()
		Ui_PE.BtnSaveCash.setText(_translate("DashbaordWindow", "Save"))

		#remove button Cash============
		Ui_PE.BtnRemoveCash = QtWidgets.QPushButton(Balance)
		Ui_PE.BtnRemoveCash.setGeometry(QtCore.QRect(420, 210, 81, 25))
		Ui_PE.BtnRemoveCash.setFont(font)
		Ui_PE.BtnRemoveCash.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
		Ui_PE.BtnRemoveCash.setStyleSheet("background-color: rgb(0, 0, 0.9);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:5px;")
		icon = QtGui.QIcon()
		icon.addPixmap(QtGui.QPixmap(":/Icons/Assets/RemoveIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		Ui_PE.BtnRemoveCash.setIcon(icon)
		Ui_PE.BtnRemoveCash.setIconSize(QtCore.QSize(16, 16))
		Ui_PE.BtnRemoveCash.setObjectName("Ui_PE.BtnRemoveCash")
		Ui_PE.BtnRemoveCash.hide()
		Ui_PE.BtnRemoveCash.setText(_translate("DashbaordWindow", "Remove"))


		#add button Cash
		Ui_PE.BtnAddCash = QtWidgets.QPushButton(Balance)
		Ui_PE.BtnAddCash.setGeometry(QtCore.QRect(580, 210, 60, 25))
		Ui_PE.BtnAddCash.setFont(font)
		Ui_PE.BtnAddCash.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
		Ui_PE.BtnAddCash.setStyleSheet("background-color: rgb(0, 0, 0.9);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:5px;")
		icon = QtGui.QIcon()
		icon.addPixmap(QtGui.QPixmap(":/Icons/Assets/AddIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		Ui_PE.BtnAddCash.setIcon(icon)
		Ui_PE.BtnAddCash.setIconSize(QtCore.QSize(16, 16))
		Ui_PE.BtnAddCash.setObjectName("Ui_PE.BtnAddCash")
		Ui_PE.BtnAddCash.setText(_translate("DashbaordWindow", "Add"))
		Ui_PE.BtnAddCash.hide()

		#add BtnLessCash
		Ui_PE.BtnLessCash = QtWidgets.QPushButton(Balance)
		Ui_PE.BtnLessCash.setGeometry(QtCore.QRect(510, 210, 60, 25))
		Ui_PE.BtnLessCash.setFont(font)
		Ui_PE.BtnLessCash.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
		Ui_PE.BtnLessCash.setStyleSheet("background-color: rgb(0, 0, 0.9);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:5px;")
		icon = QtGui.QIcon()
		icon.addPixmap(QtGui.QPixmap(":/Icons/Assets/LessIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		Ui_PE.BtnLessCash.setIcon(icon)
		Ui_PE.BtnLessCash.setIconSize(QtCore.QSize(16, 16))
		Ui_PE.BtnLessCash.setObjectName("Ui_PE.BtnAddCash")
		Ui_PE.BtnLessCash.setText(_translate("DashbaordWindow", "Less"))
		Ui_PE.BtnLessCash.hide()


		#cancel ubtton Cash
		Ui_PE.BtnCancelCash = QtWidgets.QPushButton(Balance)
		Ui_PE.BtnCancelCash.setGeometry(QtCore.QRect(650, 210, 60, 25))
		Ui_PE.BtnCancelCash.setFont(font)
		Ui_PE.BtnCancelCash.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
		Ui_PE.BtnCancelCash.setStyleSheet("background-color: rgb(0, 0, 0.9);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:5px;")
		icon = QtGui.QIcon()
		icon.addPixmap(QtGui.QPixmap(":/Icons/Assets/CancelIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		Ui_PE.BtnCancelCash.setIcon(icon)
		Ui_PE.BtnCancelCash.setIconSize(QtCore.QSize(16, 16))
		Ui_PE.BtnCancelCash.setObjectName("Ui_PE.BtnCancelCash")
		Ui_PE.BtnCancelCash.hide()
		Ui_PE.BtnCancelCash.setText(_translate("DashbaordWindow", "Cancel"))

		#added stacks


		#ProjectDTR
		ProjectDTR= QtWidgets.QWidget()
		ProjectDTR.setObjectName("ProjectDTR")
		Ui_DTR.PDTR(ProjectDTR,Ui_PE.BtnBack,Ui_PE.ProjectTab)
		Ui_PE.StackProject.addWidget(ProjectDTR)

		

		#ProjectPayroll
		ProjectPayroll= QtWidgets.QWidget()
		ProjectPayroll.setObjectName("ProjectPayroll")
		Ui_Payroll.Payroll(ProjectPayroll,Ui_PE.BtnBack,Ui_PE.ProjectTab)
		Ui_PE.StackProject.addWidget(ProjectPayroll)

		#ProjectTransaction
		ProjectTransaction= QtWidgets.QWidget()
		ProjectTransaction.setObjectName("ProjectTransaction")
		Ui_Trans.Transaction(ProjectTransaction,DashbaordWindow,Ui_PE.BtnBack,Ui_PE.ProjectTab)
		Ui_PE.StackProject.addWidget(ProjectTransaction)

		#ProjectSummary
		ProjectSummary= QtWidgets.QWidget()
		ProjectSummary.setObjectName("ProjectSummary")
		Ui_Summary.Summary(ProjectSummary)
		Ui_PE.StackProject.addWidget(ProjectSummary)


		#buttons
		BtnEmployee.clicked.connect(lambda: Ui_PE.showpage(ProjectEmployee))
		BtnDtr.clicked.connect(lambda: Ui_PE.showdtr(ProjectDTR))
		BtnPayroll.clicked.connect(lambda: Ui_PE.showpayroll(ProjectPayroll))
		BtnTransaction.clicked.connect(lambda: Ui_PE.showtrans(ProjectTransaction))
		BtnSummary.clicked.connect(lambda: Ui_PE.showsummary(ProjectSummary))




		#adds
		Ui_PE.BtnBack.hide()
		Ui_PE.LEName.setEnabled(False)
		Ui_PE.LEBday.setEnabled(False)
		Ui_PE.LEAge.setEnabled(False)
		Ui_PE.LESex.setEnabled(False)
		Ui_PE.LEJob.setEnabled(False)
		Ui_PE.LEContact.setEnabled(False)

		# load Project Form
		Ui_PEForm.DesignateForm(DashbaordWindow)
		#load Balance form
		Ui_BalanceForm.BalanceForm(DashbaordWindow)

		#btn functions

		Ui_PE.BtnAddEmployee.clicked.connect(lambda: Ui_PEForm.showForm())
		Ui_PE.BtnRemoveEmployee.clicked.connect(lambda : Ui_PE.removeEmployee())

		Ui_PE.BtnEditSalary.clicked.connect(lambda : Ui_PE.EditSalary())
		Ui_PE.BtnSaveSalary.clicked.connect(lambda : Ui_PE.SaveSalary())
		Ui_PE.BtnCancelSalary.clicked.connect(lambda : Ui_PE.CancelSalary())

		Ui_PE.BtnEditAllow.clicked.connect(lambda : Ui_PE.EditAllow())
		Ui_PE.BtnSaveAllow.clicked.connect(lambda : Ui_PE.SaveAllow())
		Ui_PE.BtnCancelAllow.clicked.connect(lambda : Ui_PE.CancelAllow())

		Ui_PE.BtnEditCash.clicked.connect(lambda : Ui_PE.EditCash())
		Ui_PE.BtnSaveCash.clicked.connect(lambda : Ui_PE.SaveCash())
		Ui_PE.BtnCancelCash.clicked.connect(lambda : Ui_PE.CancelCash())

		Ui_PE.BtnEditSalary.hide()
		Ui_PE.BtnEditAllow.hide()
		Ui_PE.BtnEditCash.hide()

		Ui_PE.BtnAddAllow.clicked.connect(lambda: Ui_BalanceForm.showBalanceForm("Add Allowance"))
		Ui_PE.BtnAddCash.clicked.connect(lambda: Ui_BalanceForm.showBalanceForm("Add Cash Advance"))

		# selection function

		Ui_PE.PEList.itemClicked.connect(Ui_PE.get_info)

		#table selection 

		Ui_PE.TBLAllowance.selectionModel().selectionChanged.connect(Ui_PE.tableAllowSelect)
		Ui_PE.TBLCash.selectionModel().selectionChanged.connect(Ui_PE.tableCashSelect)



		Ui_PE.LERate.setEnabled(False)
		Ui_PE.DateWorkStart.setEnabled(False)
		Ui_PE.DateWorkEnd.setEnabled(False)

		#balance remove
		Ui_PE.BtnRemoveCash.clicked.connect(Ui_PE.removeRowCash)
		Ui_PE.BtnRemoveAllow.clicked.connect(Ui_PE.removeRowAllow)

		my_regex = QtCore.QRegExp("^\\d{1,6}(\\.\\d{1,2})?$")
		my_validator = QtGui.QRegExpValidator(my_regex, Ui_PE.LERate)
		Ui_PE.LERate.setValidator(my_validator)


		

	def removeRowAllow():
		try:
			if Ui_PE.Allowid > 0:
				if (Dialog.confirm_dialog("Are you sure you want to remove this record?") == QMessageBox.Ok):
					cursor = con.cursor()
					query2 = (f"DELETE FROM `projecte_balance` WHERE `id` = {Ui_PE.Allowid}")
					cursor.execute(query2)
					con.commit()
					Ui_PE.Allowid=0
					Ui_PEForm.show_dialog("Allowance Record has been removed from the employee")
					Ui_PE.SaveAllow2()

					Ui_PE.getAllowance(Ui_PE.TBLAllowance,Ui_PE.not_editable,False)

					Ui_Activity.record_activity("admin",f"Removed Allowance Record of {Ui_PE.LEName.text()} in Project: {Ui_PE.LBProjectTitle.text()}")
				  
			else:
				Ui_PEForm.show_dialog("Please select a row first")

		except:
			Ui_PEForm.show_dialog(str(sys.exc_info()))

	def removeRowCash():
		try:
			if Ui_PE.Cashid > 0:
				if (Dialog.confirm_dialog("Are you sure you want to remove this record?") == QMessageBox.Ok):
					cursor = con.cursor()
					query2 = (f"DELETE FROM `projecte_balance` WHERE `id` = {Ui_PE.Cashid}")
					cursor.execute(query2)
					con.commit()
					query2 = (f"DELETE FROM `projecte_balance` WHERE `id` = {Ui_PE.Cashid+1}")
					cursor.execute(query2)
					con.commit()
					Ui_PE.Cashid=0
					Ui_PEForm.show_dialog("Cash Advance Record has been removed from the employee")

					Ui_Activity.record_activity("admin",f"Removed Cash Record of {Ui_PE.LEName.text()} in Project: {Ui_PE.LBProjectTitle.text()}")
				  

					Ui_PE.getCashAdvance(Ui_PE.TBLCash,Ui_PE.not_editable,False)
					Ui_PE.SaveCash2()
			else:
				Ui_PEForm.show_dialog("Please select a row first")

		except:
			Ui_PEForm.show_dialog(str(sys.exc_info()))



	def tableAllowSelect(selected, deselected):
		for x in selected.indexes():
			x=x.row()
			Ui_PE.Allowid=Ui_PE.TBAid[x]


	def tableCashSelect(selected, deselected):
		for x in selected.indexes():
			x=x.row()
			Ui_PE.Cashid=Ui_PE.TBCid[x]



class Ui_BalanceForm(object):
	DisplayGroup2=""
	BtnSubmit=""
	BtnCancel=""

	LBTitle=""
	LBBalance=""


	LEBalance=""
	dateEdit=""

	title=""


	def showBalanceForm(title):
		Ui_BalanceForm.DisplayGroup2.show()
		Ui_BalanceForm.title = title
		Ui_BalanceForm.LBTitle.setText( f"{Ui_BalanceForm.title}\nForm")
		Ui_BalanceForm.LBBalance.setText(str(Ui_BalanceForm.title))

		try:
			cursor = con.cursor()
			query = f"SELECT * FROM `projects` WHERE `project_id`={Ui_PE.projectid}"
			cursor.execute(query)
			res = cursor.fetchall()
			d1=""
			d2=""
			for x in res:
				d1=x[4]
				d2=x[5]
			# process date
			startdate = QDate(Ui_PE.process_date(d1))
			enddate = QDate(Ui_PE.process_date(d2))
			# set min max
			Ui_BalanceForm.dateEdit.setMinimumDate(startdate)
			Ui_BalanceForm.dateEdit.setMaximumDate(enddate)
			#set date start dates
			set_start = QDate(startdate)
			Ui_BalanceForm.dateEdit.setDate(set_start)
		except:
			Dialog.msg_dialog("Server Error")


	def cancelBalanceForm():
		x = Ui_PEForm.cancel_dialog("Are you sure you want to cancel?")
		if x:
			Ui_BalanceForm.DisplayGroup2.hide()
			now = QDate.currentDate()
			Ui_BalanceForm.dateEdit.setDate(now)
			Ui_BalanceForm.LEBalance.setText("")

			Ui_PE.Allowid=0
			Ui_PE.Cashid=0
	def checkMaxBalance():
		bools=True
		cash = Ui_BalanceForm.LEBalance.text()
		date = Ui_BalanceForm.dateEdit.date()
		maxCash=Ui_PE.LERate.text()
		maxCash=float(maxCash)*8*6
		minusCash=0

		cursor = con.cursor()
		cursor.execute(f"SELECT * FROM `project_payroll` WHERE `project_id` = {Ui_PE.projectid} AND `employee_id` ={Ui_PE.itemid} ")
		res = cursor.fetchall()

		for x in res:
			d1= Ui_PE.process_date(x[3])
			d2= Ui_PE.process_date(x[4])

			if (date>=d1)&(date<=d2):
				minusCash=minusCash-float(x[11])

		maxCash = maxCash+minusCash

		if float(cash)<=maxCash:
			bools=True
		else:
			bools=False

		return bools

	def addBalance():
		if (len(Ui_BalanceForm.LEBalance.text()))>0:
			if (float(Ui_BalanceForm.LEBalance.text())>0):
				if (Ui_BalanceForm.checkMaxBalance()):
					Ui_BalanceForm.DisplayGroup2.hide()
					try:
						date = (f"{Ui_BalanceForm.dateEdit.date().year()},{Ui_BalanceForm.dateEdit.date().month()},{Ui_BalanceForm.dateEdit.date().day()}")
						cursor = con.cursor()
						query1="INSERT INTO projecte_balance(project_id,employee_id,title,`date`,balance) VALUES (%s,%s,%s,%s,%s)"
						query2=""
						if Ui_BalanceForm.title=="Less Cash Advance":
							query2=(Ui_PE.projectid,Ui_PE.itemid,Ui_BalanceForm.title,date,"-"+Ui_BalanceForm.LEBalance.text())
						else:
							query2=(Ui_PE.projectid,Ui_PE.itemid,Ui_BalanceForm.title,date,Ui_BalanceForm.LEBalance.text())

						cursor.execute(query1,query2)
						con.commit()

						if Ui_BalanceForm.title=="Add Cash Advance":
							title="Less Cash Advance"
							query2=(Ui_PE.projectid,Ui_PE.itemid,title,date,"-"+Ui_BalanceForm.LEBalance.text())
							cursor.execute(query1,query2)
							con.commit()


						Ui_PE.getAllowance(Ui_PE.TBLAllowance,Ui_PE.not_editable,False)
						Ui_PE.getCashAdvance(Ui_PE.TBLCash,Ui_PE.not_editable,False)
						Ui_BalanceForm.updatePayrollBalance()

						#update full payroll
						cursor.execute(f"SELECT * FROM `project_payroll` WHERE `project_id`={Ui_PE.projectid} AND `employee_id`={Ui_PE.itemid}")
						res = cursor.fetchall()

						for x in res:
							rateDay=float(x[7])*8
							AmountReg=float(x[7])*float(x[8])
							AmountOT=float(x[9])*float(x[7])
							AmountOT= AmountOT + (float(AmountOT)*0.3)
							TotalAmount = AmountReg+AmountOT+x[10]
							Netpay=TotalAmount+x[12]

							query2 = f"UPDATE `project_payroll` SET `rateDay`={rateDay}, `AmountReg`={AmountReg}, `AmountOT`={AmountOT}, `TotalAmount`={TotalAmount}, `Netpay`={Netpay} WHERE `id`={x[0]}"
							cursor.execute(query2)
							con.commit()

						msgBox = QMessageBox()
						msgBox.setIcon(QMessageBox.Information)
						msgBox.setText(f"{Ui_BalanceForm.title} was added successfully")
						msgBox.setWindowTitle("Message Alert")
						msgBox.setStandardButtons(QMessageBox.Ok)
						msgBox.buttonClicked.connect(msgBox.close)

						Ui_Activity.record_activity("admin",f"{Ui_BalanceForm.title} Record of {Ui_PE.LEName.text()} in Project: {Ui_PE.LBProjectTitle.text()}")
						
						returnValue = msgBox.exec()
						if returnValue == QMessageBox.Ok:
							Ui_BalanceForm.DisplayGroup2.hide()
							now = QDate.currentDate()
							Ui_BalanceForm.dateEdit.setDate(now)
							Ui_BalanceForm.LEBalance.setText("")

							Ui_PE.Allowid=0
							Ui_PE.Cashid=0

					except :
						Ui_PEForm.show_dialog(str(sys.exc_info()))
				else:
					Ui_PEForm.show_dialog("Input exceeded the Maximum Cash Advance for the week Selected")
			else:
				Ui_PEForm.show_dialog("Invalid Input")
		else:
			Ui_PEForm.show_dialog("Please complete the form first")

	def updatePayrollBalance():
		cursor = con.cursor()
		try:
			
			Ui_PE.Allowid=0
			Ui_PE.Cashid=0

			cursor.execute(f"SELECT * FROM `projecte_balance` WHERE `project_id`={Ui_PE.projectid} AND `employee_id`={Ui_PE.itemid} AND `title`='Add Allowance'")
			res1 = cursor.fetchall()

			cursor.execute(f"SELECT * FROM `projecte_balance` WHERE `project_id`={Ui_PE.projectid} AND `employee_id`={Ui_PE.itemid} AND `title`='Add Cash Advance'")
			res2 = cursor.fetchall()

			cursor.execute(f"SELECT * FROM `projecte_balance` WHERE `project_id`={Ui_PE.projectid} AND `employee_id`={Ui_PE.itemid} AND `title`='Less Cash Advance'")
			res3 = cursor.fetchall()

			cursor.execute(f"SELECT * FROM `project_payroll` WHERE `project_id`={Ui_PE.projectid} AND `employee_id`={Ui_PE.itemid}")
			res4 = cursor.fetchall()

			startDate=[]
			endDate=[]

			
			for x in res4:
				startDate.append(x[3])
				endDate.append(x[4])

			# Update Allowance
			for x in range(0,len(startDate)):
				dateZ= ""
				dateX=""
				dateY=""
				allowance=0

				dateX=QDate(Ui_PE.process_date(startDate[x]))
				dateY=QDate(Ui_PE.process_date(endDate[x])) 

				for y in res1:
					dateZ= QDate(Ui_PE.process_date(y[4]))
					if (dateZ>=dateX) & (dateZ<=dateY):
						allowance=allowance+float(y[5])

				#update payroll week here
				d1=dateX.toString("yyyy,MM,dd")
				d2=dateY.toString("yyyy,MM,dd")

				query2 = f"UPDATE `project_payroll` SET `Allowance`={allowance} WHERE `startDate`='{d1}' AND `endDate`='{d2}' AND `employee_id`={Ui_PE.itemid} AND `project_id`={Ui_PE.projectid}"
				cursor.execute(query2)
				con.commit()

			# Update Cash Advance and less CA and balance
			for x in range(0,len(startDate)):
				dateZ=""
				dateX=""
				dateY=""
				CashAdv=0
				LessCashAdv=0

				dateX=QDate(Ui_PE.process_date(startDate[x]))
				dateY=QDate(Ui_PE.process_date(endDate[x])) 

				for y in res2:#cash advance
					dateZ= QDate(Ui_PE.process_date(y[4]))
					if (dateZ>=dateX) & (dateZ<=dateY):
						CashAdv=CashAdv+float(y[5])

				for y in res3:#less cash advance
					dateZ= QDate(Ui_PE.process_date(y[4]))
					if (dateZ>=dateX) & (dateZ<=dateY):
						LessCashAdv=LessCashAdv+float(y[5])


				#update payroll week here
				d1=dateX.toString("yyyy,MM,dd")
				d2=dateY.toString("yyyy,MM,dd")

				balance = CashAdv+LessCashAdv

				query2 = f"UPDATE `project_payroll` SET `CashAdv`={CashAdv},`LessCA`={LessCashAdv},`Balance`={balance} WHERE `startDate`='{d1}' AND `endDate`='{d2}' AND `employee_id`={Ui_PE.itemid}  AND `project_id`={Ui_PE.projectid}"
				cursor.execute(query2)
				con.commit()


		except:
			Ui_PEForm.show_dialog(str(sys.exc_info())) 


	def BalanceForm(DashbaordWindow):

		Ui_BalanceForm.DisplayGroup2 = QtWidgets.QGroupBox(DashbaordWindow)
		Ui_BalanceForm.DisplayGroup2.setGeometry(QtCore.QRect(0, 0, 1230, 703))
		Ui_BalanceForm.DisplayGroup2.setStyleSheet("\n""")
		Ui_BalanceForm.DisplayGroup2.setTitle("")
		Ui_BalanceForm.DisplayGroup2.setObjectName("DisplayGroup")
		Ui_BalanceForm.DisplayGroup2.hide()
		# Adds

		Bg = QtWidgets.QLabel(Ui_BalanceForm.DisplayGroup2)
		Bg.setEnabled(True)
		Bg.setGeometry(QtCore.QRect(0, 0, 1230, 703))
		Bg.setMinimumSize(QtCore.QSize(1230, 703))
		Bg.setMaximumSize(QtCore.QSize(1230, 703))
		Bg.setStyleSheet("background-color: rgb(0, 0, 0,.9);")

		Designation = QtWidgets.QGroupBox(Ui_BalanceForm.DisplayGroup2)
		Designation.setGeometry(QtCore.QRect(500, 180, 561, 621))
		Designation.setStyleSheet(".QLabel{color:white;}\n"
											 ".QPushButton{color:white;}\n"
											 ".QGroupBox{border:none;}\n")
		Designation.setTitle("")
		Designation.setObjectName("Designation")



		
		BGForm1 = QtWidgets.QLabel(Designation)
		BGForm1.setGeometry(QtCore.QRect(0, 0, 331, 261))
		BGForm1.setStyleSheet("background-color: rgb(148, 0, 2,.4);\n"
"border-radius:5px;")
		BGForm1.setText("")
		BGForm1.setObjectName("BGForm1")
		BGForm2 = QtWidgets.QLabel(Designation)
		BGForm2.setGeometry(QtCore.QRect(5, 5, 321, 251))
		BGForm2.setStyleSheet("background-color: rgb(148, 0, 2,.6);\n"
"border-radius:5px;")
		BGForm2.setText("")
		BGForm2.setObjectName("BGForm2")
		Ui_BalanceForm.LBTitle = QtWidgets.QLabel(Designation)
		Ui_BalanceForm.LBTitle.setGeometry(QtCore.QRect(15, 10, 301, 81))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(25)
		font.setBold(True)
		font.setWeight(75)
		Ui_BalanceForm.LBTitle.setFont(font)
		Ui_BalanceForm.LBTitle.setStyleSheet("color:white;")
		Ui_BalanceForm.LBTitle.setObjectName("LBTitle")
		Ui_BalanceForm.LBTitle.setAlignment(QtCore.Qt.AlignCenter)
		Ui_BalanceForm.BtnCancel = QtWidgets.QPushButton(Designation)
		Ui_BalanceForm.BtnCancel.setGeometry(QtCore.QRect(170, 200, 130, 31))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(12)
		font.setBold(True)
		font.setWeight(75)
		Ui_BalanceForm.BtnCancel.setFont(font)
		Ui_BalanceForm.BtnCancel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
		Ui_BalanceForm.BtnCancel.setStyleSheet("background-color: rgb(0, 0, 0,.9);\n"
"color:white;\n"
"border-radius:5px;")
		icon = QtGui.QIcon()
		icon.addPixmap(QtGui.QPixmap(":/Icons/Assets/FormCancelIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		Ui_BalanceForm.BtnCancel.setIcon(icon)
		Ui_BalanceForm.BtnCancel.setIconSize(QtCore.QSize(30, 30))
		Ui_BalanceForm.BtnCancel.setObjectName("BtnCancel")
		Ui_BalanceForm.BtnSubmit = QtWidgets.QPushButton(Designation)
		Ui_BalanceForm.BtnSubmit.setGeometry(QtCore.QRect(30, 200, 130, 31))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(12)
		font.setBold(True)
		font.setWeight(75)
		Ui_BalanceForm.BtnSubmit.setFont(font)
		Ui_BalanceForm.BtnSubmit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
		Ui_BalanceForm.BtnSubmit.setStyleSheet("background-color: rgb(0, 0, 0,.9);\n"
"color:white;\n"
"border-radius:5px;")
		icon1 = QtGui.QIcon()
		icon1.addPixmap(QtGui.QPixmap(":/Icons/Assets/FormSubmitIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		Ui_BalanceForm.BtnSubmit.setIcon(icon1)
		Ui_BalanceForm.BtnSubmit.setIconSize(QtCore.QSize(30, 30))
		Ui_BalanceForm.BtnSubmit.setObjectName("BtnSubmit")
		Ui_BalanceForm.LEBalance = QtWidgets.QLineEdit(Designation)
		Ui_BalanceForm.LEBalance.setGeometry(QtCore.QRect(170, 130, 130, 30))
		Ui_BalanceForm.LEBalance.setStyleSheet("background-color: rgba(255, 255, 255);\n"
"border-radius:5px;")
		Ui_BalanceForm.LEBalance.setObjectName("LEBalance")
		Ui_BalanceForm.dateEdit = QtWidgets.QDateEdit(Designation)
		Ui_BalanceForm.dateEdit.setGeometry(QtCore.QRect(30, 130, 130, 31))
		Ui_BalanceForm.dateEdit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
		Ui_BalanceForm.dateEdit.setStyleSheet("color:maroon;\n"
"background-color:rgb(255, 255, 255);\n"
"border-radius:5px;")
		Ui_BalanceForm.dateEdit.setCalendarPopup(True)
		Ui_BalanceForm.dateEdit.setObjectName("dateEdit")
		LBDate = QtWidgets.QLabel(Designation)
		LBDate.setGeometry(QtCore.QRect(30, 110, 47, 13))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(12)
		font.setBold(True)
		font.setWeight(75)
		LBDate.setFont(font)
		LBDate.setStyleSheet("color:white;")
		LBDate.setObjectName("LBDate")
		Ui_BalanceForm.LBBalance = QtWidgets.QLabel(Designation)
		Ui_BalanceForm.LBBalance.setGeometry(QtCore.QRect(170, 110, 130, 16))
		font = QtGui.QFont()
		font.setFamily("Calibri")
		font.setPointSize(12)
		font.setBold(True)
		font.setWeight(75)
		Ui_BalanceForm.LBBalance.setFont(font)
		Ui_BalanceForm.LBBalance.setStyleSheet("color:white;")
		Ui_BalanceForm.LBBalance.setObjectName("LBBalance")

		_translate = QtCore.QCoreApplication.translate
		Ui_BalanceForm.LBTitle.setText(_translate("DashbaordWindow", f"Add {Ui_BalanceForm.title}\nForm"))
		Ui_BalanceForm.BtnCancel.setText(_translate("DashbaordWindow", "  Cancel"))
		Ui_BalanceForm.BtnSubmit.setText(_translate("DashbaordWindow", "  Add"))
		LBDate.setText(_translate("DashbaordWindow", "Date"))
		Ui_BalanceForm.LBBalance.setText(_translate("DashbaordWindow", Ui_BalanceForm.title))


		Ui_BalanceForm.BtnCancel.clicked.connect(lambda: Ui_BalanceForm.cancelBalanceForm())
		Ui_BalanceForm.BtnSubmit.clicked.connect(lambda: Ui_BalanceForm.addBalance())


		my_regex = QtCore.QRegExp("^\\d{1,6}(\\.\\d{1,2})?$")
		my_validator = QtGui.QRegExpValidator(my_regex, Ui_BalanceForm.LEBalance)
		Ui_BalanceForm.LEBalance.setValidator(my_validator)


class Ui_PEForm(object):
		DisplayGroup2 = ""
		ListEmployee=""

		selectedid=0

		employee_id = []
		employee_fname = []
		employee_lname = []
		employee_mname = []
		employee_position = []

		def addtoProject():
				if Ui_PEForm.selectedid > 0:
						try:
								cursor = con.cursor()

								query = f"SELECT * FROM `projects` WHERE `project_id`={Ui_PE.projectid}"
								cursor.execute(query)
								res = cursor.fetchall()

								d1=""
								d2=""
								location=""

								for x in res:
									location=x[3]
									d1=x[4]
									d2=x[5]

								query1 = "INSERT INTO projecte(project_id, employee_id,rate,work_start,work_end) VALUES (%s,%s,%s,%s,%s)"
								query5 = (Ui_PE.projectid, Ui_PEForm.selectedid,62.5,d1,d2)
								cursor.execute(query1, query5)
								con.commit()

								query2 = f"UPDATE `employees` SET `Designated`='Yes',`Current_Site`='{location}' WHERE id={Ui_PEForm.selectedid}"

								cursor.execute(query2)
								con.commit()

								startdate=QDate(Ui_PE.process_date(d1))
								enddate=QDate(Ui_PE.process_date(d2))
								enddate=enddate.addDays(1)
								
								while startdate<enddate:
									query1 = "INSERT INTO projectdtr(project_id, employee_id,`date`,AM_TimeIN,AM_TimeOut,PM_TimeIN,PM_TimeOut,RH,OT) VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s)"
									query5 = (Ui_PE.projectid, Ui_PEForm.selectedid,startdate.toString("yyyy,MM,dd"),0,0,0,0,0,0)
									cursor.execute(query1, query5)
									con.commit()
									startdate=startdate.addDays(1)


								#get payroll weeks

								week_listX = []
								week_listY = []
								startdate=""
								enddate=""

								try:
									cursor = con.cursor()
									cursor.execute(f"SELECT * FROM `projects` WHERE `project_id`={Ui_PE.projectid}")
									res = cursor.fetchall()
									for x in res:
										startdate=QDate(Ui_PE.process_date(x[4]))
										enddate=QDate(Ui_PE.process_date(x[5]))


									while startdate<enddate:
										for i in range(0,7):
											if i==0:
												week_listX.append(startdate.toString("yyyy,MM,dd"))
											if startdate==enddate:
												week_listY.append(startdate.toString("yyyy,MM,dd"))
												break
											if i==6:
												week_listY.append(startdate.toString("yyyy,MM,dd"))

											startdate=startdate.addDays(1)
								except:
									Ui_PEForm.show_dialog(str(sys.exc_info()))

										
								#creating payroll


								query = f"SELECT * FROM `employees` WHERE `id`={Ui_PEForm.selectedid}"
								cursor.execute(query)
								res = cursor.fetchall()

								suffix=""
								if res[0][4]=="N/A":
									suffix=""
								else:
									suffix=" "+res[0][4]


								position=res[0][15]
								full_name = (f"{res[0][1]} {suffix}, {res[0][2]} {res[0][3]}.")

								for x in range(0,len(week_listX)):
									query1 = "INSERT INTO project_payroll(`project_id`, `employee_id`,`startDate`,`endDate`, `name`, `position`, `rateHrs`, `TRH`, `OT`, `Allowance`, `CashAdv`, `LessCA`, `Balance`, `Netpay`, `rateDay`, `AmountReg`, `AmountOT`, `TotalAmount`) VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)"
									query5 = (Ui_PE.projectid, Ui_PEForm.selectedid,week_listX[x],week_listY[x],full_name,position,62.5,0,0,0,0,0,0,0,500,0,0,0)
									cursor.execute(query1, query5)
									con.commit()

								Ui_Activity.record_activity("admin",f"Add Employee to Project: {Ui_PE.LBProjectTitle.text()}")
				 



						except:
								Ui_PEForm.show_dialog("Failed to add employee to the Project")

						Ui_PEForm.show_dialog("Employee added successfully to the project")
						Ui_PEForm.DisplayGroup2.hide()
						Ui_PEForm.getActiveEmployee()
						Ui_PE.getProjEmp()
				else:
						Ui_PEForm.show_dialog("Please select an Employee First")

		def setId(item):
				Ui_PEForm.selectedid = item.value

		def getActiveEmployee():
				Ui_PEForm.ListEmployee.clear()
				Ui_PEForm.employee_id = []
				Ui_PEForm.employee_fname = []
				Ui_PEForm.employee_lname = []
				Ui_PEForm.employee_mname = []
				Ui_PEForm.employee_position = []
				# get_info_database
				try:
						res = Ui_PEForm.mysql_select()

						for x in res:
								Ui_PEForm.employee_id.append(x[0])
								Ui_PEForm.employee_fname.append(x[2])
								Ui_PEForm.employee_lname.append(x[1])
								Ui_PEForm.employee_mname.append(x[3])
								Ui_PEForm.employee_position.append(x[15])

				except mysql.connector.Error as e:
						Ui_PEForm.show_dialog(e)

				# insert elements
				index = 0
				while index < len(Ui_PEForm.employee_id):
						try:
								full_name = (
										f"{Ui_PEForm.employee_lname[index]}, {Ui_PEForm.employee_fname[index]} {Ui_PEForm.employee_mname[index]}.\n[{Ui_PEForm.employee_position[index]}]")
								item = QtWidgets.QListWidgetItem(full_name)
								item.setBackground(QColor('#666666')) if (index % 2) == 0 else item.setBackground(
										QColor('#595959'))
								item.value = Ui_PEForm.employee_id[index]
								item.setTextAlignment(QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)


								Ui_PEForm.ListEmployee.addItem(item)


								index = index + 1
						except:
								Ui_PEForm.show_dialog(str(sys.exc_info()))

		def show_dialog(msg):
				msgBox = QMessageBox()
				msgBox.setIcon(QMessageBox.Information)
				msgBox.setText(msg)
				msgBox.setWindowTitle("Message Alert")
				msgBox.setStandardButtons(QMessageBox.Ok)
				msgBox.buttonClicked.connect(msgBox.close)

				returnValue = msgBox.exec()
				# if returnValue == QMessageBox.Ok:

		def mysql_select():
				cursor = con.cursor()
				cursor.execute("SELECT * FROM `employees` WHERE `Work_Status`='Active' AND `Designated`='No'")

				return cursor.fetchall()

		def showForm():
				Ui_PEForm.DisplayGroup2.show()
				Ui_PEForm.getActiveEmployee()
				Ui_PEForm.selectedid = 0


		def hideForm():
				x = Ui_PEForm.cancel_dialog("Are you sure you want to cancel?")
				if x:
						Ui_PEForm.DisplayGroup2.hide()


		def cancel_dialog(msg):
				msgBox = QMessageBox()
				msgBox.setIcon(QMessageBox.Information)
				msgBox.setText(msg)
				msgBox.setWindowTitle("Message Alert")
				msgBox.setStandardButtons(QMessageBox.Ok | QMessageBox.Cancel)
				msgBox.buttonClicked.connect(msgBox.close)

				returnValue = msgBox.exec()
				if returnValue == QMessageBox.Ok:
						return True




		def DesignateForm(DashbaordWindow):
				Ui_PEForm.DisplayGroup2 = QtWidgets.QGroupBox(DashbaordWindow)
				Ui_PEForm.DisplayGroup2.setGeometry(QtCore.QRect(0, 0, 1230, 703))
				Ui_PEForm.DisplayGroup2.setStyleSheet("\n""")
				Ui_PEForm.DisplayGroup2.setTitle("")
				Ui_PEForm.DisplayGroup2.setObjectName("DisplayGroup")
				Ui_PEForm.DisplayGroup2.hide()

				# Adds
				Bg = QtWidgets.QLabel(Ui_PEForm.DisplayGroup2)
				Bg.setEnabled(True)
				Bg.setGeometry(QtCore.QRect(0, 0, 1230, 703))
				Bg.setMinimumSize(QtCore.QSize(1230, 703))
				Bg.setMaximumSize(QtCore.QSize(1230, 703))
				Bg.setStyleSheet("background-color: rgb(0, 0, 0,.9);")

				designateGroup = QtWidgets.QGroupBox(Ui_PEForm.DisplayGroup2)
				designateGroup.setGeometry(QtCore.QRect(430, 80, 561, 621))
				designateGroup.setStyleSheet(".QLabel{color:white;}\n"
											 ".QPushButton{color:white;}\n"
											 ".QGroupBox{border:none;}\n")
				designateGroup.setTitle("")
				designateGroup.setObjectName("add_project_group")

				# con
				BGForm1 = QtWidgets.QLabel(designateGroup)
				BGForm1.setGeometry(QtCore.QRect(0, 0, 331, 571))
				BGForm1.setStyleSheet("background-color: rgb(148, 0, 2,.4);\n"
									  "border-radius:5px;")
				BGForm1.setText("")
				BGForm1.setObjectName("BGForm1")
				BGForm2 = QtWidgets.QLabel(designateGroup)
				BGForm2.setGeometry(QtCore.QRect(5, 5, 321, 561))
				BGForm2.setStyleSheet("background-color: rgb(148, 0, 2,.6);\n"
									  "border-radius:5px;")
				BGForm2.setText("")
				BGForm2.setObjectName("BGForm2")
				Ui_PEForm.ListEmployee = QtWidgets.QListWidget(designateGroup)
				Ui_PEForm.ListEmployee.setGeometry(QtCore.QRect(35, 80, 261, 421))
				font = QtGui.QFont()
				font.setFamily("Calibri")
				font.setPointSize(16)
				font.setBold(False)
				font.setWeight(50)
				Ui_PEForm.ListEmployee.setFont(font)
				Ui_PEForm.ListEmployee.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
				Ui_PEForm.ListEmployee.setLayoutDirection(QtCore.Qt.RightToLeft)
				Ui_PEForm.ListEmployee.setStyleSheet("background-color: rgb(120, 120, 120,.6);\n"
										   "color:white;")
				Ui_PEForm.ListEmployee.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
				Ui_PEForm.ListEmployee.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
				Ui_PEForm.ListEmployee.setAutoScrollMargin(0)
				Ui_PEForm.ListEmployee.setItemAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
				Ui_PEForm.ListEmployee.setObjectName("Ui_PEForm.ListEmployee")
				item = QtWidgets.QListWidgetItem()
				item.setTextAlignment(QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
				brush = QtGui.QBrush(QtGui.QColor(255, 0, 0, 0))
				brush.setStyle(QtCore.Qt.SolidPattern)
				item.setBackground(brush)
				Ui_PEForm.ListEmployee.addItem(item)
				LBDesignation = QtWidgets.QLabel(designateGroup)
				LBDesignation.setGeometry(QtCore.QRect(25, 20, 291, 51))
				font = QtGui.QFont()
				font.setFamily("Calibri")
				font.setPointSize(25)
				font.setBold(True)
				font.setWeight(75)
				LBDesignation.setFont(font)
				LBDesignation.setStyleSheet("color:white;")
				LBDesignation.setObjectName("LBDesignation")
				BtnCancel = QtWidgets.QPushButton(designateGroup)
				BtnCancel.setGeometry(QtCore.QRect(185, 520, 110, 31))
				font = QtGui.QFont()
				font.setFamily("Calibri")
				font.setPointSize(12)
				font.setBold(True)
				font.setWeight(75)
				BtnCancel.setFont(font)
				BtnCancel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
				BtnCancel.setStyleSheet("background-color: rgb(0, 0, 0,.9);\n"
										"color:white;\n"
										"border-radius:5px;")
				icon = QtGui.QIcon()
				icon.addPixmap(QtGui.QPixmap(":/Icons/Assets/FormCancelIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
				BtnCancel.setIcon(icon)
				BtnCancel.setIconSize(QtCore.QSize(30, 30))
				BtnCancel.setObjectName("BtnCancel")
				BtnSubmit = QtWidgets.QPushButton(designateGroup)
				BtnSubmit.setGeometry(QtCore.QRect(35, 520, 110, 31))
				font = QtGui.QFont()
				font.setFamily("Calibri")
				font.setPointSize(12)
				font.setBold(True)
				font.setWeight(75)
				BtnSubmit.setFont(font)
				BtnSubmit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
				BtnSubmit.setStyleSheet("background-color: rgb(0, 0, 0,.9);\n"
										"color:white;\n"
										"border-radius:5px;")
				icon1 = QtGui.QIcon()
				icon1.addPixmap(QtGui.QPixmap(":/Icons/Assets/FormSubmitIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
				BtnSubmit.setIcon(icon1)
				BtnSubmit.setIconSize(QtCore.QSize(30, 30))
				BtnSubmit.setObjectName("BtnSubmit")

				_translate = QtCore.QCoreApplication.translate

				item = Ui_PEForm.ListEmployee.item(0)
				item.setText(_translate("DashbaordWindow", "Juan Dela Cruz - Engineer"))
				LBDesignation.setText(_translate("DashbaordWindow", "Designate Employee"))
				BtnCancel.setText(_translate("DashbaordWindow", "  Cancel"))
				BtnSubmit.setText(_translate("DashbaordWindow", "  Add"))

				#functions
				BtnCancel.clicked.connect(lambda: Ui_PEForm.hideForm())
				BtnSubmit.clicked.connect(lambda: Ui_PEForm.addtoProject())


				# selection function
				Ui_PEForm.ListEmployee.itemClicked.connect(Ui_PEForm.setId)



